### ISSUE TITLE
Unicode strings in doctest files

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1074]
Several doctest files contain unicode strings (`egrep -l "u'" *.doctest`). Shouldn't these be (non-unicode) python 3 strings? @kmike would you please advise?

**Comment by kmike** [comment]
@stevenbird many tests may start failing in Python 2.x if we remove u'' prefixes from the example output. 'u' letters in doctest output are stripped by https://github.com/nltk/nltk/blob/develop/nltk/test/doctest_nose_plugin.py to smooth Python 2.x/3.x differences.

**Comment by kmike** [comment]
This is documented [here](https://github.com/nltk/nltk/blob/develop/web/dev/python3porting.rst#doctests-porting-notes); maybe it worths it to move these docs to a more visible location.

**Comment by dimazest** [comment]
Sometimes joining and printing the value helps, as in #1075.

**Comment by kmike** [comment]
@dimazest the test in #1075 shouldn't be failing because of `u` letters if executed using NLTK runtests script.

**Comment by dimazest** [comment]
Right. Though I prefer to use pytest instead of nose mostly because it's possible to get to set `pdb` tracebacks inside of doctests and then the plugin doesn't work.

I, personally, don't like the idea of adopting doctests to a test runner either, as the main point is to make them as clear to the reader as possible.

I  investigate how pytest can be configured to treat this correctly. Hopefully this can be sorted out without changing NLTK.
