### ISSUE TITLE
issue with data.py

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1081]
@longdt219 would you please try to diagnose the problem with accessing NLTK data here:

https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py34-jenkins,jdk=jdk8latestOnlineInstall/lastCompletedBuild/testReport/

I can't replicate it locally. I wonder if it is related to [recent changes to internals.py](https://github.com/nltk/nltk/commit/73fc6553574678198994b265cc32387133b6c8fd#diff-6d3d9c7d1794a239ab676fc6fce3131f).

(@alvations – please let us know if you see what the problem is, thanks.)

**Comment by alvations** [comment]
@stevenbird @longdt219 I couldn't replicate the problem too and I didn't spot any problem. I'm sorry if the changes made I've made caused the nosetest to break.

**Comment by alvations** [comment]
@stevenbird @longdt219 The errors disappeared after the recent PRs https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py34-jenkins,jdk=jdk8latestOnlineInstall/lastCompletedBuild/testReport/

I'm not sure what happened though.

**Comment by stevenbird** [comment]
Right, I don't know what has caused this either.

**Comment by longdt219** [comment]
Hi @stevenbird, @alvations, 
It shown again in the CI server. The problem is because all the nltk.data is not downloaded, instead the exception is thrown. 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "nltk/**init**.py", line 129, in <module>
    from nltk.chunk import *
  File "nltk/chunk/**init**.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "nltk/chunk/api.py", line 13, in <module>
    from nltk.parse import ParserI
  File "nltk/parse/**init**.py", line 77, in <module>
    from nltk.parse.malt import MaltParser
  File "nltk/parse/malt.py", line 12, in <module>
    from six import text_type
ImportError: No module named six
NLTK data download failed: 1

I modified the jenkins.sh file so that the required package is download. See PR #1085

**Comment by stevenbird** [comment]
Thanks @longdt219. Let's see if this works.

**Comment by alvations** [comment]
To resolve https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py34-jenkins,jdk=jdk8latestOnlineInstall/lastCompletedBuild/testReport/%3Cnose/suite/ContextSuite_context_gluesemantics_malt_fixt__setup/

Would it be more intuitive to:
- Change the class call from `depparser = MaltParser()` to `depparser = MaltParser('maltparser-1.7.2')` at https://github.com/nltk/nltk/blob/develop/nltk/test/gluesemantics_malt_fixt.py or
- Make the default `__init__()` to force `parser_dirname='maltparser-1.7.2'` at https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py

However, the `MaltParser()` can also take `parser_dirname='maltparser-1.8'`, so I would prefer the first solution.

The example call for `MaltParser` would look something like https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py#L337

**Comment by alvations** [comment]
PR #1101 should fix the last standing problems in the build test (https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py34-jenkins,jdk=jdk8latestOnlineInstall/lastCompletedBuild/testReport/)

**Comment by alvations** [comment]
That's resolved too, so close too?
