### ISSUE TITLE
six dependency

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1087]
[malt.py](https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py) introduces a dependency on `six`, which is not required anywhere else in NLTK. @kmike – do you think we can avoid this?

**Comment by longdt219** [comment]
Actually Six is required for Gensim package too.

**Comment by kmike** [comment]
I'm fine with six dependency. If I'd be doing Python 3 port now I'd be definitely using six instead of creating a custom compat.py module.

But if six is required we should add it to `install_requires` in setup.py, to make it install automatically.

**Comment by stevenbird** [comment]
Thanks @kmike – I added it to the requirements files for pip and tox, since we're not using `install_requires`.

**Comment by alvations** [comment]
`six` would help a lot in resolving quite a lot of py2->py3, especially unicode problems.

**Comment by kmike** [comment]
@stevenbird I think we should start using `install_requires` for six because it is the only non-optional dependency, and it is good to get it installed automatically. We can do it because we already switched to setuptools.

@alvations there are six-inspired utilities in https://github.com/nltk/nltk/blob/develop/nltk/compat.py; most unicode-related stuff should be covered. NLTK's compat.py is a copy-paste from an ancient six version, improved for NLTK needs. In 2012 it was not clear six will be a way to go, that it is stable enough, etc, and it was not clear setuptools is maintained well enough to rely on it. We also needed some custom utilities, so now compat.py is a bundled version of a very old `six` with a lot of extra stuff.

**Comment by stevenbird** [comment]
Thanks for the suggestion @kmike. I'll create a new low-priority issue to update our compatibility code.

**Comment by dimazest** [comment]
Just a small comment. Even though NLTK doesn't use `install_requires`, other projects that depend on NLTK might use it. By listing dependencies in `install_requires` we not only making installation and packaging of NLTK easier, but also avoid surprises for the projects that depend on NLTK.

**Comment by stevenbird** [comment]
So, is six the only package that we need to list in `install_requires`? Can we move the other packages from [pip-req.txt](https://github.com/nltk/nltk/blob/develop/pip-req.txt) and remove it?

**Comment by kmike** [comment]
I think we shouldn't move other packages to install_requires because 1. they are optional, and 2. installation of these packages can fail because many of them are not pure-python.
