### ISSUE TITLE
Installing NLTK 3.0.5 on Windows

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1134]
It seems that `six` is not being automatically installed on some Windows machines.
https://groups.google.com/forum/#!topic/nltk-users/YhFSSvB8Has

**Comment by suyashbansal** [comment]
I am also getting the same error on windows. Now I installed the NLTK 3.0.4

**Comment by stevenbird** [comment]
@dimazest, @kmike – if you have any advice I'd love to hear it.

**Comment by dimazest** [comment]
My answer in the mailing list waits moderation. I'll rewrite it here.

How did you install NLTK (did you use pip, cloned github repo or the .zip distribution). What python version do you use?

**Comment by suyashbansal** [comment]
I installed NLTK by using the Windows installer provided at https://pypi.python.org/pypi/nltk

Also, I am using the latest version of Python i.d.e. python-3.5.0

**Comment by dimazest** [comment]
Thanks.

I thought that installer will work only with Python 2.6. That installer doesn't include dependencies. I'll have a look how include them into the installer.

**Comment by stevenbird** [comment]
It looks like six is not automatically installed on Windows, and it looks like it's a pain to install it manually (https://groups.google.com/forum/#!topic/nltk-users/YhFSSvB8Has). How about we include it in NLTK?

**Comment by dimazest** [comment]
+1 six is a single file, and we can distribute it as `nltk.six`, for example.

For a more complex set up I would suggest to use Anaconda or a similar software instead of windows installers.

**Comment by kmike** [comment]
> For a more complex set up I would suggest to use Anaconda or a similar software instead of windows installers.

Like pip and venv which are built-in in recent Python 3? :) Since https://github.com/nltk/nltk/pull/697 was opened some things changed: most important scientific packages got official Windows wheels, so AFAIK installing numpy/scipy/scikit-learn on Windows shouldn't be a problem if pip+venv are used.

Users will have to learn how to use pip anyways - e.g. for twython. Very few packages provide .exe installers.

Anaconda is also fine; one issue is that NLTK is a built-in Anaconda package, so by making a new release we won't be updating NLTK in Anaconda. For example, currently they provide NLTK 3.0.3, while the latest release is 3.0.5. Maybe it is possible to contact them to get control over releases, or maybe we can provide alternative packages, or maybe we can recommend using pip to install NLTK to Anaconda environments.

**Comment by kmike** [comment]
Anaconda is nice though: you download a couple hundred of MBs file and get a brand new Python with most important scientific packages pre-installed. One data point: I was doing a tutorial on ML text processing and just downloaded Anaconda distributions for all OSes and put them on USB flash sticks, then gave them to auditory. They had a mix of Linux, OS X and Windows laptops, and WiFi was almost non-working, but still there was no a single complain about how to install necessary software, and many people (I assume all who wanted) were able to folow the tutorial.

**Comment by dimazest** [comment]
My impression is that Anaconda devs and maintainers are quite open minded. Pandas have their own channel where they provide recent versions https://conda.anaconda.org/pandas

In my experience (a web development course about django and things) anaconda was the most reliable choice as it's supports all the major OSes.

**Comment by stevenbird** [comment]
So if I add `six`, I presume I can drop it from setup.py (`install_requires`) and from tox.ini.

**Comment by kmike** [comment]
@stevenbird yes, that's correct.

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/f4342ffe451c2fa6e3f48f9646c5f2a92018a260
