### ISSUE TITLE
POS taggers should return iterators not lists

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1151]

**Comment by zeehio** [comment]
I had the need for using iterators in my pos tagger tests (I am just starting to play with nltk) and I made a small modification (zeehio/nltk@b453d7f8c864b383e7c749ef7ba187336d933654) to nltk to train and check the accuracy using iterators. I don't know the nltk implementation details and having the testsuite broken makes it very difficult for me to check what has been broken by my (small) changes. If you want it as a starting point, you can fetch it from the link above. If you want help or coordination with this issue, feel free to ask, otherwise I will leave it to you.
