### ISSUE TITLE
Is this intended for TweetTokenizer?

### ISSUE THREAD

**Issue by jelmelk** [nltk/nltk#1155]
```
from nltk import word_tokenize
from nltk.tokenize import TweetTokenizer

tknz = TweetTokenizer()

tweet = str("@someone did you check out this #superawesome!! it's very cool 
            \xF0\x9F\x98\x81 http://t.co/ydfY2".encode('utf-8'))

tweet = tweet[2:-1]

print(word_tokenize(tweet))

print(tknz.tokenize(tweet))
```

The `word_tokenize` gives me the following:

```
['@', 'someone', 'did', 'you', 'check', 'out', 'this', '#', 'superawesome', '!', '!', 
 'it', "'s", 'very', 'cool', '\\xc3\\xb0\\xc2\\x9f\\xc2\\x98\\xc2\\x81', 'http', ':', 
 '//t.co/ydfY2']
```

However, `TweetTokenizer` splits the coding making the count for `\\` extremely large and not possible to use emoji

```
['@someone', 'did', 'you', 'check', 'out', 'this', '#superawesome', '!', '!', 
 "it's", 'very', 'cool', '\\', 'xc3', '\\', 'xb0', '\\', 'xc2', '\\', 'x9f', '\\', 'xc2', 
 '\\', 'x98', '\\', 'xc2', '\\', 'x81', 'http://t.co/ydfY2']
```

Is this intended? If so is it possible to change?

**Comment by kmike** [comment]
This doesn't look right:

```
tweet = str("@someone did you check out this #superawesome!! it's very cool 
            \xF0\x9F\x98\x81 http://t.co/ydfY2".encode('utf-8'))
```

What Python version are you using? If it is Python 2.x then `tweet` becomes a bytestring (while you should pass unicode to NLTK methods). If it is Python 3 you're getting str representation of a bytes object, this is not what you want: 

```
>>> str('test'.encode('utf8'))
"b'test'"
```

**Comment by kmike** [comment]
In Python 3 you'd want to do this:

```
tweet = b"@someone did you check out this #superawesome!! it's very cool \xF0\x9F\x98\x81 http://t.co/ydfY2".decode('utf-8')
```

**Comment by jelmelk** [comment]
That's just an example (apparently a poor one), I usually have the tweets written to a csv file and I've been pulling from that. 

In the actual scenario I am using Python3, pulling data into pandas df and from that using TweetTokenizer, but the emoji is still being broken up.
![image](https://cloud.githubusercontent.com/assets/14167775/10259033/be3e30b0-6931-11e5-8267-40a211f98fa5.png)

**Comment by kmike** [comment]
Your example works perfectly fine in Python 3 if fed with correct input:

```
In [1]: from nltk.tokenize import TweetTokenizer

In [2]: tweet = b"@someone did you check out this #superawesome!! it's very cool \xF0\x9F\x98\x81 http://t.co/ydfY2".decode('utf-8')

In [3]: tweet
Out[3]: "@someone did you check out this #superawesome!! it's very cool 😁 http://t.co/ydfY2"

In [4]: tknz = TweetTokenizer()

In [5]: tknz.tokenize(tweet)
Out[5]: 
['@someone',
 'did',
 'you',
 'check',
 'out',
 'this',
 '#superawesome',
 '!',
 '!',
 "it's",
 'very',
 'cool',
 '😁',
 'http://t.co/ydfY2']
```

**Comment by jelmelk** [comment]
Is it not possible to keep the coding in order to display "\xF0\x9F\x98\x81" as word_tokenizer?

**Comment by kmike** [comment]
There must be something wrong either in a way you're reading the data or with CSV data itself. Maybe pandas doesn't use right encoding or escaping by default and you need to tweak options to make encoding compatible with your CSV file, or maybe instead of raw data there is escaped data stored in CSV file.

> Is it not possible to keep the coding in order to display "\xF0\x9F\x98\x81" as word_tokenizer?

It may be possible, but I'm not sure it is a good feature to support: "\xF0\x9F\x98\x81" looks like incorrectly decoded unicode symbol, not like a real text - it seems somewhere data were escaped twice but unescaped once. `word_tokenize` may work for it only by a coincidence.

**Comment by jelmelk** [comment]
So here's what I tried, if I take the exact "tweet" that I gave in the original example and save it to a csv file as `b"@someone did you check out this #superawesome!! it's very cool \xF0\x9F\x98\x81 http://t.co/ydfY2"`. I import it with pandas as such `df = pd.read_csv('kjd.csv', header=None, names=['TWEET'])`.

Then I type :

```
for tweet in df['TWEET']:
    print(tknz.tokenize(bytes(tweet, 'utf-8').decode('utf-8')))
```

Which I know is a bit overkill, but when you import it with pandas it's automatically converted into a string (I tested it). As you showed in the example if you take the `byte` and `decode` it works just fine. However, I'm still getting the "emoji" broken up as I showed in the snapshot.

I even tried importing the file with encoding (didn't seem right) but didn't change anything. How come it's working if I specifically assign the example tweet to a variable, but won't if it's imported under pandas then converted into bytes?

**Comment by kmike** [comment]
Could you please show the code to save the example to a csv file?

**Comment by jelmelk** [comment]
I simply saved the tweet manually into a csv file as `b"@someone did you check out this #superawesome!! it's very cool \xF0\x9F\x98\x81` similar to when doing `tweet=b"@someone did you check out this #superawesome!! it's very cool \xF0\x9F\x98\x81`

**Comment by kmike** [comment]
> I simply saved the tweet manually into a csv file as b"@someone did you check out this #superawesome!! it's very cool \xF0\x9F\x98\x81 similar to when doing tweet=b"@someone did you check out this #superawesome!! it's very cool \xF0\x9F\x98\x81

No, this is not correct. `b"\xF0\x9F\x98\x81"` is a literal for a 4-byte sequence:

```
>>> len(b"\xF0\x9F\x98\x81")
4
>>> [x for x in b"\xF0\x9F\x98\x81"]
[240, 159, 152, 129]
```

If you copy `\xF0\x9F\x98\x81` and paste it to a CSV file using a text editor you won't get the same bytes - you're copying and pasting a representation of this data (the way Python displays it), not the data itself. For example, `\xF0` means a hex value F0 or int value 240. `b"\xF0\x9F\x98\x81"` was 4 bytes long, but if you copy-paste it as text it will become 16 bytes long - `\` symbol, then `x` symbol, then `F` symbol, etc. Also, you shouldn't copy-paste b letter (it has no meaning outside Python, it is just what Python prints to show the constant is bytes) and quotes (the same; they may work by chance because csv also uses quotes).

I think some tutorial on unicode and encodings can help avoid confusion; https://docs.python.org/3/howto/unicode.html may work. There were also some nice PyCon talks - check https://www.google.com/search?q=python+unicode&tbm=vid.

I think this is not an NLTK issue because given correct input tokenizer works (as shown in the example).

**Comment by jelmelk** [comment]
Thank you for the detailed explanation. I'll go ahead and close the issue.

**Comment by ewan-klein** [comment]
Many thanks @kmike for all your helpful input on this issue.
