### ISSUE TITLE
TweetTokenizer hangs

### ISSUE THREAD

**Issue by jelmelk** [nltk/nltk#1158]
I have the following code that I use to  TweetTokenize a day worth of tweet collection, ~2.2M tweets.

```
import pandas as pd
from nltk.tokenize import TweetTokenizer

tknz = TweetTokenizer()

df_25 = pd.read_csv('2015-09-25.csv', header=None,\
                     names=['ID', 'ORIG', 'LAT', 'LONG', 'CITY', 'STATE', 'TIMESTAMP', 'TWEET_ID', 'TWEET'], \
                     low_memory=False, \
                     parse_dates=['TIMESTAMP'], usecols=['TIMESTAMP', 'TWEET'])

twt25=[]
for w in df_25['TWEET']:
    twt25.append(tknz.tokenize(w.lower()))
    #debugging output
    print(w)
    print(len(twt25))
```

The code works as intended unless I come across certain types of tweets, I confirmed this through couple of tests.

For that specific file it was hanging for a long period and couldn't figure out why. I added the `print()` function to find out where the issue lies. Last time I ran it before manually interrupting the script was 30+minutes., so I decided to remove it with Sublime Text and reran it.

The tweet being: `@bunicole http://t.co/LZbFWsdMnl\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ITS YOU!` I'm assuming it's because there's 57 `!`

After removal it stopped again on `http://t.co/8K2bEJe9Hn\n???????????????????????? http://t.co/PhylB6ufxw`. However, that one having 24 `?` was for a shorter period of time ~10s. 

Is it possible to skip those types of lines without having to manually delete them?

**Comment by kmike** [comment]
I think we should try fixing the pathological regex; it looks like a security issue.

**Comment by fievelk** [comment]
I created a csv file with several tweets, adding your entry at the end (I added an ID column just for test):

> 624492026386624513,@bunicole http://t.co/LZbFWsdMnl\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ITS YOU!

Then I parsed it using pandas (following your code):

```
import pandas as pd
from nltk.tokenize import TweetTokenizer

tknz = TweetTokenizer()

df_25 = pd.read_csv('test_file.csv', header=None,\
                     names=['TWEET_ID', 'TWEET'], \
                     low_memory=False, \
                     usecols=['TWEET_ID', 'TWEET'])

twt25=[]
for w in df_25['TWEET']:
    twt25.append(tknz.tokenize(w.lower()))
    #debugging output
    print(w)
    print(len(twt25))
```

I found out that the entry is sligthly different after pandas parsing:

```
>>> df_25['TWEET'][5001]
'@bunicole http://t.co/LZbFWsdMnl\\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ITS YOU!'
```

You can see that the `\n` has been modified, and it is now escaped as `\\n` (see [here](https://groups.google.com/forum/#!topic/pydata/-kCo7OYAJaE) for another example). I think that this is because pandas uses `\n` to create new rows (but I did not use pandas so much, so I might be wrong). It seems that this is what causes the regexp to take so much time. In fact:

```
>>> from nltk.tokenize.casual import *
>>> tweet_1 = "@bunicole http://t.co/LZbFWsdMnl\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ITS YOU!"
>>> tweet_2 = "@bunicole http://t.co/LZbFWsdMnl\\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ITS YOU!"
>>> tknz.tokenize(tweet_1)
['@bunicole', 'http://t.co/LZbFWsdMnl', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', '!', 'ITS', 'YOU', '!']
>>> tknz.tokenize(tweet_2)
Takes a lot of time.
```

The regexp that gets stuck is `WORD_RE` in [`tokenize/casual.py`](https://github.com/nltk/nltk/blob/07bcb7ed51260f5da07be841aebf23235b6af96e/nltk/tokenize/casual.py).
