### ISSUE TITLE
Trie implementation

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1166]
Consolidate `tokenize.mwe.MWETokenizer.add_mwe` and `sem.logic.StringTrie` into `util.Trie`.

**Comment by mrecachinas** [comment]
I'm currently working on ensuring the `util.Trie` I've adapted from `sem.logic.StringTrie` maintains compatability with both `sem.logic.LogicParser.process` and `tokenize.mwe.MWETokenizer.add_mwe`.

**Comment by stevenbird** [comment]
+1

**Comment by stevenbird** [comment]
@mrecachinas – our [CI Server](https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py34-jenkins,jdk=jdk8latestOnlineInstall/lastCompletedBuild/testReport/) reports test failures that involve the new Trie object:

```
AttributeError: 'Trie' object has no attribute 'iteritems'
```

Would you be able to track down the problem and submit a new PR please?

**Comment by mrecachinas** [comment]
Very odd. I'll check it out.

**Comment by mrecachinas** [comment]
@stevenbird -- In Python 3, `dict.iteritems` was removed because `dict.items` has optimized what `iteritems` had done and now returns a `memoryview` (an iterator that does much more). 

There are a few different ways to fix this that will ensure compatibility between 2 and 3:
- Add an `iteritems` method to `Trie` that will simply `return self.items()`.
  - Downside: Performance hit in Python2 because we're no longer using an iterator; we're now building a full list of tuples unpacked from the `dict` or `defaultdict` (base class of `Trie`).
  - Upside: Full compatibility between 2 and 3
- Change the Python3 unit test to call `items()`
  - Downside: Disconnect in the API?
  - Upside: `items` is in both 2 and 3, so the tests remain consistent.

What are your thoughts?

**Comment by erip** [comment]
Any status on this? @stevenbird

**Comment by iliakur** [comment]
This is coming a little bit out of left field, but would it be worth considering using @kmike's [DaTrie Implementation](https://github.com/kmike/datrie) for its speed? Or is it a problem to have such an external dependency?

**Comment by mrecachinas** [comment]
+1 @Copper-Head This is a good question. I'd be curious about it too. cc @stevenbird @kmike

**Comment by alvations** [comment]
+1 for @kmike's Trie dependency.

**Comment by stevenbird** [comment]
Sorry for the delay. I've adopted the second suggestion of @mrecachinas above, given that `iter*` methods from Python 2 are the default behaviour in Python 3.

I think if someone wants the added efficiency that @kmike's implementation offers, surely they can use it directly? I don't think it needs to be bundled in NLTK.

**Comment by kmike** [comment]
FTR: datrie has pathological cases: building of a trie can dramatically slow down (see https://github.com/kmike/datrie/issues/12#issuecomment-28498683). For a trie which can be updated efficiently https://github.com/kmike/hat-trie is better. For static data structures (the ones you build once) https://github.com/kmike/DAWG or https://github.com/kmike/marisa-trie provide much better memory usage.

**Comment by iliakur** [comment]
@kmike thanks a lot for that. There was talk of using Tries when refactoring the NgramModel, this will help us make an informed decision about it :)
