### ISSUE TITLE
Word attribute in DependencyGraph TOP node

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1182]
As reported in https://groups.google.com/forum/#!topic/nltk-users/C7e-jRdeVtM, there seems to be a bug caused by the fact that the added TOP node has no value for its `word` attribute:

```
import nltk
from nltk.parse import DependencyGraph
from collections import defaultdict

def from_sentence(sent):
    tokens = nltk.word_tokenize(sent)
    tagged = nltk.pos_tag(tokens)

    dg = DependencyGraph()
    for (index, (word, tag)) in enumerate(tagged):
        dg.nodes[index + 1] = {
            'word': word,
            'lemma': '_',
            'ctag': tag,
            'tag': tag,
            'feats': '_',
            'rel': '_',
            'deps': defaultdict(),
            'head': '_',
            'address': index + 1,
        }
    dg.connect_graph()
    return dg

dg = from_sentence("Natural Language Processing is really fun.")
tree = dg.tree()
tree.pprint()

Error, 
Traceback (most recent call last):
...........
 tree = dg.tree() 
  File "C:\Python27\lib\site-packages\nltk\parse\dependencygraph.py", line 340, in tree 
    word = node['word'] 
TypeError: 'NoneType' object has no attribute '__getitem__' 
```

The same error happens with:

```
for val in dg.triples():
    print val
```

**Comment by stevenbird** [comment]
@dimazest – do you have any suggestion for how to resolve this please?

**Comment by dimazest** [comment]
I need to have a look, but the idea of creating an empty graph, appending nodes to it and then connecting the nodes seems strange to me. The reason is that this code knows too much about DG internal implementation, for example the fact that we are using dictionaries to store node information.

**Comment by dimazest** [comment]
I think the best solution for this is to stop assuming that there is only one root node.

A radical solution is to remove the .root attribute from DpendencyGraph, this will break some code and might lead to surprises because the attribute might be set outside of the dependencygraph module.

Another solution is to call the TOP node the root node. This will change the behavior of tree printing for example.

The most compatible solution is to introduce the .roots property that return a list of TOP dependents and also make .root a property that returns the only root, if there are several of them, an exception is thrown. In this way, the code that assumes that there is only one root will work when there is indeed only one root. However, it will not be possible to set the .root (but it probably should not be possible to do so). 

Maybe we can deprecate it for a couple of releases and remove eventually.
