### ISSUE TITLE
Wordnet _morphy handling of exception words

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1196]
Wordnet lemmatizer that depends on `nltk.corpus.wordnet._morphy()` doesn't handle exception words as expected, 

``` python
>>> from nltk.stem import WordNetLemmatizer
>>> wnl = WordNetLemmatizer()
>>> wnl.lemmatize('saw', pos='v')
'saw'
>>> wnl.lemmatize('teeth', pos='n')
'teeth'
>>> wnl.lemmatize('geese', pos='n')
u'goose'
```

Even though these are irregular words are already in the Princeton exception list. It seems like `_moprhy()` was adding more options rather than immediately return the lemma of the exception words, e.g.:

``` python
>>> from nltk.corpus import wordnet as wn

>>> exceptions = wn._exception_map['n']
>>> exceptions['teeth']
[u'tooth']
>>> exceptions = wn._exception_map['v']
>>> exceptions['saw']
[u'see']

>>> wn._morphy('saw', pos='v')
['saw', u'see']
>>> wn._morphy('teeth', pos='n')
['teeth', u'tooth']
```

Possibly adding this before the rest of code in the `_morphy()` function can resolve the problems, but I'm not sure whether it will break other word instances or other part of the wordnet code:

``` python
def _morphy(word, pos):
    exceptions = wordnet._exception_map[pos]
    if word in exceptions:
        return exceptions[word]
    # Else, continue the rest of the _morphy code.
```

Full diagnostic of the bug can be found [here](http://stackoverflow.com/questions/33594721/why-nltk-lemmatization-has-wrong-output-even-if-verb-exc-has-added-right-value/33600258#33600258)

**Comment by nschneid** [comment]
I believe this is not technically a bug because WordNet has [saw](http://www.golovchenko.org/cgi-bin/wnsearch?q=saw) and [teeth](http://www.golovchenko.org/cgi-bin/wnsearch?q=teeth) as lemmas. "Saw" is certainly ambiguous. The problem is that WordNet's POS inventory doesn't distinguish inflectional categories like tense and number.

It might be worth having a `lemmatize()` function that wraps `_morphy()` and handles special cases when a finer-grained POS tag is available. At one point I wrote the following rules for irregular past tenses and plurals, using the Penn Treebank tagset (just added "teeth" as well):

``` python
if p in {'VBD','VBN'}:
  if w=='found': return 'find'
  elif w=='ground': return 'grind'
  elif w=='rent': return 'rend'
  elif w=='smelt': return 'smell'
  elif w=='wound': return 'wind'
  elif p=='VBD':
    if w=='fell': return 'fall'
    elif w=='lay': return 'lie'
    elif w=='saw': return 'see'
elif p[0]=='V' and w=='stove': return 'stove'  # WordNet has only the past/ppt form of 'stave', but apparently 'stove' can be a verb
# 'ridden' is a past participle of 'rid' and the past participle of 'ride'. The POS is not enough to disambiguate, but 'ride' (which WordNet gives) is probably more common.
elif p=='NNS' and w=='people': return 'person'
elif p=='NNS' and w=='teeth': return 'tooth'
```

**Comment by alvations** [comment]
@nschneid thanks for the wordnet links to the lemmas. That makes more sense why the `_morphy()` would generate beyond the exception list. Look at [teeth in other languages](http://compling.hss.ntu.edu.sg/omw/cgi-bin/wn-gridx.cgi?usrname=&gridmode=grid&synset=05282433-n&lang=eng&lang2=eng) makes more sense when it refers to dentures.

**Comment by mr-solebrity** [comment]
I actually noticed the similar behaviour here with the word `men`.  `men` is in the exceptions list and should be `man` after lemmatizing.  I do also see `men` as a lemma by itself, but the exception should take precedence. No?  I think the main cause of this is acutally the `min(lemmas, key=len)` compounded by the fact that the original word is prepended to the list of forms before `filter_forms` instead of appended.

**Comment by nschneid** [comment]
@mr-solebrity: Yes, `men` is similar to `people`: there is [an entry](http://www.golovchenko.org/cgi-bin/wnsearch?q=men) where it's listed in the plural, so it is never lemmatized to the singular. 

It turns out that many regular (as well as a few irregular) plurals are listed as WordNet lemmas, and thus left alone during lemmatization. Working on lists and an improved stemmer at https://gist.github.com/nschneid/d49de87813bd6499ff7c2d861eba196c
