### ISSUE TITLE
Multext reader returns map object

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1203]
The `tagged_sents` and `tagged_words` methods should return a sequence type not a map object.

```
>>> nltk.corpus.brown.tagged_words()
>>> [('The', 'AT'), ('Fulton', 'NP-TL'), ...]
>>> nltk.corpus.multext_east.tagged_words("oana-en.xml", "universal")
 <map object at 0x10b34dfd0>
>>> 
```

**Comment by stevenbird** [comment]
@stieglma: would you please look into this?

**Comment by stieglma** [comment]
This seems to be a problem with Python 3. It can easily be fixed by wrapping the return value of the mentioned functions in `list(...)`. This is also what I would do. But I have a question on this: When executing the tagged_words() function on the brown corpus it only shows the first two elements and not the whole list. With the multext-east reader it will always print the whole list. I couldn't figure out how you achieve this. Is it necessary that it works like that, or is it ok if the whole list is printed?

**Comment by nschneid** [comment]
@stieglma, that's done with the lazy sequence API in http://www.nltk.org/api/nltk.html#module-nltk.util. I think lazy loading should be preferred except for very small corpora.

**Comment by stieglma** [comment]
I created the pull request quite a while ago, did you just forget to merge it, or is something wrong with it?

**Comment by stevenbird** [comment]
Thanks @stieglma! I'm getting to it...

**Comment by stevenbird** [comment]
Thanks @stieglma
