### ISSUE TITLE
Zipfile corpus reader breaks in Python 3.5

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1204]
The zipfile corpus reader breaks in Python 3.5.

```
>>> from nltk.corpus import propbank
>>> propbank.instances()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk-3.0.5-py3.5.egg/nltk/util.py", line 716, in __repr__
    for elt in self:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk-3.0.5-py3.5.egg/nltk/corpus/reader/util.py", line 282, in iterate_from
    self._open()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk-3.0.5-py3.5.egg/nltk/corpus/reader/util.py", line 209, in _open
    self._stream = self._fileid.open(self._encoding)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk-3.0.5-py3.5.egg/nltk/data.py", line 505, in open
    data = self._zipfile.read(self._entry)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk-3.0.5-py3.5.egg/nltk/data.py", line 982, in read
    self.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/zipfile.py", line 1607, in close
    self._fpclose(fp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/zipfile.py", line 1711, in _fpclose
    assert self._fileRefCnt > 0
AssertionError
```

**Comment by dlukes** [comment]
Any idea why? And is anyone currently investigating? Or should I try to fix it myself (I was planning to use the zipfile corpus reader in a project) and submit a pull request if I manage to get it working again?

Thanks so much for NLTK by the way! :)

**Comment by alvations** [comment]
The same thing was reported in #1256. @JiHongyu suggested a fix with a +1. But I'm not sure what exactly is wrong. So sorry that I can't fix this for now because I'm busy with something else.

**Comment by dlukes** [comment]
Thanks for the reference!

> So sorry that I can't fix this for now because I'm busy with something else.

I understand and please don't apologize :) I'll try to have a look at it myself if I have time.

**Comment by dlukes** [comment]
OK, so it looks as though a `_fileRefCnt` private attribute was added to `zipfile.ZipFile` (something to do with a bug in reopening the underlying file, see commit https://github.com/python/cpython/commit/d4d1c956f96fda459bbc08b177831884a16bea67, I only had a cursory look at the related issue). It gets incremented on each call to `self.open()` and decremented on each `self.close()` (via `self._fpclose()`).

The trouble is that `nltk.data.OpenOnDemandZipFile` overrides `read()` and doesn't call `self.open()` in it but the builtin `open()`. `_fileRefCnt` thus doesn't get incremented, and once `self.close()` is called, the `assert self._fileRefCnt > 0` fails (see traceback in OP).

Here's an ugly hack that makes things work:

``` diff
diff --git a/nltk/data.py b/nltk/data.py
index ffef466..b070fac 100644
--- a/nltk/data.py
+++ b/nltk/data.py
@@ -978,6 +978,10 @@ class OpenOnDemandZipFile(zipfile.ZipFile):
     def read(self, name):
         assert self.fp is None
         self.fp = open(self.filename, 'rb')
+        if self._fileRefCnt:
+            self._fileRefCnt += 1
+        else:
+            self._fileRefCnt = 1
         value = zipfile.ZipFile.read(self, name)
         self.close()
         return value
```

Ugly because we're tampering with a private attribute of the superclass in a subclass.

Alternative ideas:
- make `nltk.data.OpenOnDemandZipfile.read()` use `zipfile.ZipFile.open()` instead of builtin `open()` (that will set the private attribute correctly, but I've no idea whether it does the right thing&trade; in other respects)
- override `zipfile.ZipFile.close()` with a custom method -- perhaps it would be possible to essentially copy the superclass's method with just a small change which would skip some of the checks which are performed, including the one on `_fileRefCnt`? Something along the lines of (highlighting the change compared to `zipfile.ZipFile.close()`):

``` diff
diff --git a/nltk/data.py b/nltk/data.py
index fc03cba..97b38f5 100644
--- a/nltk/data.py
+++ b/nltk/data.py
@@ -984,41 +984,41 @@ class OpenOnDemandZipFile(zipfile.ZipFile):
     def close(self):
         """Close the file, and for mode 'w', 'x' and 'a' write the ending
         records."""
         if self.fp is None:
             return

         try:
             if self.mode in ('w', 'x', 'a') and self._didModify: # write ending records
                 with self._lock:
                     if self._seekable:
                         self.fp.seek(self.start_dir)
                     self._write_end_record()
         finally:
             fp = self.fp
             self.fp = None
-            self._fpclose(fp)
+            fp.close()

     def write(self, *args, **kwargs):
         """:raise NotImplementedError: OpenOnDemandZipfile is read-only"""
```

The workarounds shown in the diffs work, but I've no idea which (if any) fits better with existing NLTK dev practices :)

**Comment by stevenbird** [comment]
Resolved by #1301

**Comment by ghost** [comment]
Hi guys, so is it fixed for good ?
Does it mean that when the next version of python comes out then we won't get this : https://github.com/nltk/nltk/issues/1338 ? 
Thank you

**Comment by alvations** [comment]
@alvinsight I'm quite sure the zipfile issue with Python 3.5 is fixed. The issue with #1338 is when users downloads a corrupted file when the internet breaks, and has little to do with this zipfile issue =)

@stevenbird possibly a different mirror to the `panlex_lite` zip file that can have faster download time and handles higher traffic might solve the woes. Maybe we should think of setting up a dropbox for `nltk` or https://git-lfs.github.com/.
