### ISSUE TITLE
NLTK sentiment analysis returns only positive classifications

### ISSUE THREAD

**Issue by josti92** [nltk/nltk#1227]
# Python script

import nltk
import csv

FBdata = None
with open('Classified.csv' ,'rb') as f: 
    reader = csv.reader(f)
    FBdata = map(tuple, reader)

with open('Classified2.csv' ,'rb') as f: 
    reader = csv.reader(f)
    Negative = map(tuple, reader)

import random
random.shuffle(FBdata)
Negativedata = Negative

newFBdata = []  #sorting data
for row in FBdata:
    statement = row[0]
    sentiment = row[1]
    words_filtered = [e.lower() for e in statement.split() if len(e) >= 3] 
    newFBdata.append((words_filtered, sentiment))

posts = newFBdata[:1000]
# Then we need to get the unique word list as the features for classification.
# get the word lists of posts

def get_words_in_posts(posts):
    all_words = []
    for (words, sentiment) in posts:
        all_words.extend(words)
    return all_words
# get the unique word from the word list

def get_word_features(wordlist):
    wordlist = nltk.FreqDist(wordlist)
    word_features = wordlist.keys()
    return word_features

word_features = get_word_features(get_words_in_posts(posts))
word_features
# To create a classifier, we need to decide what features are relevant. To do that, we first need a feature extractor.

def extract_features(document):
    document_words = set(document)
    features = {}
    if posts in word_features:
      features['contains(%s)' % word] = True
    return features
# Then, we can build up the training set and create the classifier:

training_set = nltk.classify.util.apply_features(extract_features, posts)

classifier = nltk.NaiveBayesClassifier.train(training_set)
# You may want to know how to define the ‘train’ method in NLTK here:

def train(labeled_featuresets, estimator=nltk.probability.ELEProbDist):
    # Create the P(label) distribution
    label_probdist = estimator(label_freqdist)
    # Create the P(fval|label, fname) distribution
    feature_probdist = {}
    return NaiveBayesClassifier(label_probdist, feature_probdist)
# Now, we will classify the negativeposts and calculate the recall accuracy.

def classify_post(post):
    return \
        classifier.classify(extract_features(post)) # nltk.word_tokenize(tweet)

total = accuracy = float(len(Negativedata))

for post in Negativedata[:100]:
    if classify_post(post[0]) != post[1]:
        accuracy -= 1

print('Total accuracy: %f%% (%d/20).' % (accuracy / total \* 100, accuracy))
# test to see post sentiment, everyone gets positive value :(

print classifier.classify(extract_features(Negativedata[1]))

for x in range(0,100):
    print classifier.classify(extract_features(Negativedata[x]))

classifier.show_most_informative_features()

**Comment by ewan-klein** [comment]
@fievelk Would you have time to have a look at this?

**Comment by fievelk** [comment]
Sure, I will check it

**Comment by fievelk** [comment]
@josti92 I think I found the online tutorial you are using for your task; since I do not have your data, I cannot replicate your results. However, it seems that you only changed the datasets (**FBdata** and **Negative**), so the issue is probably there. You are supposed to train the classifier on both positive and negative labeled examples; testing on **Negativedata** instances is then supposed to give you a lot of _negative_ classifications.

In this case, I think that your problem is not related to a NLTK bug, and it is therefore more suitable to be reported on the [nltk-users forum](https://groups.google.com/forum/#!forum/nltk-users).

I think you would also find it useful to check the first part of the [NLTK Sentiment Analysis How To](http://www.nltk.org/howto/sentiment.html). Finally, we recently added several utility methods for sentiment analysis and preprocessing tasks in the `sentiment/sentiment_analyzer.py` and `sentiment/util.py` modules, so you can use them if you need more features for your classifier.

**Comment by josti92** [comment]
Thank you for your reply! I figured it out, I had to redo the cleaning of my data.

Best regards,
Øystein Løken

**Comment by ewan-klein** [comment]
Thanks, @fievelk.
