### ISSUE TITLE
Automatically adding classpath for Stanford Tools 

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1237]
The [new Stanford NER tool](http://nlp.stanford.edu/software/stanford-ner-2015-12-09.zip) and [parser](http://nlp.stanford.edu/software/lex-parser.shtml) requires more `.jar` files to be added to the classpath. Possibly, it's easier to modify the `nltk.tag.stanford`  to do something like what 
- `nltk.parse.malt` is doing with the dependencies check using `find_jar_within_paths`  (e.g. https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py#L66) https://github.com/nltk/nltk/blob/develop/nltk/internals.py#L722. 

More details on http://stackoverflow.com/questions/34361725/nltk-stanfordnertagger-noclassdeffounderror-org-slf4j-loggerfactory-in-windo/

**Comment by alvations** [comment]
Given the new corenlp v3.6, maybe that's the way to go wrap around the JSON output: https://github.com/smilli/py-corenlp and something like https://github.com/alvations/nltk/blob/stanfordnlp/nltk/parse/dependencygraph.py#L636

That way we don't have to play catch up with Stanford NLP tools all the time and say that we only support tagger/parsers/tools versions from corenlp

**Comment by alvations** [comment]
@stanfordnlp Any thoughts on whether third-party wrappers to Stanford tools should wrap the individual tools or the Stanford CoreNLP? If we're wrapping Stanford CoreNLP, what's an easy way to specify language or a specific model for a specific task to the server query?

**Comment by longdt219** [comment]
Hi @stevenbird, 
All the bugs related to Stanford packages shown in the CI server is due to the new logging requirements such that <b> slf4j-api.jar</b> and <b> slf4j-simple.jar </b> are needed. We can do some hackings as suggested by @alvations  <a href = 'https://gist.github.com/alvations/e1df0ba227e542955a8a'> here </a> to add these additional .jar files to the classpath through the `find_jar_within_paths` function. What do you think ?

**Comment by dimazest** [comment]
here is what I did to make it working https://github.com/nltk/nltk/pull/1249/files#diff-3ddcbc41d8654bc0748b8afb087c55aeR40

**Comment by longdt219** [comment]
Vote for @alvations'solution since we don't have to manually specify the jar file names.

**Comment by rapaliwal** [comment]
Hi,
I am also facing the same issue. I believe its not fixed yet? Please comment in case it is or there is any way to get it working. Thanks

**Comment by alvations** [comment]
@rapaliwal the code is merged into the `develop` branch, if you want to use the bleeding edge version of `NLTK`, you can try`pip install -U https://github.com/nltk/nltk/archive/develop.zip` (CAUTION: this will subject your python environment to developmental code; it may break something!). 

Otherwise, it should be patched in the current/next stable release of NLTK and `pip install -U nltk` should fix the problem.

If you want to resolve the problem without changing the NLTK version or code in NLTK, try https://gist.github.com/alvations/e1df0ba227e542955a8a

**Comment by rapaliwal** [comment]
Thanks @alvations for quick reply. I am trying to use nltk with stanford parser (and maybe dependency parser later). I will give the new version of nltk a go. Will let you know what happens. Thanks

**Comment by dterg** [comment]
With NLTK 3.2, Stanford POS tagger works fine but parser and dependency parser suffer from the same issue. Nonetheless, works with the hack.

**Comment by sarancruzer** [comment]
How to add new words to PERSON node

**Comment by francescomambrini** [comment]
Just one quick follow-up!
I was trying to port some code with calls to `StanfordNER` that I had written on a machine with NLTK 3.2.1 to a machine where I have NLTK 3.2.5. I am still using the hold distribution  `stanford-ner-2015-12-09` on both machines and `$CLASSPATH` is configured correctly on both.
Everything was working well on NLTK 3.2.1, but I met this very problem on NLTK 3.2.5. The workaround by @alvations posted [here](https://gist.github.com/alvations/e1df0ba227e542955a8a) solved everything on NLTK 3.2.5 but apparently I did not need it on 3.2.1.
Is it normal? Is it because `StanfordNER` is now deprecated on 3.2.5?
