### ISSUE TITLE
Turkish language extension

### ISSUE THREAD

**Issue by DuyguA** [nltk/nltk#1248]
Hello all,
I'm a Turkish NLP developer and I'd like to add Turkish language libraries including a morphological analyzer and a parser. Would anyone be interested?

**Comment by periscube** [comment]
Hi Duygu

It would be fantastic if you do that. Could be very useful for sentiment analysis on Turkish texts / forums / twitter data..

**Comment by maeares** [comment]
is there any update about this ?

**Comment by stevenbird** [comment]
We welcome pull requests to add support for specific languages. Please ensure you follow our [guidelines](https://github.com/nltk/nltk/wiki/Developers-Guide).

**Comment by DuyguA** [comment]
Hi guys,

Unfortunately my company  decided to do another language and postpone Turkish. :( However, I'll prepare some FSTs anyway for the other language (German). I'll speak to my boss and make the pull request if applicable.

**Comment by MrPeker** [comment]
:(

**Comment by DuyguA** [comment]
I moved to SpaCy, for whoever is interested. Turkish work will continue from 

https://github.com/explosion/spaCy/tree/master/spacy/lang/tr

Also you can check out my Medium page, I post about Turkish processing when I have time.

**Comment by arf1372** [comment]
@stevenbird @alvations:
I could see it's about a year ago that this issue is still open. As I understood, @DuyguA stopped working on this and moved to SpaCy. So, would you mind close this? or you are working on it? (or seeking contributors to resolve this one?)

I also recommend this one goes to [nltk/nltk_data](/nltk/nltk_data) as the pipeline may be common for other languages and the important part is just data (corpus, dictionaries, wordnets, etc)

**Comment by DuyguA** [comment]
Yes, I moved to spaCy but if you still want I can make an implementation for NLTK too under nltk_data

**Comment by Higgs32584** [comment]
any update on this ?

**Comment by DuyguA** [comment]
> any update on this ?
> 

Moved to spaCy completely, can send package and tutorial links if you want!
