### ISSUE TITLE
use source-code to install fail

### ISSUE THREAD

**Issue by CodingLionDargon** [nltk/nltk#1278]
git clone code;
sudo python setup.py install;
a problem:
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by alvations** [comment]
You would need `setuptools`:

```
# For linux/mac
$ pip install -U pip setuptools
# For windows
$ python -m pip install -U pip setuptools
```

(see http://python-packaging-user-guide.readthedocs.org/en/latest/installing/)

If you do not have `pip`, see https://pip.pypa.io/en/stable/installing/

---

To install the bleeding edge code, I suggest using `pip` instead of using `setup.py`:

```
pip install git+https://github.com/nltk/nltk.git
```

But this will make your currently environment use the bleeding edge code which might contain unresolved bugs introduced by new features. Using `conda` and `pip` with the stable versions is more appropriate, see http://conda.pydata.org/docs/install/quick.html and http://www.nltk.org/install.html

Otherwise, if you're interested in contributing, it's easier to clone the repo and not install but run test within the directory of the repo, which `python` should be smart enough to use the local directory version rather than the globally installed one in your environment.

**Comment by CodingLionDargon** [comment]
thank you!
