### ISSUE TITLE
ParentedTree breaks deepcopy

### ISSUE THREAD

**Issue by josepvalls** [nltk/nltk#1324]
Can deepcopy Tree but not ParentedTree, not sure if may be related to this: https://github.com/nltk/nltk/issues/130

> > > from nltk.tree import Tree,ParentedTree
> > > t1 = Tree.fromstring("(TOP (S (NP (NNP Bell,)) (NP (NP (DT a) (NN company)) (SBAR (WHNP (WDT which)) (S (VP (VBZ is) (VP (VBN based) (PP (IN in) (NP (NNP LA,)))))))) (VP (VBZ makes) (CC and) (VBZ distributes) (NP (NN computer))) (. products.)))")
> > > t2 = copy.deepcopy(t1)
> > > t3 = ParentedTree.fromstring("(TOP (S (NP (NNP Bell,)) (NP (NP (DT a) (NN company)) (SBAR (WHNP (WDT which)) (S (VP (VBZ is) (VP (VBN based) (PP (IN in) (NP (NNP LA,)))))))) (VP (VBZ makes) (CC and) (VBZ distributes) (NP (NN computer))) (. products.)))")
> > > import copy
> > > t4 = copy.deepcopy(t3)
> > > Traceback (most recent call last):
> > >   File "<input>", line 1, in <module>
> > >   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
> > >     y = _reconstruct(x, rv, 1, memo)
> > >   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 351, in _reconstruct
> > >     item = deepcopy(item, memo)
> > >   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
> > >     y = _reconstruct(x, rv, 1, memo)
> > >   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 351, in _reconstruct
> > >     item = deepcopy(item, memo)
> > >   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
> > >     y = _reconstruct(x, rv, 1, memo)
> > >   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 352, in _reconstruct
> > >     y.append(item)
> > >   File "/usr/local/lib/python2.7/site-packages/nltk/tree.py", line 1061, in append
> > >     self._setparent(child, len(self))
> > >   File "/usr/local/lib/python2.7/site-packages/nltk/tree.py", line 1221, in _setparent
> > >     raise ValueError('Can not insert a subtree that already '
> > > ValueError: Can not insert a subtree that already has a parent.

**Comment by alvations** [comment]
I'm not sure what's the use of copying the `Tree` object but it seems like `ParentedTree` can't be deeply copied.

```python
>>> import copy
>>> from nltk.tree import Tree,ParentedTree

>>> t1 = Tree.fromstring("(TOP (S (NP (NNP Bell,)) (NP (NP (DT a) (NN company)) (SBAR (WHNP (WDT which)) (S (VP (VBZ is) (VP (VBN based) (PP (IN in) (NP (NNP LA,)))))))) (VP (VBZ makes) (CC and) (VBZ distributes) (NP (NN computer))) (. products.)))")

>>> t2 = copy.deepcopy(t1)

>>> t3 = ParentedTree.fromstring("(TOP (S (NP (NNP Bell,)) (NP (NP (DT a) (NN company)) (SBAR (WHNP (WDT which)) (S (VP (VBZ is) (VP (VBN based) (PP (IN in) (NP (NNP LA,)))))))) (VP (VBZ makes) (CC and) (VBZ distributes) (NP (NN computer))) (. products.)))")

>>> t4 = copy.deepcopy(t3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 351, in _reconstruct
    item = deepcopy(item, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 351, in _reconstruct
    item = deepcopy(item, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 352, in _reconstruct
    y.append(item)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tree.py", line 1064, in append
    self._setparent(child, len(self))
  File "/usr/local/lib/python2.7/dist-packages/nltk/tree.py", line 1224, in _setparent
    raise ValueError('Can not insert a subtree that already '
ValueError: Can not insert a subtree that already has a parent.
```

And having NLTK object breaking native Python `copy` isn't a good thing...

We should look into this, most probably the error is coming from how `ParentedTree` are made up of `ParentedTree`:

```
>>> t3
ParentedTree('TOP', [ParentedTree('S', [ParentedTree('NP', [ParentedTree('NNP', ['Bell,'])]), ParentedTree('NP', [ParentedTree('NP', [ParentedTree('DT', ['a']), ParentedTree('NN', ['company'])]), ParentedTree('SBAR', [ParentedTree('WHNP', [ParentedTree('WDT', ['which'])]), ParentedTree('S', [ParentedTree('VP', [ParentedTree('VBZ', ['is']), ParentedTree('VP', [ParentedTree('VBN', ['based']), ParentedTree('PP', [ParentedTree('IN', ['in']), ParentedTree('NP', [ParentedTree('NNP', ['LA,'])])])])])])])]), ParentedTree('VP', [ParentedTree('VBZ', ['makes']), ParentedTree('CC', ['and']), ParentedTree('VBZ', ['distributes']), ParentedTree('NP', [ParentedTree('NN', ['computer'])])]), ParentedTree('.', ['products.'])])])
```

**Comment by irisxzhou** [comment]
@ssantichaivekin and I have found a fix to this, which also extends to the `ImmutableTree` object. 

Native Python `copy` first looks for `__copy__` and `__deepcopy__` (which don't exist in `Tree`), then if it doesn't find it looks for `__reduce_ex__` and `__reduce__` instead. Since all trees (`Tree`, `ParentedTree`, `ImmutableTree`) derive from the list base class, the trees inherit `__reduce_ex__` from it. However, this doesn't necessarily apply to produce the intended behavior. For example, here for list-like objects we will try to call `append` in `deepcopy`, which will break both `ParentedTree` and `ImmutableTree` objects and raise an exception. 

The easiest way to fix this is to define `__copy__` and `__deepcopy__` methods that call NLTK tree's `copy`. NLTK tree objects have their own `copy`, with an option to make it a deep copy, so no other code has to be modified. We are slightly concerned that this fix may not support `pickle`, but the one or two examples we checked seemed to work, since `pickle` seems to use `append` and/or `extend` and both of those are implemented for trees. 

![image](https://user-images.githubusercontent.com/31681549/56871099-eef8b680-69cd-11e9-9f6e-8601897354db.png)

We will finish testing and submit a pull request soon!
