### ISSUE TITLE
dispersion_plot incorrectly imported in nltk/text.py

### ISSUE THREAD

**Issue by Mithrillion** [nltk/nltk#1339]
The issue is around line 444
`from nltk.draw import dispersion_plot`
The function is actually defined in nltk/draw/dispersion.py
The above line causes a failure to import name error in a NLTK book chapter one example
The correct import should be:
`from nltk.draw.dispersion import dispersion_plot`

**Comment by dennisobrien** [comment]
I ran across this problem as well with Python 2.7.11 and Python 3.5.1.  The problem seems to be in `nltk.draw.__init__.py` which is attempting to `import tkinter` first and only if this is successful does it bring `nltk.draw.dispersion.dispersion_plot` into the `nltk.draw` namespace.
https://github.com/nltk/nltk/blob/develop/nltk/draw/__init__.py#L17

`dispersion_plot` does not depend on `tkinter` so it can be moved out of this `else` block.
