### ISSUE TITLE
Return Type of WordNetLemmatizer

### ISSUE THREAD

**Issue by melvyniandrag** [nltk/nltk#1344]
```
>>>words = 'I love dogs and cats and all animals'.split() # type is ascii
>>>wnl = WordNetLemmatizer()
>>>lemmas = [wnl.lemmatize(w) for w in words]
>>>lemmas
['I', 'love', u'dog', 'and', u'cat', 'and', 'all', 'other', u'animal'] 
```

I don't think we should have mixed types for a return value. This is a minor error that could be fixed. I've had some confusion on a number of occasions with NLTK due to 'str' vs 'unicode'. I think that it might be best if all NLTK modules return utf-8 for type safety/to avoid headaches.

What does everyone think?

**Comment by alvations** [comment]
I think that `str` vs `utf8` is fine since `WordNetLemmatizer` is only English-specific. And hopefully once everyone moves to Python3, this difference would disappear.

When checking for value equivalence, `str` vs `utf8` shouldn't have much problem in English:

``` python
>>> from nltk.stem import WordNetLemmatizer
>>> wnl = WordNetLemmatizer()
>>> sent = u'I love dogs and cats and all animals'.split()
>>> gold = u'I love dog and cat and all animal'.split()
>>> [wnl.lemmatize(w) for w in sent] == gold
True
>>> sent = 'I love dogs and cats and all animals'.split()
>>> [wnl.lemmatize(w) for w in sent] == gold
True
```

But it does become an issue if later on in the pipeline there're individual type checks (but i think it's uncommon):

``` python
>>> all(type(l) == type(g) for l,g in zip([wnl.lemmatize(w) for w in sent], gold))
False
>>> all(l == g for l,g in zip([wnl.lemmatize(w) for w in sent], gold))True
```

Possibly, users would need to use something like this in Python2:

``` python
>>> [wnl.lemmatize(w) for w in sent]
['I', 'love', u'dog', 'and', u'cat', 'and', 'all', u'animal']
>>> u" ".join([wnl.lemmatize(w) for w in sent])
u'I love dog and cat and all animal'
>>> u" ".join([wnl.lemmatize(w) for w in sent]).split()
[u'I', u'love', u'dog', u'and', u'cat', u'and', u'all', u'animal']
```

And in `python2`, if there's some non-ascii string being read as `str`, an error like this should appear before lemmatization (it usually happens when reading a file without using `io.open(filename, 'r', encoding='utf8'`):

``` python
>>> from nltk.stem import WordNetLemmatizer
>>> wnl = WordNetLemmatizer()
>>> wnl.lemmatize(u'Café')
u'Caf\xe9'
>>> wnl.lemmatize('Café')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nltk/stem/wordnet.py", line 40, in lemmatize
    lemmas = wordnet._morphy(word, pos)
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1712, in _morphy
    forms = apply_rules([form])
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1694, in apply_rules
    if form.endswith(old)]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

**Comment by stevenbird** [comment]
Thanks @melvyniandrag and @alvations. I think this is a minor issue and it's going away as people switch to Python 3, so not worth expending resources.
