### ISSUE TITLE
russian stopwords

### ISSUE THREAD

**Issue by Donald522** [nltk/nltk#1367]
A list of russian stopwords need to be expanded by following words:

badwords = [
    u'я', u'а', u'да', u'но', u'тебе', u'мне', u'ты', u'и', u'у', u'на', u'ща', u'ага', 
    u'так', u'там', u'какие', u'который', u'какая', u'туда', u'давай', u'короче', u'кажется', u'вообще',
    u'ну', u'не', u'чет', u'неа', u'свои', u'наше', u'хотя', u'такое', u'например', u'кароч', u'как-то',
    u'нам', u'хм', u'всем', u'нет', u'да', u'оно', u'своем', u'про', u'вы', u'м', u'тд',
    u'вся', u'кто-то', u'что-то', u'вам', u'это', u'эта', u'эти', u'этот', u'прям', u'либо', u'как', u'мы',
    u'просто', u'блин', u'очень', u'самые', u'твоем', u'ваша', u'кстати', u'вроде', u'типа', u'пока', u'ок'

]

**Comment by iliakur** [comment]
@Donald522 is this suggestion based on some literature or on frequency counts?

**Comment by Donald522** [comment]
@Copper-Head This suggestion is based on my experience of using the library during the mining data from russian social network Vkontakte. These words have very high frequence of use and have no sence.

**Comment by iliakur** [comment]
I see. The reason I ask is because the current stopwords corpus is clearly tied to a specific stemming approach (and paper):
**PORTER, M. F. 1980. "An Algorithm for Suffix Stripping." Program, 14(3), 130-37**

IMHO, it may be a bit risky to start amending this with data coming from people's individual experiences with very specific domains. It simply can lead to unpredictable behavior.

For example, you include the Dative _тебе_, but not the Instrumental _тобой_. From a linguist's point of view they both carry about as much meaning, it would be somewhat surprising to include one but not the other solely because it occurred more often in a particular text we were working with.

I honestly suspect that by the time we'd be done thinking this through properly we might as well publish a paper and use that as a reference for a pull request.

Sadly, I for one don't have the time for such an activity.

This is just my two cents though, let's see what other folks say.

**Comment by stevenbird** [comment]
@Donald522: I think @Copper-Head is right. We can only accept a replacement list that represents wide consensus.

**Comment by postrou** [comment]
@Copper-Head sorry for commenting such a dead issue, but it doesn't make sence to me. The words *этот*, *этого*, *этом*, *эту* are included in stop-words list, but, for example, the words *это*, *эта*, which are just another form of words, I mentioned earlier, are not. This actually suits the controversial example you mentioned in your comment.
