### ISSUE TITLE
Sentence splitting: Inconsistent end spans with trailing white space.

### ISSUE THREAD

**Issue by lfurrer** [nltk/nltk#1433]
I observed the following inconsistency in the PunktSentenceTokenizer, using NLTK 3.1 on Python 3.4:

```
>>> from nltk.tokenize import PunktSentenceTokenizer
>>> pst = PunktSentenceTokenizer()
>>> pst.span_tokenize('See Section 3.)  Or Section 2.)  ')  # Ex. 1
[(0, 15), (17, 31)]
>>> pst.span_tokenize('See Section 3).  Or Section 2).  ')  # Ex. 2
[(0, 15), (17, 33)]
>>> pst.span_tokenize('See Section 33.  Or Section 213  ')  # Ex. 3
[(0, 15), (17, 33)]
```

Apparently, the spans returned by the sentence splitter don't include trailing whitespace for sentences 1.._n_-1, but include them for sentence _n_ (the last sentence identified in the argument string, see the second and third example).
However, if the last sentence ends in a closing parenthesis, the spans don't include whitespace either (as in the first example).

Thus, there are two mutually exclusive strategies, each having pros and cons:
In examples 2 and 3, the end offset of the last sentence always equals the length of the given string; however, the handling of blanks is inconsistent among the non-last sentences vs. the last sentence.
On the other hand, in example 1, the spans exclude trailing blanks for all sentences; however, it might be undesirable that the final whitespace is not represented in the spans.

**Comment by alvations** [comment]
I think this is the expected behavior sentence tokenizers. We want to avoid any movement of strings (whitespace inclusive) between sentences but if it's heading or trailing whitespaces it's natural to strip them before passing it to the sentence tokenizers.

Keeping in mind that the input to sentence tokenizers are either:
 - paragraphs
 - documents

Most probably the paragraphs are taken from a document using newlines or double newlines as delimiters or `<p>...</p>` tags from HTML files. And for documents, the EOF is the ending delimiter.  Given that knowledge stripping the trailing and heading whitespaces shouldn't be a problem. 

Although it might differ in specific use-cases for sentence tokenizers but if we consider the usual tokenization of paragraphs/documents, the strategy to do `str.strip()` before feeding it into the sentence tokenizer should be sound. And to assume that jumping indices from end of one sentence to another are non-content whitespaces should also be sound.

In code, the common use case of the `span_tokenize` would look something like :

```python
>>> from nltk.tokenize import PunktSentenceTokenizer
>>> pst = PunktSentenceTokenizer()
>>> sent3 = 'See Section 33.  Or Section 213  '
>>> pst.span_tokenize(sent3.strip())
[(0, 15), (17, 31)]
>>> sents_idx = pst.span_tokenize(sent3.strip())
>>> for start, end in sents_idx:
...     print (start, end, [sent3[start:end]])
... 
0 15 ['See Section 33.']
17 31 ['Or Section 213']
```

**Comment by lfurrer** [comment]
So you are saying that expected behaviour of a sentence splitter is to be inconsistent with regard to trailing whitespace?

Calling `str.strip()` before feeding it to the sentence splitter is an obvious work-around to get predictable behaviour. But I argue that the sentence splitter should be consistent in the way it treats trailing whitespace in the first place.
Especially since this behaviour is not documented, as far as I know.
So if you want to know, as a user, if the sentence splitter reports trailing whitespace or not, you have to do a few tests to find out. And if your tests don't happen to contain a case like example 1 above (last sentence ends with parenthesis), then you will draw the wrong conclusion that trailing whitespace is reported. This leads to hard-to-track bugs.

**Comment by alvations** [comment]
Personally, I would never pass in an unstripped string to any NLP process. IMO, it's just cleaner for me to know that no functions (tokenizers/taggers/parsers/etc.) give me spurious output when it comes to heading/trailing whitespaces =)

~~Do post the issue to https://groups.google.com/forum/#!forum/nltk-users and/or https://groups.google.com/forum/#!forum/nltk-users for further discussion from other users/devs too.~~

**Comment by lfurrer** [comment]
Did you mean to link to the same forum twice?

**Comment by lfurrer** [comment]
I don't see need discussing this issue in a forum – I don't see a point in discussing the pros and cons of reporting trailing whitespace in general.
Here is the bug tracker, and I think it's clearly a bug.
I figured the NLTK devs might want to fix this in a future release, or at least put a note in the doc(string) that trailing whitespace is reported sometimes, but not always.
But if you, as an NLTK developer, think it's ok for a function to produce inconsistent output without being documented, then be it – I fixed my code to work around this inconsistency anyway.

**Comment by alvations** [comment]
~~Do feel free to discuss further on the google groups or do a Pull Request (PR) with the fixes and it will go through code/feature review where the other developers/users can put in their views on the PR.~~

@en-dash I think I misunderstood what you meant. Just to double check, do you mean to apply a fix like this: https://github.com/alvations/nltk/commit/5cf26536d4251c46237af9d674d1358881dceb6b
