### ISSUE TITLE
Wordnet-LMF

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#144]
Add a corpus reader for Wordnet-LMF format.

http://en.wikipedia.org/wiki/Lexical_markup_framework
http://xmlgroup.iit.cnr.it/kyoto/index.php?option=com_content&amp;view=article&amp;id=143&amp;Itemid=129

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=651</p>

**Comment by ceilingcat** [comment]
I am interested in this as well.

**Comment by pquentin** [comment]
The original WordNet (Princeton WordNet) is the only WordNet that NLTK supports since no other WordNet that I'm aware of uses their format. To encourage experiments with [other wordnets](http://globalwordnet.org/wordnets-in-the-world/), I'd like to add support for more formats, starting with WordNet-LMF.

How would that work out? The `corpus.reader.wordnet` module roughly:
1. reads WordNet files
2. queries WordNet
3. computes similarity measures
4. queries PWN-specific information (morphy lemmatizer, verb frames, domains...)

Those concerns are highly coupled in the current implementation. To add WordNet-LMF support, one would need to change 1, keep 2 and 3 and remove 4. With some work, I think I could separate the PWN-only parts from the parts that all WordNets with synsets and hyponymy support.

My question is: how should the user query this new information? A few things to consider:
- Since 3.0 is nearly out, the existing interface for querying PWN should not change at all.
- Querying another WordNet should be as close as possible to querying the current PWN.
- It would be nice to be able to ask for a WordNet such as "WordNet Bahasa" or "OpenWN-PT" and get loading for free if that WordNet is in `nltk.data`.
- Not all existing similarity measures will work on all wordnets, and explicit error messages will be helpful (eg. "This worndet does not support domains").

I'd love some comments from someone familiar with nltk's architecture. Am I worrying too much? Am I over-engineering? Should I write the code and only consider the interface later on? Did I miss the elephant in the room?

**Comment by pquentin** [comment]
Oops, looks like I should have paid more attention to issue #505 from @fcbond. I guess I'll wait for @stevenbird to add it to nltk and nltk.data. Sorry for the noise.

**Comment by alvations** [comment]
A good [`NAF`/`KAF`](http://www.newsreader-project.eu/files/2013/01/techreport.pdf) reader API would be good.
