### ISSUE TITLE
blue_score:: modified_precision() zero division exception 

### ISSUE THREAD

**Issue by rbahumi** [nltk/nltk#1458]
Issue:
In modified_precision(), there is no check if the Counter has 0 results - if there are no ngrams in the hypothesis, a zero division exception is thrown.

Code to reproduce:

```
from nltk.translate import bleu as bleu_score

hypothesis = ['1', '2', '3']
references = [['1', '2', '3', '4']]
bleu_score(references=references, hypothesis=hypothesis)
```

Exception output:

```
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    bleu_score(references=references, hypothesis=hypothesis)
  File "/home/roei/anaconda2/lib/python2.7/site-packages/nltk/translate/bleu_score.py", line 79, in sentence_bleu
    return corpus_bleu([references], [hypothesis], weights, smoothing_function)
  File "/home/roei/anaconda2/lib/python2.7/site-packages/nltk/translate/bleu_score.py", line 146, in corpus_bleu
    p_i = modified_precision(references, hypothesis, i)
  File "/home/roei/anaconda2/lib/python2.7/site-packages/nltk/translate/bleu_score.py", line 287, in modified_precision
    return Fraction(numerator, denominator, _normalize=False)  
  File "/home/roei/anaconda2/lib/python2.7/site-packages/nltk/compat.py", line 700, in __new__
    cls = super(Fraction, cls).__new__(cls, numerator, denominator)
  File "/home/roei/anaconda2/lib/python2.7/fractions.py", line 162, in __new__
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(0, 0)

```

**Comment by rbahumi** [comment]
[Added a pull request for the fix.](https://github.com/nltk/nltk/pull/1459)

**Comment by alvations** [comment]
@rbahumi which version of the code are you using? The master branch or the develop branch?

This should have been previously fixed by allowing it to go through the smoothing function. I'll check the changes made from your PR in a while =)

**Comment by rbahumi** [comment]
Hi @alvations, 
Thank you for your quick response :-)

The _develop_ branch doesn't have this check. I can't really find a branch named _master_:

```
roei> git branch -r
  origin/HEAD -> origin/develop
  origin/alvations-patch-bleu
  origin/alvations-patch-senna
  origin/brill
  origin/bug_1458_modified_precision_zero_division_exception
  origin/ccg
  origin/childes
  origin/collections
  origin/defunct
  origin/develop
  origin/framenet
  origin/model
  origin/model2
  origin/nschneid-patch-1
  origin/nschneid-patch-2
  origin/panlex
  origin/pattern_groups
  origin/py25
  origin/relextract
  origin/test
  origin/wiki
```

I believe this  empty counter check was present in version 3.1

**Comment by alvations** [comment]
The counter check is no longer necessary after the #1383 and #1358. Actually it will mess up the `Fraction()` data structure that should be enforced throughout the modified precision, brevity penalty and bleu score. 

It seems like you're working on an `anaconda` package of the repo instead of the `develop` branch from https://github.com/nltk/nltk.git, i.e. you're not using the current `develop` branch from your github fork, you're using the version packaged in anaconda, c.f. your example in the previous post:

```
  File "/home/roei/anaconda2/lib/python2.7/fractions.py", line 162, in __new__
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(0, 0)
```

Could you do a git pull merge to the latest develop branch and then retry your example? I am not getting `ZeroDivisionError` error on my machine:

``` python
alvas@ubi:~/git/nltk$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__version__
'3.2.1'
>>> from nltk.translate import bleu as bleu_score
>>> hypothesis = ['1', '2', '3']
>>> references = [['1', '2', '3', '4']]
>>> bleu_score(references=references, hypothesis=hypothesis)
0.7165313105737893
```

---

Try the following:
- Do a fresh fork or pull merge of the repo from https://github.com/nltk/nltk to your github account
- Then do `git clone https://github.com/rbahumi/nltk.git`
- Then **change directory to where this version of the `nltk` that you've currently cloned** 
- Then try the example code above, it should work without the `ZeroDivisionError`

To ensure that you're in the right directory of the `nltk` fork and not the anaconda's version, do:

```
alvas@ubi:~/git/nltk$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__file__
'nltk/__init__.pyc'
```

You should **not** see  something like `/home/roei/anaconda2/lib/python2.7/nltk/__init__.pyc` If you were to do the `nltk.__file__` outside of the directory where you clone, on my machine it will look like this:

```
alvas@ubi:~$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__file__
'/usr/local/lib/python2.7/dist-packages/nltk/__init__.pyc'
```

**Comment by rbahumi** [comment]
You are correct, it does not happen in the develop branch.
But this is really weird, because I am also running version 3.2.1 (install with conda), and the bleu_score.py file is different to the develop branch. 

It is actually your commit (3dd4d82b704af16fbc5bc479796b11dc5d95c2aa) which solved the issue.

**Comment by alvations** [comment]
It's because the conda and pip is shipping the code based on the last minor version 3.2.1. The patch for the fringe cases in #1383 is after the release of 3.2.1. There should be a new minor release soon and that'll include the fringe cases fix as well as other feature improvements since the last release. 

@rbahumi  so would this issue (#1458 and #1459) be a close =) ?

**Comment by rbahumi** [comment]
Yes. Thank you very much for your quick response!
