### ISSUE TITLE
MaltEval in nltk.parse.malt?

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#147]
Adding an interface to MaltEval (http://w3.msi.vxu.se/~jni/malteval/) to nltk.parse.malt would be absolutely wonderful.  If need be, I could provide some Polish data to help test such an interface.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=656</p>

**Comment by alvations** [comment]
Closing this because it seems like `MaltEval` is an orphaned project and it [cannot be found even on wayback machine](http://web.archive.org/web/*/http://w3.msi.vxu.se/users/jni/malteval). I would love to visualize it dependencies and see how `MaltEval` works too but now I think there're [`brat`](http://brat.nlplab.org/) that can do the same job #668  =(
