### ISSUE TITLE
Normalizer in VADER not really bounding output to [-1.0, 1.0]

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1490]
The normalizer at https://github.com/nltk/nltk/blob/develop/nltk/sentiment/vader.py#L107 is not exactly normalizing the inputs to give an output bounded by [-1.0, 1.0] as reported in the docstring. Given the default value of `alpha=15`, the upperbound of the normalized outputs would be somewhere in the between (-0.13, 0.13) 

![](https://i.stack.imgur.com/p8De8.png)

The outputs gets funkier with other `alpha` values, see http://stackoverflow.com/questions/40325980/how-is-the-compound-polarity-score-calculated-in-python-nltk-vader-approach/40337646#40337646

@cjhutto any ideas whether this is the expected output of the normalizer? Usually a normalization function would expect some sort of mean/variance input or a list of inputs. For example, I would expect the normalization to be taken corpus wide such that the value of the `sum_s` will be normalized against all the `sum_s` computed by across sentences in the corpus.

**Comment by cjhutto** [comment]
--- About the scoring ---
·         The compound score is computed by summing the valence of each word in the lexicon, adjusted with rules, and then normalized to be generally between -1 (most extreme negative) and +1 (most extreme positive). This is the most useful metric if you want a single unidimensional measure of sentiment.  Calling it a “normalized weighted composite score” is accurate.
·         The Pos/Neu/Neg are each ratios for “proportion of text” that falls in each category (so these should all add up to be 1… or close to it with float operation).  These are the most useful metrics if you want multidimensional measures of sentiment.

--- About normalizing ---
It would be fine to use a typical unity normalization function of the form you describe (using known list of values such that max/min or mean/variance can be computed).  However, I (and many others) use VADER in a more "streaming" use case... like ingesting social media or other text on a daily basis, where this list of values (or any of its distribution characteristics) **cannot** be known in advance.  Thus, 
I chose a simple way to normalize given unknown or unbounded data.  I could have used the [hyperbolic tangent (tanh) function](https://en.wikipedia.org/wiki/Hyperbolic_function#Tanh) or the [logistic function](https://en.wikipedia.org/wiki/Logistic_function) or the [error function](https://en.wikipedia.org/wiki/Error_function)... but the implemented approach has the power of parsimony -- it's simple and easy to understand by a broad audience, and allows for comparisons of sentiment scores across many different data sets with straightforward interpretation (regardless of what the specific min, max or distribution parameters are among those various data sets).

**Comment by alvations** [comment]
@cjhutto Thanks for the explanation. Given the "streaming"/online use-case of the normalizer, that seems alright. 

But as for the upper-/lower-bound of the normalizer, there are cases that it'll be > 1.0 or <-1.0 if left unconstrained, e.g.

![](https://i.stack.imgur.com/6ICZK.png)

![](https://i.stack.imgur.com/v1l31.png)

IMHO, the docstring for the normalization function should still be corrected. Should we add a note in the docstring, that the boundary depends rather heavily on the alpha set?

**Comment by alvations** [comment]
@cjhutto would it be okay to do some sort of scaling so that the output of [nltk.sentiment.vader.normalize](https://github.com/nltk/nltk/blob/develop/nltk/sentiment/vader.py#L107) be bounded by -[1,1] ?

Is it alright if the function gets changed to something like:

```python
def stream_normalize(score, alpha=15, beta=1, min_max=(-1.0, 1.0)):
    """
    Normalize the score using the function to approximates the 
    maximum expected value. 
        x := beta * x / (x^2 + alpha) 
    
    Using the default parameters (alpha=15, beta=1) will return a score that
    ranges between (-0.123, 0.123). 

    To achieve a normalize score ranging [-1.0, 1.0], users can set the 
    alpha and beta parameters 15 and 8 respectively. 
    """
    norm_score = beta*score/math.sqrt((score*score) + alpha)
    _min, _max = min_max
    if norm_score < min: 
        return _min
    elif norm_score > max:
        return _max
    else:
        return norm_score
```

Since we know that the max of `x / (x^2+15)` is close to 0.128, we can add a priori scaling factor of 8, i.e. `8x/(x^2+15)` which its max is close to 1.03. So the propose solution with a beta scaling variable of 8 to make it become a bounded normalizer by clipping the max and min to [-1,1] . And the scaling variable shouldn't change the variance of the normalization function.

The default `alpha`, `beta` and `min_max` parameters would still reflect the implementation of the version described in the paper.

**Comment by cjhutto** [comment]
Perhaps I'm misinterpreting what you're trying to say.  
"we know that the max of `x / (x^2+15)` is close to 0.128" ... this is not an accurate depiction of what VADER is doing - note: VADER is actually doing `score / math.sqrt((score*score) + alpha)`.  Your equation is missing the key part of taking the square root of the denominator.

Indeed it should be clear from the example sentences (without doing any math) that the actual output from VADER is not bound to 0.128 -- just take a look at the outputs produced in the example sentences of '`__main__`'.  (see examples [here](https://github.com/cjhutto/vaderSentiment))
For example, the following sentence:
          `"VADER is VERY SMART, really handsome, and INCREDIBLY FUNNY!!!"` 
returns a compound score of **0.9469**.  The output clearly isn't bounded to a max of 0.128. 
   This score is near the ceiling (without adding another scalar, `beta`, or if you wish, assume `beta=1`) because VADER already scales up the score (or "`x`" in your equation) several times: 
1.) the sentence contains several high-valence positive words (each instance of positive valence words scales up the score according to the empirically derived sentiment intensity of the particular word); 
2.) the sentence has sentiment polarity emphasis resulting from conventional use of capitalization (the value of the polarity increase is an empirically derived constant); 
3.) the sentence uses degree modifiers such as "very", "really", and "incredibly" (each instance scales up the score - the value of the increase is also modified by whether the degree modifier word is in all caps when the surrounding text is not - see item 2 above);
4.) the sentence makes use of a social convention signalling increased sentiment intensity by flooding exclamation points (each exclamation point [up to 4 of them] scales up the score, and the value of each increase is an empirically derived constant).

It's true that VADER is optimized for sentiment analysis at the **sentence** level (which is why 15 is a pretty good default value for `alpha`... that's about the upper limit on "`score`" at the sentence level, even with all the scaling up from VADER's rule-based sentiment reasoner).  But, I can imagine a hypothetical situation where someone deviates... Say, for example, that a person was wanting to analyze the sentiment of the entire "editorial news cycle" in a given week (say, election week) and wanted to compare it to the weeks preceding and then following that week... let's say they are doing this by analyzing all the text from the editorial sections of every major newspaper for those weeks (and they were not breaking the articles down to the sentence level first, which is currently how VADER would work best)... then I can see how the concerns over "unbounded scores" could become an issue.  Since I'm planning an update to VADER, I will definitely consider putting the hard limits [-1.0, 1.0] on the output, but I'm not sure that a `beta=8` parameter is necessary, given the examples I've shown on [VADER's GitHub page](https://github.com/cjhutto/vaderSentiment).  I may end up using something like the hyperbolic tangent function or the logistic function, since they are both well established unity-based normalization functions for unbounded data... or I might not change the equation at all (aside from implementing the -1.0, 1.0 limits).

With all that said -- it **is** open source code.  The MIT license gives you leave to use it or change it as  you desire... so, as long as you are aware of the consequences -- for example, if you publish the results of your sentiment analysis, and someone else wanted to replicate or compare to your results, it would not be valid unless they also change their normalization function to match your output -- use it as you wish!

**Comment by alvations** [comment]
Thanks @cjhutto for the detailed explanation! Will close this issue =)
