### ISSUE TITLE
stem_word and lower case stem output in v3.2.2

### ISSUE THREAD

**Issue by iranianpep** [nltk/nltk#1575]
Hi,

Just wanted to confirm the following things affected by the recent upgrade to v3.2.2:
- There is no `stem_word` function in `PorterStemmer()`. I had to replace it with `stem()`
- Unlike before, `stem` returns lower case of a word e.g. `stem` for `Stemming` (http://text-processing.com/demo/stem/ is the same as before).

Cheers,
Ehsan

**Comment by stevenbird** [comment]
@ExplodingCabbage would you please respond to this? Also, are there other changes to the API?

**Comment by ExplodingCabbage** [comment]
Hi @iranianpep. Yes, both of those changes were intentional. @stevenbird, yes, these are the only two backwards-incompatible changes.

Both changes are noted in the commit message at https://github.com/nltk/nltk/commit/d8402e3f43ce3b7a3c7ecb45c3b8b1f75c7124e2, though these points didn't make it to the [release notes](http://www.nltk.org/news.html):

> Minor compatability-breaking changes, with justification:
>
> - Removed call to _adjust_case prior to stemming; this isn't part of the Porter algorithm, and isn't done by other NLTK stemmers like Lancaster or Snowball, so it seemed wrong
> - Remove stem_word from PorterStemmer. It does pretty much the same as stem(), and isn't part of the StemmerI interface. Anybody who was previously using it (hopefully nobody) can just change their code to call stem() if they update NLTK.

I'm guessing @stevenbird overlooked these points when merging my PR and when creating the release. I suppose I ought to have queried what the plan was for releasing the changes, since if NLTK follows SemVer (I'm unsure if it does) then a change like this would require a major version bump, and the right thing to do would've been either to delay release of the whole rewrite until the next major version release or to have an API-maintaining patch release followed by implementing the two API changes in the next major release.

How would you like to now proceed, @stevenbird?

**Comment by iranianpep** [comment]
@ExplodingCabbage Thanks, you can close this if you want.

**Comment by jayvdb** [comment]
@stevenbird, @ExplodingCabbage, ping

**Comment by ExplodingCabbage** [comment]
I'm only a contributor, not a collaborator, so I've got no power to close this, @jayvdb. :) And possibly @stevenbird might want to adjust the release notes before doing so, I'm not sure.

**Comment by RodgerKibble** [comment]
Hi, will someone be updating the example in section 3.6 of the book which still shows uc output from Porter? This is confusing my students.  Many thanks.

**Comment by alvations** [comment]
Validating the outputs from Chapter 3.6 of the book.

```python
>>> from nltk import word_tokenize
>>> from nltk.stem import PorterStemmer
>>> porter = PorterStemmer()

>>> raw = """DENNIS: Listen, strange women lying in ponds distributing swords
... is no basis for a system of government.  Supreme executive power derives from
... a mandate from the masses, not from some farcical aquatic ceremony."""

>>> tokens = word_tokenize(raw)

>>> [porter.stem(t) for t in tokens]
['denni', ':', 'listen', ',', 'strang', 'women', 'lie', 'in', 'pond', 'distribut', 'sword', 'is', 'no', 'basi', 'for', 'a', 'system', 'of', 'govern', '.', 'suprem', 'execut', 'power', 'deriv', 'from', 'a', 'mandat', 'from', 'the', 'mass', ',', 'not', 'from', 'some', 'farcic', 'aquat', 'ceremoni', '.']
```

The other example using `IndexedText` doesn't change since it's not printing the direct output of the `porter.stem()`.

Changes suggested on https://github.com/nltk/nltk_book/pull/216

**Comment by alvations** [comment]
Closing issue, https://github.com/nltk/nltk_book/pull/216 is merged =)

Thanks @iranianpep @jayvdb @RodgerKibble for raising the issue! 
Thanks @ExplodingCabbage for verifying the changes!
