### ISSUE TITLE
Unavailable corpora are breaking tests

### ISSUE THREAD

**Issue by fievelk** [nltk/nltk#1580]
Tests are failing with python 3.5 because of some corpus readers whose corpora are not distributed within NLTK. For example: [`nkjp`][1], [`ipipan`][2], [`ycoe`][3].

You can reproduce these problems using `tox -e py35 /nltk/nltk/corpus/__init__.py`.

I would like to find an answer the following questions:
1. Why is this problem only arising when we run `tox` using python 3.5, and not with previous versions?
2. How can we solve it?

If we want to keep corpus readers even for those corpora that are not currently shipped with NLTK, I think we need to avoid raising exceptions when these corpus readers are loaded. But where should we fix the problem? I briefly write the problems for each of these corpora:

- [`nkjp`][1]: it is not available, but we get this message if we try to use it:
  > Resource 'corpora/nkjp' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> `nltk.download()`

  But the download cannot be used to download it, since we do not have `nkjp` on `nltk_data`.

- [`ipipan`][2]: same as before. The corpus is not available on `nltk_data`, but when we try to use it we get this message:
  > Resource 'corpora/ipipan' not found.  Please use the NLTK
  > Downloader to obtain the resource:  >>> `nltk.download()`

- [`ycoe`][3]: we don't have the corpus, and we get this error:
  > OSError: No such file or directory: `nltk_data/corpora/ycoe/psd`

I'm also wondering: how could we test a corpus reader if we do not have the corpus it is supposed to read? At the moment, we are not covered against the possibility that any change made to the syntax of original corpus could make our reader useless. Anyway, this is not what I wanted to discuss here.

Could you please give your opinion about these problems?
  
[1]: https://github.com/fievelk/nltk/blob/develop/nltk/corpus/reader/nkjp.py
[2]:https://github.com/fievelk/nltk/blob/develop/nltk/corpus/reader/ipipan.py
[3]: https://github.com/fievelk/nltk/blob/develop/nltk/corpus/reader/ycoe.py

**Comment by alvations** [comment]
I'm not actually sure why these corpora reader exists and I'm not sure whether it's good to keep readers for corpora that can't be shipped with `nltk`. 

And as for test, we surely can't test them. If we let them stay, I think it's best to skip them and wait for either the maintainers or users to patch it. I'm not exactly sure how to skip them within `tox` though.

Otherwise, reviving the `nltk.contrib` package would be a solution to move such corpora readers that can't be shipped with NLTK and possibly 3rd party interfaces, that we don't want to maintain as often, there. Like how `tensorflow` handles it: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib

For `ycoe`, from the docstring:

```
Corpus reader for the York-Toronto-Helsinki Parsed Corpus of Old
English Prose (YCOE), a 1.5 million word syntactically-annotated
corpus of Old English prose texts. The corpus is distributed by the
Oxford Text Archive: http://www.ota.ahds.ac.uk
```

Maybe the error messages should include information from the docstring, e.g.

> OSError: No such file or directory: nltk_data/corpora/ycoe/psd
>                Please refer to http://www.ota.ahds.ac.uk to download the corpus.

For `ipipan` corpus, it gets more cryptic the source code in `nltk/corpus/reader/ipipan.py` says refer to http://korpus.pl/en/ and the site needs login access =(

Looking at http://nkjp.pl/index.php?page=0&lang=1,  i think `ipipan` and `nkjp` should be two related corpora. I'm not sure how we can deal with these corpora. The download link for `nkjp` looks like it's http://nkjp.pl/index.php?page=14&lang=1

**Comment by stevenbird** [comment]
I don't know why the problem only arises for Python 3.5. I like @alvations' suggestion to skip the tests, and if necessary, comment out the offending lines in `corpus/__init__.py`.

**Comment by alvations** [comment]
This should be resolved since these datasets no longer exist on nltk_data =) #1484 #1485
