### ISSUE TITLE
Various GUIs not working in Python3

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#160]
It appears that various GUI components of nltk, (graphy stuff) no longer work in Python3. I believe this is mainly due to the use of Tkinter and TkFont which is no longer supported (just TkFont).
Anyways, how about we move on to a more modern GUI toolkit like Qt? Maybe a web based interface would be nice?<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=675</p><hr/><h2>earlier comments</h2>

<p><strong>bobobo1618 said, at 2011-05-02T00:34:31.000Z:</strong></p>

<p>Btw Steven, the lack of commits and such from me doesn't mean I've given up or moved on. I've been working through the book.</p><p><strong>xim@8d.no said, at 2011-06-02T22:45:15.000Z:</strong></p>

<p>I was able to bring up some basic graphs, e.g.

    nltk.FreqDist(['foo', 'bar', 'baz', 'foo']).plot()

Even the .download() interface opens, and works after applying the patch attached.</p><p><strong>bobobo1618 said, at 2011-06-03T01:55:46.000Z:</strong></p>

<p>Thanks for that, your patch has been added :)</p>

**Comment by paulproteus** [comment]
It seems to me that someone ought to:
- Make sure they are running Python 3
- Install NLTK by downloading the latest git master
- Try to run various NLTK GUIs, and report on specific problems

If so, that seems to me to be a good newcomers bug in NLTK, which is great, because I'm trying to find such bugs for an upcoming 'how to get involved in open source' event.

Per http://docs.python.org/3.3/library/tkinter.html it seems to me Tkinter is still around in Python-land, but I may be mistaken in my reading of that.

**Comment by kmike** [comment]
@jskda do you know if we can close this ticket?

**Comment by kmike** [comment]
I don't think we should move to QT because it is could be painful to install, and tkinter is in standard library. In case of @jskda doesn't know if all GUIs are working, I added a "goodfirstbug" tag as  @paulproteus suggested.

**Comment by stevenxxiu** [comment]
@kmike I tested everything in `nltk.apps` and they appear to work. `FreqDist.plot()` and the download gui also work so I think this can be closed.
