### ISSUE TITLE
better explanations for how to use HMM training methods

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#162]
A short, clear explanation of how and when to use the unsupervised HMM training methods would be good, perhaps for the HOWTO section.

Issue 681, for example, would have been found much more quickly if HiddenMarkovModelTrainer.train_unsupervised were called more often.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=682</p>

**Comment by alexrudnick** [comment]
Where _are_ the HOWTO docs these days? Did we misplace those? ...

**Comment by stevenbird** [comment]
The old HOWTOs are here:
http://nltk.googlecode.com/svn/trunk/doc/howto/index.html

The sources are here:
https://github.com/nltk/nltk/tree/master/nltk/test

However, we should migrate documentation into the modules themselves, so that this is accessible via help() and via nltk.org's documentation section. This migration is ongoing. These days, nltk/test/*.doctest is the home for regression tests only.
