### ISSUE TITLE
corpus_bleu does not match multi-bleu.perl for very poor translations

### ISSUE THREAD

**Issue by AndreasMadsen** [nltk/nltk#1634]
example:

**tokenized reference:**
```
Their tasks include changing a pump on the faulty stokehold .
Likewise , two species that are very similar in morphology were distinguished using genetics .
```

**tokenized hypothesis:**
```
Teo S yb , oe uNb , R , T t , , t
Tue Ar saln S , , 5istsi l , 5oe R ulO sae oR R
```

with the `multi-bleu.perl` script the BLEU score is `0`:

```
BLEU = 0.00, 3.4/0.0/0.0/0.0 (BP=1.000, ratio=1.115, hyp_len=29, ref_len=26)
```

with `corpus_bleu` the BLUE score is `43.092382`, my understanding is that default `corpus_bleu` settings corresponds to the `multi-bleu.perl` script.

---

```py
from nltk.translate.bleu_score import corpus_bleu

references = [
    'Their tasks include changing a pump on the faulty stokehold .',
    'Likewise , two species that are very similar in morphology were distinguished using genetics .'

]

hypothesis = [
    'Teo S yb , oe uNb , R , T t , , t',
    'Tue Ar saln S , , 5istsi l , 5oe R ulO sae oR R'
]

hypothesis_tokens = [line.split(' ') for line in hypothesis]
references_tokens = [[line.split(' ')] for line in references]

# calculate corpus-bleu score
bleu = corpus_bleu(
    references_tokens, hypothesis_tokens
)

print('BLEU: %f' % (bleu * 100)) # 43.092382
```

**Comment by alvations** [comment]
If we look at the numbers from `multi-bleu.perl`, we see unigram matches of `3.4`. 

```
BLEU = 0.00, 3.4/0.0/0.0/0.0 (BP=1.000, ratio=1.115, hyp_len=29, ref_len=26)
```

And the bad thing about `multi-bleu.perl` is that it throws away this 3.4 and assumes 0 score once it doesn't have a higher order ngram match. This is not an ideal situation.

So to resolve the isse in #1554,  the `develop` branch of the `nltk` after #1330 and #1554 produces:

```python
>>> from nltk.translate.bleu_score import corpus_bleu
>>> hyp = "Teo S yb , oe uNb , R , T t , , t Tue Ar saln S , , 5istsi l , 5oe R ulO sae oR R"
>>> ref = "Their tasks include changing a pump on the faulty stokehold . Likewise , two species that are very similar in morphology were distinguished using genetics ."
>>> corpus_bleu([[ref]], [hyp])
0.03794338950850931
```

If we split the sentences up:

```
>>> ref1 = "Their tasks include changing a pump on the faulty stokehold ."
>>> ref2 = "Likewise , two species that are very similar in morphology were distinguished using genetics ."
>>> hyp1 = "Teo S yb , oe uNb , R , T t , , t"
>>> hyp2 = "Tue Ar saln S , , 5istsi l , 5oe R ulO sae oR R"
>>> corpus_bleu([[ref1], [ref2]], [hyp1, hyp2])
0.09768267564445479
```

----

**Why does `nltk` calculate BLEU differently from `multi-bleu.perl`?**

NLTK version of BLEU is closer to [`mteval-v13a.pl`](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v13a.pl) instead of `mutl-bleu.perl`, see https://github.com/nltk/nltk/blob/develop/nltk/test/unit/translate/test_bleu.py#L185

**Why don't `nltk` emulate late `multi-bleu.perl`?**

Though `multi-bleu.perl` has been recently used widely in deep-learning / nlp publications, the canonical scrip that the machine translation community has been using to evaluate MT shared task is `mteval-v13.pl`.

**What's bad about `multi-bleu.perl`?**

Firstly, it threw away the unigram counts that we see in the example above. Beyond that, it produces undesirable outputs when the reference is short and translation is accurate, see  https://gist.github.com/alvations/e5922afa8c91472d25c58b2d712a93e7

There are other issues that `multi-bleu.perl` produces that we can resolve with new features NLTK's BLEU implementation, e.g. using [`auto_reweigh`](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L84) or [`smoothing_function`](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L410)

----

To use the bleeding edge version of `nltk`, please do:

```
pip install -U https://github.com/nltk/nltk.git
```

But do note that the `develop` branch of NLTK is under development so it is possible that the code might break for some modules/functions.

**Comment by alvations** [comment]
Yes, buggy! Sorry previous comment was wrong.

**Comment by alvations** [comment]
Just like to check, did you see a warning message like this:

```python
>>> from nltk.translate.bleu_score import corpus_bleu
>>> hyp = "Teo S yb , oe uNb , R , T t , , t Tue Ar saln S , , 5istsi l , 5oe R ulO sae oR R"
>>> ref = "Their tasks include changing a pump on the faulty stokehold . Likewise , two species that are very similar in morphology were distinguished using genetics ."
>>> corpus_bleu([[ref.split()]], [hyp.split()])
nltk/translate/bleu_score.py:473: UserWarning: 
Corpus/Sentence contains 0 counts of 2-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)
0.43092381945890607
```

In that case, the issue can be resolved by using `SmoothingFunction.method4`, e.g.:

```python
>>> from nltk.translate.bleu_score import SmoothingFunction
>>> from nltk.translate.bleu_score import corpus_bleu
>>> hyp = "Teo S yb , oe uNb , R , T t , , t Tue Ar saln S , , 5istsi l , 5oe R ulO sae oR R"
>>> ref = "Their tasks include changing a pump on the faulty stokehold . Likewise , two species that are very similar in morphology were distinguished using genetics ."
>>> chencherry = SmoothingFunction()
>>> corpus_bleu([[ref.split()]], [hyp.split()], smoothing_function=chencherry.method4)
0.17261970532895454
```

**Comment by AndreasMadsen** [comment]
A BLEU score of `17` is still way too high.

**Comment by alvations** [comment]
~~0.17 out of 100.0 BLEU, **not** 0.17 out of 1.0 BLEU ;P~~


BTW, did you see the warning? It's important because if the warning isn't there, then we have to make it more prominent by maybe raising an error.

**Comment by AndreasMadsen** [comment]
> 0.17 out of 100.0 BLEU, not 0.17 out of 1.0 BLEU ;P

Are you sure about that? If I set `hyp = ref` then I get a BLEU score of `1.0` not `100`:

```py
>>> from nltk.translate.bleu_score import SmoothingFunction
>>> from nltk.translate.bleu_score import corpus_bleu
>>> ref = "Their tasks include changing a pump on the faulty stokehold . Likewise , two species that are very similar in morphology were distinguished using genetics ."
>>> hyp = ref
>>> chencherry = SmoothingFunction()
>>> corpus_bleu([[ref.split()]], [hyp.split()], smoothing_function=chencherry.method4)
1.0
```

> BTW, did you see the warning? It's important because if the warning isn't there, then we have to make it more prominent by maybe raising an error.

Yes, I did get the warning.

**Comment by alvations** [comment]
Whoops, my bad. Maybe someone with fresh eyes can take a look at it. I'll be busy in the next 1-2 months =(

Any suggestions on how to fix this?

**Comment by alvations** [comment]
I'm trying to take a poke at this over the weekend. Any suggestions on how we should approach this?

**Comment by alvations** [comment]
@AndreasMadsen actually I've worked through the math by hand and 17 BLEU for the example you've given is really similar to the "the the the the the the the" example in the [original BLEU paper](http://www.aclweb.org/anthology/P02-1040.pdf), see also https://gist.github.com/alvations/e5922afa8c91472d25c58b2d712a93e7 . In code:

```python
>>> reference1 = 'the cat is on the mat'.split()
>>> reference2 = 'there is a cat on the mat'.split()
>>> hypothesis1 = 'the the the the the the the'.split()
>>> references = [reference1, reference2]
>>> float(modified_precision(references, hypothesis1, n=1)) # doctest: +ELLIPSIS
0.2857...
>>> bleu([ref1, ref2], hyp)
0.7311104457090247
```

The 17 BLEU (smoothed) or 34 BLEU (unsmoothed, taking only unigrams into account) is coming from the modified precision being ridiculously high from the punctuation. One quick hack to check for bad sentences is to remove the punctuation before running BLEU, e.g.:

```python
>>> from nltk.translate.bleu_score import corpus_bleu
>>> from string import punctuation
>>> 
>>> hyp = "Teo S yb , oe uNb , R , T t , , t Tue Ar saln S , , 5istsi l , 5oe R ulO sae oR R"
>>> ref = "Their tasks include changing a pump on the faulty stokehold . Likewise , two species that are very similar in morphology were distinguished using genetics ."
>>> 
>>> hyp = ''.join([ch for ch in hyp if ch not in punctuation])
>>> ref = ''.join([ch for ch in ref if ch not in punctuation])
>>> corpus_bleu([[ref.split()]], [hyp.split()])
0
```

The implementation of the basic BLEU score in NLTK isn't exactly flawed but it has never meant to emulate the effects of `multi-bleu.pl` because `multi-bleu.pl` put in a hack that wasn't considered in the paper, i.e. to return a 0.0 score if any of the 1- to 4- gram returns a 0.0 precision. 

To emulate that behavior, I've added similar "hack" to 

 1. set the precision (a fraction/floating point) to the smallest negative value that any system can take and then 
 2. taking the log of it would have caused it to end up with large negative value and 
 3. when the BLEU formula takes the exponential of the modified precision before multiplying it with the brevity penalty, it should set the precision back to the minimal negative value and 
 4. the final rounding off that's kicked in when `emulate_multibleu` parameter is set to True would cause the final BLEU value to be clipped at 0, i.e.:

```python
>>> import sys
>>> from math import log, exp
>>> sys.float_info.min
2.2250738585072014e-308
>>> log(sys.float_info.min)
-708.3964185322641
>>> exp(log(sys.float_info.min))
2.2250738585072626e-308
>>> round(exp(log(sys.float_info.min)), 4)
0.0
```

**Comment by AndreasMadsen** [comment]
@alvations I see, thanks for looking into it.
