### ISSUE TITLE
Defining utf8 encoding for all `.py` files

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1664]
Is it a good idea to add magic encoding ([PEP 263](https://www.python.org/dev/peps/pep-0263/#defining-the-encoding)) on all `.py` files to handle non-ascii systems e.g. #1024 ?

```
# -*- coding: utf-8 -*-
```

**Comment by nschneid** [comment]
Doesn't this only indicate the encoding of the source file itself (in case there are any non-ASCII string literals or variable names)? I don't think it changes the default encoding of input/files processed by the code.

**Comment by alvations** [comment]
Yes, it only changes the source encoding. 

But when the interpreter calls the [ntpath](https://github.com/python/cpython/blob/master/Lib/ntpath.py), the non-ascii strings will enter as part of the code and possibly that happens when `os.path.expanduser('~/')` lines in `nltk` "breaks" on the user-side. 

But I'm not sure, we have to verify that that is the case, first.

**Comment by nschneid** [comment]
If the user writes code with an import that uses non-ASCII characters, then yes, that file should declare its source encoding. But I don't think it would help to declare the source encoding in files that are pure-ASCII.

The problem in #1024 seems to be the `unicode_literals` import. `os.path.expanduser()` apparently assumes that the type of its argument—which, with `unicode_literals`, is `unicode`—matches the type of the environment variable, which is `str` (bytes in 2.7, unicode in 3.x). This mismatch in 2.7 is not a problem with all-ASCII strings, because an ASCII bytestring can be concatenated with a unicode string. But it fails if the bytestring is non-ASCII:

```py
>>> u'\u102a'.encode('utf-8')
'\xe1\x80\xaa'
>>> '\xe1\x80\xaa' + '~/'
'\xe1\x80\xaa~/'
>>> '\xe1\x80\xaa' + u'~/'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)
```

Is the `unicode_literals` import really necessary? If so, then perhaps all literals passed to `os.path` should be wrapped in `str()`, effectively negating `unicode_literals` in 2.7.

**Comment by nschneid** [comment]
P.S. as suggested in [#1593](https://github.com/nltk/nltk/pull/1593#issuecomment-273356452), `unicode_literals` can be a source of nasty bugs. This is because `unicode` is the "non-default" string type in 2.7, and some libraries may use `str` strings in ways that don't play nicely with `unicode` strings. (I recall experiencing this with a 3rd-party XML processing library, so it's not just `os.path`.)

**Comment by alvations** [comment]
Hopefully these will go away once the [Python2.7 goes away](https://pythonclock.org). Closing the issue =)
