### ISSUE TITLE
In nltk.corpus.wordnet, some synsets are not accessible through their parents

### ISSUE THREAD

**Issue by rafaveguim** [nltk/nltk#1705]
In the following example "european_country.n.01" is among the hypernyms of "portugal.n.01", but "portugal.n.01" is not listed as a hyponym of "european_country.n.01".

```python
>>> wn.synset("european_country.n.01").hyponyms()
[Synset('balkan_country.n.01'), Synset('scandinavian_country.n.01')]

>>> wn.synset('portugal.n.01').hypernym_paths()
[[Synset('entity.n.01'), Synset('physical_entity.n.01'), Synset('object.n.01'), Synset('location.n.01'), Synset('region.n.03'), Synset('district.n.01'), Synset('administrative_district.n.01'), Synset('country.n.02'), Synset('european_country.n.01'), Synset('portugal.n.01')]]

>>> wn.synset('portugal.n.01').hypernyms()
[]
```

**Comment by alvations** [comment]
Due to the hand-crafted nature of Wordnet, this is actually a feature not a bug =)

In the [Princeton WordNet](http://wordnetweb.princeton.edu/perl/webwn?o2=1&o0=1&o8=1&o1=1&o7=1&o5=1&o9=&o6=1&o3=1&o4=1&s=portugal&i=0&h=0#c), there's a difference between `hypernyms()` and `instance_hypernyms()`:

```python
>>> from nltk.corpus import wordnet as wn
>>> wn.synset('portugal.n.01')
Synset('portugal.n.01')
>>> wn.synset('portugal.n.01').hypernyms()
[]
>>> wn.synset('portugal.n.01').instance_hypernyms()
[Synset('european_country.n.01')]
```

The reason why the path to instance hypernyms appears in `hypernym_paths` is because when traversing wordnet for the hypernym paths, both the "direct" hypernyms and instance hypernyms were considered, see https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L555 

And in the original wordnet format, it's the direct hypernyms are indicated with `@` whereas the instance hypernyms are indicated with `@i`. Similarly, the distinction is drawn in the hyponyms and instance hyponyms too.

The question then becomes, should the default behavior of `Synset.hypernyms()` return the list of the concatenated "direct" and instance hypernyms or just the "direct" hypernyms?

**Comment by rafaveguim** [comment]
Oh! I wasn't aware of this distinction!
Thanks @alvations
