### ISSUE TITLE
KeyError in MosesDetokenizer

### ISSUE THREAD

**Issue by moiri-gamboni** [nltk/nltk#1729]
Getting a KeyError when trying to detokenize three or more symbols:
```
from nltk.tokenize.moses import MosesDetokenizer
MosesDetokenizer().detokenize(['```'])
```
```
  File "/usr/local/lib/python3.6/site-packages/nltk/tokenize/moses.py", line 613, in detokenize
    return self.tokenize(tokens, return_str)
  File "/usr/local/lib/python3.6/site-packages/nltk/tokenize/moses.py", line 574, in tokenize
    if quote_counts[normalized_quo] % 2 == 0:
KeyError: '```'
```
In printable ASCII characters, the problem seems to occur for ",  ',  and `.
Using Python 3.

**Comment by alvations** [comment]
@moiri-gamboni Thanks for catching that!! My bad on this.

I missed the initialization for the normalized quote at https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L566. Currently, the line `quote_counts.get(normalized_quo, 0)` does nothing. 

It should have been:

```python
quote_counts[normalized_quo] = quote_counts.get(normalized_quo, 0)
```

It should correspond to this line in [`detokenizer.perl in moses`](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/detokenizer.perl#L153). 

----

After the #1730 patch:

```python
>>> from nltk.tokenize.moses import MosesDetokenizer
>>> MosesDetokenizer().detokenize(['```'])
[u'```']
>>> MosesDetokenizer().detokenize(['```'], return_str=True)
u'```'
```

Note that lumping the quotes together is the expected behavior as `detokenizer.perl` :

```
alvas@ubi:~/git/nltk$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk.tokenize.moses import MosesDetokenizer
>>> MosesDetokenizer().detokenize(['"', '"'])
[u'"""']
>>> exit()
alvas@ubi:~/git/nltk$ cd ~/mosesdecoder/scripts/tokenizer/
alvas@ubi:~/mosesdecoder/scripts/tokenizer$ perl detokenizer.perl -l en
Detokenizer Version $Revision: 4134 $
Language: en
"" "
"""
```
