### ISSUE TITLE
WordNet 3.1

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#179]
Update WordNet data files to 3.1 once this data is available.
http://wordnet.princeton.edu/wordnet/download/current-version/

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=714</p>

**Comment by bluemont** [comment]
I just submitted this pull request to Homebrew for WordNet 3.1. Maybe it will be helpful:
https://github.com/bluemont/homebrew/commit/de39582d98fe4c2510e191c2f959e54f37ba2c51

**Comment by margold** [comment]
Version 3.1 is now available here: http://wordnet.princeton.edu/wordnet/download/current-version/. These are just the database (plain text) files which can be substituted for version 3.0 database files, which suggests that the format is exactly the same. In that case it seems all that needs to be done here is to substitute
https://github.com/nltk/nltk_data/tree/gh-pages/packages/corpora/wordnet.zip
with the new version 3.1 files.

**Comment by alvations** [comment]
an updated discussion on https://groups.google.com/forum/#!topic/nltk-dev/rLhXQFIt2Xk

**Comment by stevenbird** [comment]
@fcbond are there problems with NLTK upgrading English WordNet to 3.1? I'm happy to hold off upgrading if that would cause problems.

**Comment by fcbond** [comment]
Yes, we should wait until after the next global wordnet conference (in
January in Romania), when we will have a better integration of the
different languages.

On Tue, Oct 13, 2015 at 2:37 AM, Steven Bird notifications@github.com
wrote:

> @fcbond https://github.com/fcbond are there problems with NLTK
> upgrading English WordNet to 3.1? I'm happy to hold off upgrading if that
> would cause problems.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nltk/nltk/issues/179#issuecomment-147486887.

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by ghost** [comment]
As of May 10 2012 - a few months after this issue was filed - the [NLTK Data](https://github.com/nltk/nltk_data/tree/gh-pages) GitHub repository was created, separating this sort of concern from the NLTK GitHub repository. Can this issue report be migrated to the [NLTK Data bug tracker](https://github.com/nltk/nltk_data/issues), or at least closed here as invalid?

I appreciate the historical reason why this report was filed against this repository (i.e. the NLTK Data repo didn't exist at the time this report was filed), but even so, it seems a hostage to fortune to track another repository's issues on this repository's bug tracker.

**Comment by stevenbird** [comment]
Thanks @sampablokuper. This issue is not valid. Please see https://github.com/nltk/nltk_data/issues/18.
