### ISSUE TITLE
POS tagging after Tokenization using CoreNLP classes

### ISSUE THREAD

**Issue by tomirio619** [nltk/nltk#1876]
Hello,

I want to use the `CoreNLPTagger` to tokenize and POS-tag a big corpus.
However, there is no option to specify additional properties to the `raw_tag_sents` method in the `CoreNLPTagger` (in contrary to the `tokenize` method in `CoreNLPTokenizer`, which lets you specify additional properties). Therefore I'm not able to tell the tokenizer to e.g. not normalize the brackets and other stuff.

For example, I want to use the following tokenization options:
```python
additional_properties = {
            'tokenize.options': 'ptb3Escaping=false, unicodeQuotes=true, splitHyphenated=true, normalizeParentheses=false, normalizeOtherBrackets=false',
            'annotators': 'tokenize, ssplit, pos'
        }
```

Using the tokenizer before the tagger does also not work, as this will revert any of the additional options you set in the tokenizer.

I may be doing something wrong here, but I hope you can help me.

Thanks

**Comment by dimazest** [comment]
There is no way to implement it without changing the code.

You would need to add properties parameter to https://github.com/nltk/nltk/blob/develop/nltk/tag/stanford.py#L233 and update default_properties accordingly, check https://github.com/nltk/nltk/blob/develop/nltk/parse/corenlp.py#L232 for an example.

Also, since `GenericCoreNLPParser` already implements `ParserI` and `TokenizerI` https://github.com/nltk/nltk/blob/develop/nltk/parse/corenlp.py#L179 I would add `TaggerI` there. The logic behind is that `GenericCoreNLPParser` is an interface to a multi-functional tool.

Once `GenericCoreNLPParser` implements `TaggerI` and `CoreNLPParser` with `CoreNLPDependencyParser` handle it correctly I would remove `CoreNLPTagger`, `CoreNLPPOSTagger` and`CoreNLPNERTagger` or at least substitute them with functions that instantiate `CoreNLPParser `or `CoreNLPDependencyParser`.

**Comment by alvations** [comment]
Documentation for the new CoreNLP interface should also demonstrate that beyond the usual, parsing, tokenizing, tagging, it is possible for users to call custom pipelines using `api_call()` from `CoreNLPParser` super class `GenericCoreNLPParser`

**Comment by tomirio619** [comment]
Thanks, that solves my problem.

**Comment by Janiknoah** [comment]
Hello,

I am sorry I dont get the solution or may be I have a different Problem. 

I use the the coreNLPParser to tokenize my text. Example "...dem späteren Papst Benedikt XVI., in der Glaubenskongergation..."

Now the problem is, when I use the parser to tokenize my text I get a token with "XVI." which is correct. But when I use this token with the Core NLP Pos Tagger, I get two tokens back [u'XVI', u'NE'], [u'.', u'$.'] which I don't want. Can I somehow restict the tagger to the original tokens?

**Comment by tomirio619** [comment]
This is indeed the same problem I had.
You can see the annotator dependencies [here](https://stanfordnlp.github.io/CoreNLP/dependencies.html).
For POS-tagging, it will apply tokenization again, which explains why your token gets tokenized again.

The way I solved this is by creating an instance of `CoreNLPParser`, and specify the additional properties.
Now you call the function `api_call` with the properties you specified.
For example:
```python
from nltk.parse.corenlp import CoreNLPParser

stanford_parser = CoreNLPParser()
additional_properties = {
            'tokenize.options': 'ptb3Escaping=false, unicodeQuotes=true, splitHyphenated=true, normalizeParentheses=false, normalizeOtherBrackets=false',
            'annotators': 'tokenize, ssplit, pos'
        }
json_result = stanford_parser.api_call(your_text_here, properties=self.additional_properties)
                for sentence in json_result['sentences']:
                    for token in sentence['tokens']:
```

**Comment by Janiknoah** [comment]
That worked well! Thanks a lot!
