### ISSUE TITLE
nltk 2.0.4 get HTTP Error 403 when access pypi api

### ISSUE THREAD

**Issue by tom-aa** [nltk/nltk#1880]
https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html
pypi dropped http access of api

https://github.com/nltk/nltk/blob/2.0.4/distribute_setup.py#L50
so there will be an error during install in 2.0.x
could we fix it in the 2.0.5+ version?

**Comment by alvations** [comment]
@tom-aa the `distribute_setup.py` has been deprecated  and removed since a long time ago and the latest versions of NLTK uses `setup.py` with the native [`setuptools`](https://pypi.python.org/pypi/setuptools). Last known tagged version with it is [v3.0a1](https://github.com/nltk/nltk/blob/3.0a1/distribute_setup.py)

Modern `pip` and `python setup.py` should be able to handle NLTK installation with the current `setup.py` in the codebase. 

There isn't a tagged version of the NLTK code in the repository for version 2.0.5 too and we strongly encourage users to use version `> 3.2` and `>= 3.2.5` if possible because of the constant bug fixes. 

**Is there a reason to use NLTK v2.0.4?** Just curious so that we note who's using backdated NLTK versions and why.

**Comment by babbottscott** [comment]
We have an existing service coded against v2.0.5, and we are having to hack our provisioning scripts to death to provision new instances to run it due to this installation failure.  A backport or workaround would be greatly appreciated

In my brief (and non-python-guy) testing, changing https://github.com/nltk/nltk/blob/18c842fca78b77e2cdaced944903c793437a1034/distribute_setup.py#L50 from http to https is sufficient to make this install work again.

**Comment by alvations** [comment]
I've created a branch off 3ff37647eeb2327d943a8cc15acc30adfa1e806f where v2.0.5 (aka 3.0.1) took off with the `distribute_setup.py` with the change to https.

Before that change is "pip-able", it still requires 

 - new github release
 - updates on PyPI 

Until the above is done, you can do:

```
pip install https://github.com/user/repository/archive/2.0.5a.zip
```

----

It might be a better thing for us to know what breaks when you upgrade your code to NLTK > v.2.5.

Some questions to better help us to help you: 

 - Why are you still using v2.0.5? Is it possible to upgrade to v3.2.5?
 - What breaks when you upgrade your NLTK? 
 - Which specific functions/features are you using NLTK for?

**Comment by alvations** [comment]
Resolved in https://github.com/nltk/nltk/issues/1880#issuecomment-356837823 with `https://github.com/user/repository/archive/2.0.5a.zip`.

Closing this since we resolved the `http` -> `https`. 

Please reopen if there's further issues on this.
