### ISSUE TITLE
CFG.fromstring cannot handle epsilons

### ISSUE THREAD

**Issue by DavidNemeskey** [nltk/nltk#1890]
There are times when one wants to include an empty terminal, such as:
```
S -> A B
A -> 'a'
B -> 'b' | ''
```

However, when trying to read it via `CFG.fromstring`, I get
```
ERROR:root:An unexpected error occurred while tokenizing input
```

Interestingly, `Tree` has no problems with empty terminals:
```Python
tree = Tree('S', [
    Tree('A', ['a']),
    Tree('B', [''])
])
tree.pos()
```
prints
```Python
[('a', 'A'), ('', 'B')]
```

**Comment by stevenbird** [comment]
I agree, it should handle epsilons!

**Comment by martinbroadhurst** [comment]
An empty terminal is not the same as an empty right-hand side, though, and if you implement epsilon rules this way it will have all sorts of counter-intuitive consequences. For example, if you generate from your grammar, you will get the two sentences ``['a', 'b']`` and ``['a', '']`` (*not*  ``['a']``), and similarly if you try to parse ``['a']`` (or ``'a'.split()``) it will fail because the empty terminal is required.

The correct way to implement epsilon rules is with an empty right-hand side, but I would imagine this would require changes to all of the parsers, as handling epsilon rules is tricky.
