### ISSUE TITLE
Why does ntlk.tokenize.wordpunct_tokenize not split on `_`

### ISSUE THREAD

**Issue by sara-02** [nltk/nltk#1900]
I am using `nltk.tokenize.wordpunct_tokenize`, but do not see the string containg `_` being split up. 
Test Code
```
from nltk.tokenize import wordpunct_tokenize
wordpunct_tokenize("Hello_World")
```
Current Output: `['Hello_world']`
Expected_output: `['Hello', '_', 'World']`
Am I missing something?

**Comment by alvations** [comment]
Which version of NLTK are you using? 

There's no problem on v3.2.5, `['Hello_World']` is the expected output.

```python
>>> import nltk
>>> nltk.__version__
'3.2.5'

>>> from nltk.tokenize import wordpunct_tokenize
>>> wordpunct_tokenize("Hello_World")
['Hello_World']
```

----

If we trace back the code of `wordpunct_tokenize`

From https://github.com/nltk/nltk/blob/develop/nltk/tokenize/__init__.py#L69, it points to   https://github.com/nltk/nltk/blob/develop/nltk/tokenize/regexp.py#L199 which points to the `WordPunctTokenizer` object at https://github.com/nltk/nltk/blob/develop/nltk/tokenize/regexp.py#L171

If we look at the [#L183](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/regexp.py#L183) regex carefully:


```python
 RegexpTokenizer.__init__(self, r'\w+|[^\w\s]+')
```

The regex there checks out to be okay: https://regex101.com/r/KJQenr/1 ; `\w+` matches any word character (equal to `[a-zA-Z0-9_]`), so we see that the `_` is included. 


To exclude the underscore, use `[^\W_]` instead of `\w` (see https://regex101.com/r/KJQenr/2): 

```python
>>> from nltk.tokenize import RegexpTokenizer
>>> rt = RegexpTokenizer(r'[^\W_]+|[^\W_\s]+')
>>> rt.tokenize('This is a foo_bar sentence. #$^&*@hello_world.123')
['This', 'is', 'a', 'foo', 'bar', 'sentence', 'hello', 'world', '123']
```

**Comment by sara-02** [comment]
@alvations I am using version `3.2.2`
Also, if you look at the code you pasted above the split is actually not happening.

**Comment by alvations** [comment]
The expected behavior is to treat underscore `_` as valid `\w+` character. Please see the extended explanation above.

**Comment by sara-02** [comment]
Thanks.
