### ISSUE TITLE
Function to access the Synset object using sense key

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1934]
I might have missed it but is there a function to access the `Synset` object from the NLTK wordnet interface from the [sense key](https://wordnet.princeton.edu/wordnet/man/senseidx.5WN.html)?

If there isn't could we expose a function that can achieve that in `nltk.corpus.wordnet`? E.g. https://stackoverflow.com/questions/48170666/how-to-get-the-gloss-given-sense-key-using-nltk-wordnet/ 

Ideally, it would be good to have functionalities to access `Synset` objects using:

 1. `offset-pos`, e.g. `1433493-a` -> `Synset('long.a.02')`
 2. `sense_key`, e.g. `long%3:00:02::` ->  `Synset('long.a.02')`

Currently, we have the `synset_from_pos_and_offset()` for (1). 

There's another function (`_synset_from_pos_and_line `) that reads the following line to return `Synset('long.a.02')`:

```
01433493 00 a 01 long 1 016 = 05129201 n 0000 + 05133287 n 0101 ! 01436003 a 0101 & 01434007 a 0000 & 01434218 a 0000 & 01434530 a 0000 & 01434717 a 0000 & 01434841 a 0000 & 01434966 a 0000 & 01435060 a 0000 & 01435189 a 0000 & 01435290 a 0000 & 01435399 a 0000 & 01435507 a 0000 & 01435675 a 0000 & 01435891 a 0000 | primarily spatial sense; of relatively great or greater than average spatial extension or extension as specified; "a long road"; "a long distance"; "contained many long words"; "ten miles long" 
``` 

but it's not the sense key.

**Comment by craaaa** [comment]
I'd like to work on this!

**Comment by alvations** [comment]
@craaaa Sorry for the late reply, was away for a while. 

Feel free to work on it and create a PR afterwards. 
P/S: Don't worry about breaking anything, there'll be checks and reviews before we merge the code.

**Comment by craaaa** [comment]
Implemented the function suggested in the stackoverflow, but it didn't seem to map to the correct senses -- for instance, `synset_from_sense_key('afraid%3:00:00::')` returned `afraid.a.04` instead of `afraid.a.01`. This problem extends to other POS as well. (Sense keys were obtained from [Wordnet's online interface](http://wordnetweb.princeton.edu/perl/webwn?s=afraid&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=1&o3=&o4=&h=000000000000))

Instead, using the method shown in the [SemCor documentation](http://moin.delph-in.net/SemCor) appears to map correctly -- there is currently a `lemma_from_key(key)` function that seems to take in something similar to a sense key. However, `lemma_from key(key)` doesn't support adjective satellites (e.g. `afraid%3:00:02:concerned:00`). I can definitely implement a wrapper around `lemma_from_key(key)` to fix this and return a `Synset`.

**Comment by Izorar** [comment]
@craaaa. I think there is still an issue with adjective satellites. I tried to use the synset_from_sense_key function and here is the error:
<p>
  File "/home/izorar/anaconda3/lib/python3.7/site-packages/nltk/corpus/reader/wordnet.py", line 1356, in synset
    raise WordNetError(message % lemma)

WordNetError: adjective satellite requested but only plain adjective found for lemma 'first'
</p>
Any idea on how to fix the error?
