### ISSUE TITLE
tweet tokenizer has US-specific phone number regex

### ISSUE THREAD

**Issue by drevicko** [nltk/nltk#1953]
The [phone number regex](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/casual.py#L125) is ONLY for united states phone numbers. Standard international numbers are not recognised at all.

Further, this regex is (causing problems with long numbers in general)[https://github.com/nltk/nltk/issues/1799].

Creating a regex capable of recognising ALL phone numbers (including other countries and other international prefixes) will likely be problematic, as it will likely match other numbers not intended as phone numbers. 

An immediate band-aid remedy would be to add an option to not process phone numbers and a caveat that it is only for US numbers. 

A more serious attempt could be to (optionally!) use [libphonenumber](https://github.com/googlei18n/libphonenumber) or something similar. Having a relatively ad-hoc regex specific to just one country seems a bit inappropriate here (only [around 1/5 of Twitter users are in the US](https://www.statista.com/statistics/274564/monthly-active-twitter-users-in-the-united-states/)).

**Comment by alvations** [comment]
Instead of attempting to capture every possible phone number, if there's a way to "enable/disable" a regex when initializing the `TweetTokenizer` that'll be more helpful, e.g. `TweetTokenzier(use_phone_regex=False)` should disable the phone regex. 

But this is a little more tricky to separate it out from the other list of regexes in https://github.com/nltk/nltk/blob/develop/nltk/tokenize/casual.py#L125

**Comment by tomaarsen** [comment]
Closed via the suggestion of @alvations in #2798. Thank you for raising the issue,
