### ISSUE TITLE
WordNet: Synsets' relations are absent from their corresponding lemmas

### ISSUE THREAD

**Issue by marcevrard** [nltk/nltk#1970]
In WordNet, it seems to me that the relations relevant for a given synset should be relevant for its corresponding lemmas as well. In the `nltk` implementation, all semantic relations implemented as methods for synsets (e.g., `hypernyms()`) are indeed also available for lemmas. Though for example, the lemma `trick.n.01.trick` `hypernyms` method does not return anything, while its synset's does.

Using the lemma method:
```python
>>> trick_lemma = wnt.get_synset('trick.n.01').lemmas()[0]
>>> print(trick_lemma.hypernyms())
[]
```
Using the the synset method instead:
```python
>>> print(trick_lemma.synset().hypernyms())
[Synset('device.n.03')]
>>> print(trick_lemma.synset().hypernyms()[0].lemmas())
[Lemma('device.n.03.device'), Lemma('device.n.03.gimmick'), Lemma('device.n.03.twist')]
```

Expected behavior of the lemma method:
```python
>>> print(trick_lemma.hypernyms())
[Lemma('device.n.03.device'), Lemma('device.n.03.gimmick'), Lemma('device.n.03.twist')]
```

Versions:
```
nltk 3.2.5
Python 3.6.4
Ubuntu 17.10
```

**Comment by ekaf** [comment]
The docstring for the Lemma class still claims that lemmas can directly return the relations defined for their synset. However, this is not true in practice, and such calls only return an empty list.

It is true that anything that holds for a synset also holds for the lemmas included in that synset, so a user is free to interpret the synset relations as also holding for lemmas. However, since this can be achieved by simply obtaining the synset of the input lemma, it would be an unnecessary extension, which a generic WordNet interface does not need to include.

In the WordNet database, synset relations are not defined at the lemma level, and there would not be any practical advantage in blurring the distinction between synset and lemma relations.

So, in my opinion, the current practice is the most correct one. Then, the docstring of the Lemma class should probably be edited, to reflect that synset relations are not directly available at the lemma level, but need an intermediate call to synset().

**Comment by ekaf** [comment]
On the other hand, most people probably think of hypernymy as a relation between words, rather than synsets. WordNet could be easier to use, and more widely accepted, if less knowledge of its peculiarities was required. So today I'm leaning more toward @marcevrard's viewpoint, and think that it could be advantageous to make synset relations directly accessible from the lemmas.

**Comment by stevenbird** [comment]
Sorry for not responding much earlier. I think the logic here is for programmers to be clear about the difference between lemmas and synsets. Lemmas are forms. Synsets are concepts. I would prefer us to fix the documentation.

**Comment by ekaf** [comment]
Anyway, just editing the docstring would not be sufficient for fixing this issue. Currently, all the relations are defined at the level of the WordnetObject class, so the Lemma class inherits definitions for the hypernyms, hyponyms, etc..., and always returns an empty list for each call of these functions, [as marcevrard notes](https://github.com/nltk/nltk/issues/1970#issue-301709671).
Stricter adherence to WordNet's distinction between synset vs. lemma relations would involve moving the definitions of all the synset relations, from the WordnetObject class, to the Synset class.
Then, instead of returning an empty list, calling these functions on a lemma would raise an error:

> AttributeError: 'Lemma' object has no attribute 'hypernyms'

On the other, according to this [Wikipedia page ](https://en.wikipedia.org/wiki/Hypernymy_and_hyponymy), everybody else considers hyponymy to be a relation between words or terms:
> In linguistics, semantics, general semantics, and ontologies, hyponymy (from Ancient Greek ὑπό (hupó) 'under', and ὄνυμα (ónuma) 'name') shows the relationship between a generic term (hypernym) and a specific instance of it (hyponym). A hyponym is a word or phrase whose semantic field is more specific than its hypernym.

So we cannot expect that programmers would want to learn  a too strict interpretation of this distinction between synset and lemma relationships.

Furthermore, we need to adress the special case of the hybrid relations, which have both synset and lemma occurences in WordNet, but are not yet properly supported by NLTK's _wordnet.py_ module.

**Comment by ekaf** [comment]
Sorry @marcevrard, but the consensus is against this proposal.
