### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by nikitxskv** [nltk/nltk#2168]
Hi!

Could you explain the necessity of this code line?
https://github.com/nltk/nltk/blob/develop/nltk/internals.py#L30

**Comment by purificant** [comment]
Hi @nikitxskv,

[`__file__`](https://docs.python.org/3/reference/import.html#__file__) is the pathname of the file from which the module was loaded, if it was loaded from a file. The attribute is optional and may not be set for some modules.

I think that line of code exists for historical reasons, previously it was needed for [this code ](https://github.com/nltk/nltk/commit/701468b184400511bbefc8053629e975f9d89bc1#diff-6d3d9c7d1794a239ab676fc6fce3131fL168) which has since been removed.

I believe, it's one of several leftover import statements that are no longer needed and can be removed.

**Comment by nikitxskv** [comment]
Thank you for response!

It will be great if you remove this line. Now I have to remove this line manually because I need to know the file from which the module was loaded.

**Comment by purificant** [comment]
Out of curiosity, why do you need to know the file?

**Comment by nikitxskv** [comment]
I wrote script, that uses your package. And I want to run this script on other machine. To do that I need to create archive with this script and all used modules. Used modules and its paths I get from `sys.modules`. And then I ran into the problem that `internals.py` path equals to `__init__.py` path:)

**Comment by purificant** [comment]
Thanks for explaining @nikitxskv, interesting use case. I proposed the removal of this line in https://github.com/nltk/nltk/pull/2172

**Comment by nikitxskv** [comment]
Thank you!

**Comment by stevenbird** [comment]
Thanks @nikitxskv, @purificant
