### ISSUE TITLE
Wordnet similarity quirky when only one synsets needs root

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#2278]
Sometimes when only one synset needs root, the similarity between the synsets are not commutative:

```python
from nltk.corpus import wordnet as nltk_wn

ncat = nltk_wn.synset('cat.n.01')
nbuy = nltk_wn.synset('buy.v.01')

print(nltk_wn.path_similarity(nbuy, ncat), nltk_wn.wup_similarity(nbuy, ncat))
print(nltk_wn.path_similarity(ncat, nbuy), nltk_wn.wup_similarity(ncat, nbuy))
```

[out]:

```
0.058823529411764705 0.1111111111111111
None None
```

Details on https://stackoverflow.com/q/20075335/610569

**Comment by djinn-anthrope** [comment]
@alvations, I've seen this "quirk" myself, and as the StackOverflow answer suggests, there are two ways of resolving this:

1. If there is only one word in a pair that contains a root, simulate a root by default, unless specified otherwise.
2. If there is only one word in a pair that contains a root, find the similarities from the one with the simulated root (one that returns a value), and modify the similarity functions to provide that as an output by default.

Is my interpretation of the possible solution correct? Are there any other methods of resolving this?
