### ISSUE TITLE
grammar.CFG.is_chomsky_normal_form returns True even if start symbol is produced by some production

### ISSUE THREAD

**Issue by jacobdweightman** [nltk/nltk#2456]
In a Chomsky normal form grammar, the start symbol must not occur on the right side of a production by definition. However, the current implementation does not check for this. As a result, NLTK indicates that the grammar `S -> S S` is in normal form, even though it does not comply with the definition.
```
>>> import nltk.grammar
>>> G = nltk.grammar.CFG.fromstring("S -> S S")
>>> G.is_chomsky_normal_form()
True
```

**Comment by svinkapeppa** [comment]
Hi, @jacobdweightman!

There is an alternative definition of a Chomsky normal form - grammar is considered to be in a Chomsky normal form, if all of its production rules are of the form:
* _A_ &rarr; _B_ _C_
* _A_ &rarr; _a_

Here _a_ is a terminal symbol and both _B_ and _C_ can be start symbol.

It's also worth mentioning that according to this definition only those context-free grammars which do not generate the empty string can be transformed into Chomsky normal form.

If we dive into the code we could see the following:

```
    def is_nonempty(self):
        """
        Return True if there are no empty productions.
        """
        return self._min_len > 0

    def is_flexible_chomsky_normal_form(self):
        """
        Return True if all productions are of the forms
        A -> B C, A -> B, or A -> "s".
        """
        return self.is_nonempty() and self.is_nonlexical() and self.is_binarised()

    def is_chomsky_normal_form(self):
        """
        Return True if the grammar is of Chomsky Normal Form, i.e. all productions
        are of the form A -> B C, or A -> "s".
        """
        return self.is_flexible_chomsky_normal_form() and self._all_unary_are_lexical

    def chomsky_normal_form(self, new_token_padding="@$@", flexible=False):
        """
        Returns a new Grammer that is in chomsky normal
        :param: new_token_padding
            Customise new rule formation during binarisation
        """
        if self.is_chomsky_normal_form():
            return self
        if self.productions(empty=True):
            raise ValueError(
                ("Grammar has Empty rules. " "Cannot deal with them at the moment")
            )
        . . .
```

So from these lines we can conclude that the developers of the NLTK considered the alternative definition of the Chomsky normal form (because empty rules are forbidden + rules in `is_chomsky_normal_form()` are the same as in the alternative definition).

So that's why the correct answer for the grammar `S -> S S` is `True`.

**Comment by tomaarsen** [comment]
I believe this has been answered clearly!
