### ISSUE TITLE
Install NTLK did not work on clean Anaconda python 3.7

### ISSUE THREAD

**Issue by orbennatan** [nltk/nltk#2492]
To reproduce
On a Windows 10 machine uninstall old versions of Anaconda and Pycharm. Delete by hand everything python or anaconda I could find (including the registry).
Install Anaconda
pip install ntlk.
You get an error "could not find version to satisfy the requirement". It doesn't say version for what.
What fixes the problem is
pip install ntlk=3.3
Which means I can't use the newest version of NTLK.
This used to work before. I noticed there is a new version now.

**Comment by alvations** [comment]
The stable releases of anaconda is https://anaconda.org/anaconda/nltk , it should be 3.4.5 on Windows. The folks at anaconda should have already tested it across version OS to make sure that the packaged version they are shipping works =)

----

First suspicion is that that you're not using the `pip` as how anaconda has packaged the library to be used with anaconda. Maybe, to resolve the issue, try `conda install nltk` since you're already using Anaconda as your environment controller/manager.

----

To really replicate the error you're having, we would require the following. 
 
 - Could you post the full error stacktrace after you've tried `pip install nltk`? 

 - Also, how are you doing `pip install nltk` in Anaconda? Are you using the Anaconda navigator, then creating a new environment, then using the terminal inside the environment to call `pip`? Could you post some screenshots?

 - Which version is `pip install nltk` trying to install? Before doing that, did you try updating your environment's package index, i.e. `pip install -U pip`?


---- 

P/S: If you haven't, I would strongly encourage you to read too:

 - https://docs.python-guide.org/starting/install3/win/#install3-windows
 - https://learning.oreilly.com/library/view/introducing-python-2nd/9781492051374/app02.html
 - https://docs.python-guide.org/dev/virtualenvs/#virtualenvironments-ref

Maybe that'll help you to resolve your issue.

**Comment by orbennatan** [comment]
Thank you so much.In the meantime I decided to dich Anaconda because of Tensorflow problems and will now work on pycharm creating my own environments with it.Will check the NTLK with this configuration later

**Comment by orbennatan** [comment]
Once I left Anaconda and start managing my environments with pycharm the problem disappeared.

**Comment by tomaarsen** [comment]
I believe the issue is related to how you type **NTLK**, instead of **NLTK**. 
Please use `pip install nltk` if you wish to install the Natural Language Toolkit.
