### ISSUE TITLE
TextTiling cutoff_policy (HC is not set properly) 

### ISSUE THREAD

**Issue by mohannad57** [nltk/nltk#2497]
The TextTiling code Line 297 - 300 shows:
297:        if self.cutoff_policy == LC:
298:            cutoff = avg - stdev / 2.0
299:        else:
300:            cutoff = avg - stdev / 2.0

Line 300 should be
300:            cutoff = avg + stdev / 2.0

**Comment by tomaarsen** [comment]
I don't believe that this is correct. As per Hearst, Marti A.. “Text Tiling: Segmenting Text into Multi-paragraph Subtopic Passages.” Comput. Linguistics 23 (1997): 33-64.:

> A higher precision but lower recall can be found by setting the
limit to be depth scores exceeding avg - stdev/2 (the conservative measure, HC) instead of
avg - stdev [which is LC].

So, HC should be `avg - stdev / 2.0`, while LC should be `avg - stdev`, as implemented in #2936:
https://github.com/nltk/nltk/blob/b35b4c6b027a017fa65c29c43771701533d5dc63/nltk/tokenize/texttiling.py#L294-L297
