### ISSUE TITLE
nltk bleu_score return 0

### ISSUE THREAD

**Issue by nimning** [nltk/nltk#2498]
I am using nltk's bleu_score package to compute blue score. However, I always got zero blue score for any sentence. Even if I use the cases mentioned in this post, I still got zero bleu score.
https://stackoverflow.com/questions/40542523/nltk-corpus-level-bleu-vs-sentence-level-bleu-score 

I run scripts on a fresh installed anaconda. Python 3.6 reproduce the same error.

```
>>> import sys
>>> import nltk
>>> print(sys.version)
3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
>>> print(nltk.__version__)
3.4.5
>>> hypothesis = ['This', 'is', 'cat']
>>> reference = ['This', 'is', 'a', 'cat']
>>> references = [reference]
>>> list_of_references = [references]
>>> list_of_hypotheses = [hypothesis]
>>> nltk.translate.bleu_score.corpus_bleu(list_of_references, list_of_hypotheses)

C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\nltk\translate\bleu_score.py:523: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\nltk\translate\bleu_score.py:523: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
**8.987727354491445e-155**
```

**Comment by karinseve** [comment]
Hi did you manage to solve this?

**Comment by tomaarsen** [comment]
Apologies for the late response. 
I would advise having another look at your output, as it throws two warnings that explain exactly what is happening:
```
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
```
Because there are no 3-grams that overlap in your two sentences of 
```python
hypothesis = ['This', 'is', 'cat']
reference = ['This', 'is', 'a', 'cat']
```
Then the BLEU score evaluates to 0.

The same warning is given with 4-grams. 

---

The solution is given, too. You can use a lower n-gram order like so:
```python
nltk.translate.bleu_score.corpus_bleu(
    list_of_references, 
    list_of_hypotheses, 
    weights=(0.5, 0.5)
)
```
This uses an n-gram of order 2 and lower. Using this outputs: `0.5066641486392106` for your sample reference and hypothesis.

Alternatively, a `SmoothingFunction()` can help too, for example `SmoothingFunction().method1`, `SmoothingFunction().method2`, ..., `SmoothingFunction().method7`.

I'll close this now, as this issue doesn't give me the indication that there is an issue with the BLEU score. Feel free to reopen this if you feel that there is indeed an issue.
