### ISSUE TITLE
nltk.lm Language Model: Perplexity performs unexpectedly

### ISSUE THREAD

**Issue by CaoHoangTung** [nltk/nltk#2548]
The perplexity performs weirdly, being higher when evaluating with a large vocabulary.

Reproduce at [ https://ProxyHT@bitbucket.org/ProxyHT/language-model.git](https://ProxyHT@bitbucket.org/ProxyHT/language-model.git)

In _ngrams.py_, from line 15-21, I have configuration for training/validating/testing corpus. With the larger training corpus (data/train-80.txt), the perplexity evaluated on the test corpus is higher than the smaller training corpus (data/train-16.txt). The same thing happens with even larger files.

**Comment by iliakur** [comment]
@CaoHoangTung thanks for linking to your data, it helped a lot.

In your case the problem is simply that you do not have sufficient training data. You are trying to build a statistical model that can handle a human language based on what I guess is 16 and 80 sentences. Then you are testing this model on 2000 sentences. Usually the training/test split is in the other direction: you have to show the model hundreds of thousands of sentences and then evaluate it on a fraction of that amount.

Given the quantities of data that you're using, I'd say your results make perfect sense. Your training texts are so small that for each of them the ratio of the size of the extracted vocabulary to the size of the text is very high. In essence we can treat your texts as vocabularies. And the larger the vocabulary, the higher the entropy for it and consequently the higher the perplexity.

This is perhaps how you could justify to yourself the need for more data: first you need to reach a point where your vocabulary size approximates that of your target language. You will have some natural entropy at this point for the vocabulary of this size. Then training the model consists of showing it enough data that it can improve on this entropy value. And for that your training data needs to be much much bigger than your vocabulary.

I hope this helps, feel free to ask if something isn't clear.

**Comment by stevenbird** [comment]
Thanks @iliakur
