### ISSUE TITLE
WordNetLemmatizer replaces "does" with "doe"

### ISSUE THREAD

**Issue by ilya-palachev** [nltk/nltk#2550]
Hello,
I'm using `WordNetLemmatizer` to make the word lemmatization. My corpus contains a big number of occurrences of word "does". However, `WordNetLemmatizer` replaces all of them with "doe". I'm using it as follows:
```
from nltk.stem.wordnet import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatized_comments = [[lemmatizer.lemmatize(w) for w in c] for c in tqdm(prepared_comments)]
```
where `prepared_comments` is a list of tokenized word sequences. Am I using the `WordNetLemmatizer` wrong, or is it a bug of `WordNetLemmatizer`?

**Comment by ab-10** [comment]
Hi @ilya-palachev, you should provide `WordNetLemmatizer` with POS tag for each token, otherwise, as you have noticed, it will guess. For _does_ it will look like this:

```
lemmatizer.lemmatize("does", pos="v")
>>> 'do'
```

Note that pos tagset differs from Penn and Universal, so you will need to do some mapping between them (please see: https://stackoverflow.com/a/15590384/6282058 and http://www.nltk.org/_modules/nltk/corpus/reader/wordnet.html).

**Comment by ilya-palachev** [comment]
Thanks for the clarification!
