### ISSUE TITLE
TweetTokenizer add new emoticons characters

### ISSUE THREAD

**Issue by danielafe7-usp** [nltk/nltk#2578]
Hello! There is any way to add new characters to the emoticons tokenization ?
For example:
from nltk.tokenize import TweetTokenizer
tknzr = TweetTokenizer()
s1 = "This is a cooool :-*"
tknzr.tokenize(s1)

It gives as result:
['This', 'is', 'a', 'cooool', ':', '-', '*']

But I need to preserve these specific emotion ":-*".
Thanks for advance!

**Comment by tomaarsen** [comment]
@danielafe7-usp 
No, this is not (conveniently) possible.
TweetTokenizer detects emoticons using a specific regular expression:
https://github.com/nltk/nltk/blob/54221dec0bae2642d1642d182d8a381c88b86bd0/nltk/tokenize/casual.py#L57-L70

This regex will not match `:-*` (because `*` is not considered a valid option for a mouth), and cannot be extended in runtime by supplying some list of specific emoticons to also search for. However, this *could* be implemented as a feature. I might look into this if I have some spare time.

**Comment by ajdapretnar** [comment]
So TweetTokenizer will not be able to recognize valid Unicode emojis?
Because currently, what I get from this `'🇸🇮🤝🇺🇦'` is this `'🇸', '🇮', '🤝', '🇺', '🇦'`. Is there an option to add support from Unicode emojis?

**Comment by tomaarsen** [comment]
@ajdapretnar  I feel like this is a bit of a complex situation. To give some context:
```python
>>> string = "🇸🇮🤝🇺🇦" 
>>> len(string)
5
>>> string[0]
'🇸'
```
Long story short, flags are combinations of regional indicator symbols. When converted into a string, Python is the one unable to recognize that 🇸🇮 is a (single) valid Unicode emoji, but it instead sees it as two separate regional indicator symbols. TweetTokenizer only rarely merges Unicode characters together: Only with Zero-Width-Joiners and Skin tone modifiers I believe (See #2843). 

However, in that context, the Zero-Width-Joiners and Skin tone modifiers don't have other uses, but the regional indicator do have other users. If someone uses them to spell something out, grouping them together might not necessarily be the desired behaviour. (Although I could be convinced if someone is able to add a concise and simple implementation to [this](https://github.com/nltk/nltk/blob/b0e85694107992e00a2f9fb48e6410c50fe1f1f6/nltk/tokenize/casual.py#L148) regex)

**Comment by ajdapretnar** [comment]
@tomaarsen Thank you for the reply. I see what's the problem. If it is a difficult/tricky fix, don't bother. Just something I noticed and thought it might be nice to solve. But I agree that there are two use cases that are at odds here.
