### ISSUE TITLE
PunktTokenizer: Inconsistency in two snippets, different languages

### ISSUE THREAD

**Issue by jerinphilip** [nltk/nltk#2586]
I am trying to work with the following example snippet [I found on StackOverflow](https://stackoverflow.com/questions/29746635/nltk-sentence-tokenizer-custom-sentence-starters)

**Example 1: Works**
```py
from nltk.tokenize.punkt import PunktSentenceTokenizer, PunktLanguageVars

class BulletPointLangVars(PunktLanguageVars):
    sent_end_chars = ('.', '?', '!', '•')

tokenizer = PunktSentenceTokenizer(lang_vars = BulletPointLangVars())
sentences = tokenizer.tokenize(u"• I am a sentence • I am another sentence")
for sentence in sentences:
    print(sentence)
```

The above works, and provides the expected output. 
Edit: The above fails if I remove the space preceding •, after some more debugging.

Now, I'm trying to work with the same with minor modifications using a unicode full-stop corresponding to a different language. 

**Example 2: Fails**
```py

from nltk.tokenize.punkt import PunktSentenceTokenizer, PunktLanguageVars

class BulletPointLangVars(PunktLanguageVars):
    sent_end_chars = ('.', '?', '!', '\u0964')

tokenizer = PunktSentenceTokenizer(lang_vars = BulletPointLangVars())
sentences = tokenizer.tokenize(u"উপরাষ্ট্রপতি শ্রী এম ভেঙ্কাইয়া নাইডু সোমবার আই আই টি দিল্লির হীরক জয়ন্তী উদযাপনের উদ্বোধন করেছেন। অনলাইনের মাধ্যমে এই অনুষ্ঠানে কেন্দ্রীয় মানব সম্পদ উন্নয়নমন্ত্রী শ্রী রমেশ পোখরিয়াল ‘নিশাঙ্ক’  উপস্থিত ছিলেন। এই উপলক্ষ্যে উপরাষ্ট্রপতি হীরকজয়ন্তীর লোগো এবং ২০৩০-এর জন্য প্রতিষ্ঠানের লক্ষ্য ও পরিকল্পনার নথি প্রকাশ করেছেন।   অনুষ্ঠানে বক্তব্য রাখতে গিয়ে শ্রী নাইডু বলেছেন, জলবায়ু পরিবর্তন থেকে স্বাস্থ্য সমস্যা ౼ মানবজাতি আজ যে সমস্ত সমস্যার মুখোমুখি হচ্ছে, সেগুলিকে সমাধানের জন্য আইআইটি সহ অন্যান্য উচ্চ শিক্ষা প্রতিষ্ঠানের গবেষণার উপর গুরুত্ব দেওয়া উচিৎ। দেশের সমস্যাগুলির স্থিতিশীল সমাধানের ভারতীয় প্রতিষ্ঠানগুলি যখন এমন কিছু কাজ করবে, যাতে সমাজের উপর তার ইতিবাচক প্রভাব পরে, তাহলেই সেগুলি বিশ্বে সর্বশ্রেষ্ঠ প্রতিষ্ঠান হয়ে উঠতে পারবে।    সামাজিক বিভিন্ন সমস্যার সমাধান খুজতে বেসরকারি ক্ষেত্রকে,  শিক্ষাক্ষেত্রে গবেষণা ও উন্নয়নের জন্য খোলা মনে বিনিয়োগের তিনি আহ্বান জানিয়েছেন। আইআইটির ছাত্রছাত্রীদের  গ্রামীণ ভারত ও কৃষকদের নানা সমসয়ার সমাধান ছাড়াও কি করে পুষ্টিকর ও প্রোটিন সমৃদ্ধ শস্য উৎপ দন বৃদ্ধি করা যায়, শ্রী নাইডু  সেই বিষয়গুলি নিয়েও কাজ করার পরামর্শ দেন। উচ্চশিক্ষা প্রতিষ্ঠানগুলিকে এককভাবে নয়, শিল্প সংস্থাগুলির সঙ্গে জোট বেঁধে অতাধুনিক প্রযুক্তি উদ্ভাবন করতে হবে। এর ফলে দ্রুত ও ফলাফল ভিত্তিক নানা প্রকল্প বাস্তবায়নে সুবিধে হবে।   নতুন শিক্ষানীতির প্রসঙ্গে উপরাষ্ট্রপতি বলেছেন, ভারতকে আন্তর্জাতিক শিক্ষা প্রতিষ্ঠানের গন্তব্যে পরিণত করার জন্য এই নীতি সহায়ক হবে। উচ্চ শিক্ষা প্রতিষ্ঠানের মানোন্নয়নে সরকার, বিশ্ববিদ্যালয়, শিক্ষাবিদ ও বেসরকারী প্রতিষ্ঠানগুলিকে একযোগে কাজ করতে হবে।   আইআইটি দিল্লি শিল্পোদ্যোগ গড়ার কেন্দ্র হয়ে উঠছে বলে উপরাষ্ট্রপতি সন্তোষ প্রকাশ করেছেন। এই প্রসঙ্গে তিনি মানব সম্পদ উন্নয়ন মন্ত্রকের ‘উন্নত ভারত অভিযান’ কর্মসূচীতে দিল্লি আইআইটি অনুঘটকের ভূমিকা পালন করায় এই প্রতিষ্ঠানের প্রশংসা করেছেন।    শ্রী পোখরিয়াল, এই অনুষ্ঠানের উদ্বোধন করার জন্য উপরাষ্ট্রপতির প্রতি কৃতজ্ঞতা জানিয়েছেন। তিনি বলেছেন, আমাদের দেশের ছাত্রছাত্রীদের জন্য একটি আধুনিক ও উন্নত শিক্ষা ব্যবস্থা গড়ে তুলতে২০২০-র নতুন জাতীয় শিক্ষানীতি সহায়ক হবে। আইআইটি দিল্লির  গৌরবময় ৬০ বছরের উল্লেখ করে তিনি বলেছেন সারা দেশ যখন ভিড-১৯ মহামারীর বিরুদ্ধে লড়াই করছে, তখন আইআইটি দিল্লি নানাভাবে কারিগরি সহায়তা দিয়েছে, যা সময়োপযোগী ও মূল্যবান। বিগত ৫ বছরে এই শিক্ষা প্রতিষ্ঠানের শিক্ষক শিক্ষিকা ও ছাত্রছাত্রীরা ৫০০-র বেশী পেটেন্টের আবেদন করেছেন এবং তাঁদের ১০হাজারের বেশী গবেষণা পত্র বিভিন্ন আন্তর্জাতিক পত্র পত্রিকায় ছাপানো হয়েছে। ২০১৬ সালে সরকার এই প্রতিষ্ঠানকে যেখানে গবেষণার জন্য ১০০ কোটি টাকা দিয়েছিল, ২০১৯ সালে তা বেড়ে হয়েছে ৪০০ কোটি টাকা।    দিল্লি আইআইটির ডিরেক্টর অধ্যাপক ভি রামগোপাল রাও জানিয়েছেন, ২০৩০ সালের যে লক্ষ মাত্রা এই শিক্ষা প্রতিষ্ঠা  নিয়েছে, তার ফলে ছাত্রছাত্রী, প্রাক্তনী, শিক্ষক শিক্ষিকা ও কর্মীবর্গদের জীবনে ইতিবাচক প্রভাব পড়বে এবং আগামী দিনে দেশের প্রগতিতে তা সহায়ক হবে।   অনুষ্ঠানের দ্বিতীয় পর্বে অধ্যাপক দেবাঙ্খখর, অধ্যাপক এম বালাকৃষ্ণাণ বক্তব্য রাখেন। ‘আই আইটি দিল্লিঃ ৬০ বছরের উৎকর্ষতার স্মৃতিচারণা ও ভবিষ্যৎ পরিকল্পনা’ শীর্ষক এক আলোচনায় এই প্রতিষ্ঠানের প্রাক্তন ডিরেক্টর অধ্যাপক ভি এস রাজু, অধ্যাপক আর এস শিরোহী, অধ্যাপক সুরেন্দ্র প্রসাদ ও অধ্যাপক আর কে শেভগাওকর অংশ নেন।")
for sentence in sentences:
    print(sentence)

```

`\u0964` corresponds to the Devanagiri full-stop (I have tried putting the normal one as well). I am not getting similar results as example 1. What could be going wrong here?

**Comment by tomaarsen** [comment]
Hello!

#### Regarding example 1's edit:
This is the functionality for all tokens that indicate the end of the sentence, eg:
```python
from nltk.tokenize.punkt import PunktSentenceTokenizer, PunktLanguageVars

tokenizer = PunktSentenceTokenizer()
for sentence in tokenizer.tokenize(u".I am a sentence .I am another sentence"):
    print(repr(sentence))
```
outputs
```python
'.I am a sentence .I am another sentence'
```
Whether this is the desired functionality is up to debate. Perhaps it could be argued that an abbreviation cannot start with a dot, and hence a dot followed by some characters must mean a full stop followed by contents of some new sentence.

#### Regarding example 2:
Here it cannot be argued that the actual result is the desired behaviour. This is either a bug, or a feature that should be implemented, that isn't yet.
I've looked into what's preventing the sentence from splitting like you would expect it to. The root of this issue is the method `word_tokenize` of the `PunktLanguageVars` class, which tokenizes a string to split off punctuation other than periods. After splitting, each split token is checked on whether it contains a sentence break. This is done in two main ways:
* Is the split off token an element of the `sent_end_chars` tuple? If so, the token contains a sentence break.
* Does the token end with a dot? If so, the the token contains a sentence break.

However, `word_tokenize` only splits off the following punctuation: `)";}]*:@'({[`. This is *fine* for most cases, but if we specifically want to split sentences based on additional punctuation, then we need to split off this newly introduced punctuation too. Then, the first rule of checking whether there is a sentence break will correctly mark the token as a sentence break.

Without this change implemented, none of the rules detecting sentence breaks will detect that e.g. `করেছেন।` has a sentence break, even if `।` is in the `sent_end_chars` tuple.

The fix for this is elementary, we can simply modify a section of the regex to also look for all all punctuation in `sent_end_chars` other than the dot.

---

I'll open up a pull request with a fork that implements this small change.

**Comment by jerinphilip** [comment]
I tried modifying the word_tokenize regex adding unicode characters amongst those, didn't get me the required results. Probably because I didn't inspect Punkt code too much.


FYI, I'm working with the following for now:

* https://github.com/jerinphilip/sentence-tokenizers/commit/b6e9d324d6aa52f984519ddc27d8860de0e0eb30

**Comment by tomaarsen** [comment]
@jerinphilip
If I apply those modifications you linked on the develop branch of nltk, and then run the following program:
```python
# -*- coding: UTF-8 -*-
from nltk.tokenize.punkt import PunktSentenceTokenizer, PunktLanguageVars

class BengaliLangVars(PunktLanguageVars):
    sent_end_chars = ('.', '?', '!', '\u0964')

tokenizer = PunktSentenceTokenizer(lang_vars = BengaliLangVars())
text = u"উপরাষ্ট্রপতি শ্রী এম ভেঙ্কাইয়া নাইডু সোমবার আই আই টি দিল্লির হীরক জয়ন্তী উদযাপনের উদ্বোধন করেছেন। অনলাইনের মাধ্যমে এই অনুষ্ঠানে কেন্দ্রীয় মানব সম্পদ উন্নয়নমন্ত্রী শ্রী রমেশ পোখরিয়াল ‘নিশাঙ্ক’  উপস্থিত ছিলেন। এই উপলক্ষ্যে উপরাষ্ট্রপতি হীরকজয়ন্তীর লোগো এবং ২০৩০-এর জন্য প্রতিষ্ঠানের লক্ষ্য ও পরিকল্পনার নথি প্রকাশ করেছেন।"
sentences = tokenizer.tokenize(text)
for sent_i, sentence in enumerate(sentences):
    print(f"Sentence {sent_i + 1}: {repr(sentence)}")
```
Then I get the following output:
```python
Sentence 1: 'উপরাষ্ট্রপতি শ্রী এম ভেঙ্কাইয়া নাইডু সোমবার আই আই টি দিল্লির হীরক জয়ন্তী উদযাপনের উদ্বোধন করেছেন।'
Sentence 2: 'অনলাইনের মাধ্যমে এই অনুষ্ঠানে কেন্দ্রীয় মানব সম্পদ উন্নয়নমন্ত্রী শ্রী রমেশ পোখরিয়াল ‘নিশাঙ্ক’  উপস্থিত ছিলেন।'
Sentence 3: 'এই উপলক্ষ্যে উপরাষ্ট্রপতি হীরকজয়ন্তীর লোগো এবং ২০৩০-এর জন্য প্রতিষ্ঠানের লক্ষ্য ও পরিকল্পনার নথি প্রকাশ করেছেন।'
```
Which seems like the intended results.

---

Another option to get these results is to implement the changes from commit CubieDev/nltk@a000e9b9c946d1d28a7625fd29f946a8aae8e394, which is one of the commits from the pull request #2587 I created.

**Comment by jerinphilip** [comment]
I prefer your implementation if it works as it changes minimum things. I don't know much about nltk, and I'm worried my dirty-fix would create issues. I just pointed to the repo in case you'd require more test-data etc. Urdu uses the Arabic Full-stop and Hindi, Oriya etc use the same full-stop from Bengali as above.

https://github.com/jerinphilip/sentence-tokenizers/tree/master/test_data.

**Comment by jerinphilip** [comment]
PR https://github.com/nltk/nltk/pull/2587 handles this. Closing issue.
