### ISSUE TITLE
raw_freq score does not sum to 1

### ISSUE THREAD

**Issue by stevenluda** [nltk/nltk#2598]
Noticed that when calculating bigram frequency using raw_freq. The result score does not sum to 1.
Checked the source code, finding that it is using the total number of words as TOTAL for the denominator instead of total number of bigrams.

Wondering if this is a bug or it has some rationale behind it?

**Comment by iliakur** [comment]
Hi @stevenluda sorry for the delayed response. Are you talking about the `collocations` module?

**Comment by tomaarsen** [comment]
It does *not* use the total numbers of words as TOTAL for the denominator, unlike what you suggest. It does in fact use the total number of bigrams.
This is the function `raw_freq` in question:
https://github.com/nltk/nltk/blob/6c07b5e99389b47e13c5e70fa07b37ef29ea8f73/nltk/metrics/association.py#L100-L103

where
https://github.com/nltk/nltk/blob/6c07b5e99389b47e13c5e70fa07b37ef29ea8f73/nltk/metrics/association.py#L36-L43

So, `raw_freq` simply divides the first parameter in your input by the last parameter. If this produces indesirable results, it's because your input values are incorrect.

You mention bigram frequency, so I'm assuming you used `BigramAssocMeasures`, which has the following documentation:
https://github.com/nltk/nltk/blob/6c07b5e99389b47e13c5e70fa07b37ef29ea8f73/nltk/metrics/association.py#L166-L192

So, the function should be used as `bam.raw_freq(n_ii, (n_ix, n_xi), n_xx)` where `n_ii` is the number of times the bigram that is being scored occurs, and where `n_xx` is the total number of *bigrams*. `(n_ix, n_xi)` can just be discarded for `raw_freq`.
Then, `raw_freq` will compute the number of times the scored bigram occurs divided by the number of bigrams, which does produce a frequency, like intended.

- Tom Aarsen

**Comment by tomaarsen** [comment]
I believe this has been answered. I'll close it accordingly. Feel free to reopen or create a new issue if you feel like this has not been resolved.
