### ISSUE TITLE
Wrong result for word more'n in Word Tokenizer and PTB Tokenizer

### ISSUE THREAD

**Issue by nmfzone** [nltk/nltk#2607]
Let sentence: `It's more'n enough`

If I'm not mistaken, the PTB Tokenizer should result something like this:

`["It", "'s", "more", "'n", "enough"]`

But, it's not. It returns:

`["It", "'s", "more", "'", "n", "enough"]`

Since Word Tokenizer trying to implement PTB contraction, the result should be like that, right?

**PS**: Word Tokenizer contraction is `mor'n`, while original PTB contraction is `more'n`. Need clarification.

**Comment by tomaarsen** [comment]
@nmfzone 
Your PS seems correct. Both the implemented Treebank and Word Tokenizer implemented for NLTK seem to use the following contractions:
https://github.com/nltk/nltk/blob/5023d6b933ef1a5b1f25fba1d5ed11a8a43a47e4/nltk/tokenize/destructive.py#L13-L29

which, on line 25, has `mor'n` as a contraction, splitting `mor` and `'n`.
These regular expressions seem to be from http://www.cis.upenn.edu/~treebank/tokenizer.sed, as can be seen in this comment in `treebank.py`:
https://github.com/nltk/nltk/blob/5023d6b933ef1a5b1f25fba1d5ed11a8a43a47e4/nltk/tokenize/treebank.py#L14-L16

This link seems to be faulty. Likely due to a redesign of the website. However, I did manage to track down the actual files using the website's search functions. Two of the links I found are (Note, they are FTP downloads):
ftp://ftp.cis.upenn.edu/pub/treebank/public_html/tokenization.html
ftp://ftp.cis.upenn.edu/pub/treebank/public_html/tokenizer.sed

I scrolled through the `tokenizer.sed`, and the relevant sections seems to be this:
```sed
s= \([Cc]\)annot = \1an not =g
s= \([Dd]\)'ye = \1' ye =g
s= \([Gg]\)imme = \1im me =g
s= \([Gg]\)onna = \1on na =g
s= \([Gg]\)otta = \1ot ta =g
s= \([Ll]\)emme = \1em me =g
s= \([Mm]\)ore'n = \1ore 'n =g
s= '\([Tt]\)is = '\1 is =g
s= '\([Tt]\)was = '\1 was =g
s= \([Ww]\)anna = \1an na =g
# s= \([Ww]\)haddya = \1ha dd ya =g
# s= \([Ww]\)hatcha = \1ha t cha =g
``` 
The uncommented lines seem to be like `CONTRACTIONS4` in `MacIntyreContractions`, while the `it` and `was` options seem to match `CONTRACTIONS3`. All the other lines match `CONTRACTIONS2`. However, here we can indeed see that MacIntyre wrote the following:
```sed
s= \([Mm]\)ore'n = \1ore 'n =g
```
Which seems to mean that Line 25 in the `MacIntyreContractions` should indeed be
```python
r"(?i)\b(more)(?#X)('n)\b",
            ^
```
instead of 
```python
r"(?i)\b(mor)(?#X)('n)\b",
```
(Note, the ^ is to indicate the changes between the two.)

Edit: 
The NLTKWordTokenizer had some extra issue with some regexes turning `more'n` into `more ' n` before the contraction regex could even be applied. I changed this up, and fixed the contraction regex in a PR I created. Thanks for letting me know about this issue!

**Comment by stevenbird** [comment]
Thanks @nmfzone
