### ISSUE TITLE
Pos-tag returns strange output for 'as'

### ISSUE THREAD

**Issue by mina1987** [nltk/nltk#2648]
Any insights on how to handle 'as'?
Inltk.pos_tag('as')
[('a', DT), ('s','NN')

I also tried to check wordnet synsets, most of the synsets were chemical terms and only the last one was my desired synset: Synset('equally.r.01) r , any insights on how i can isolate this specific meaning and use it for pos_tag, etc?

**Comment by 12mohaned** [comment]
I believe there is a problem with the pos_tagging classifier, I tried the same sentence on textblob and it worked.
`from textblob import TextBlob`
 `text = ('as')`
 `blob = TextBlob(text)`
 `blob.tags` 

the output is 
[('as', 'IN')]

Updated answer : 
Actually, it does work, you have to tokenize the sentence before tagging it as the parser does not tokenize it for you before parsing. 

`from nltk.tokenize import word_tokenize`
 `nltk.pos_tag(word_tokenize(text))`
 
the output 
[('as', 'IN'), ('you', 'PRP'), ('know', 'VBP'), ('i', 'JJ'), ('love', 'VBP'), ('coffee', 'NN')]

**Comment by goodmami** [comment]
@12mohaned's updated answer is correct, but I'll provide some context.

[nltk.pos_tag()](https://www.nltk.org/api/nltk.tag.html#nltk.tag.pos_tag) expects a list of tokens:

```python
>>> nltk.pos_tag(['as'])
[('as', 'IN')]
```

Since a list of tokens is a iterable of strings, and a single string acts like an iterable of 1-character substrings, they have the same "shape" as far as the function is concerned. That is, the function proceeds as if you'd passed the token list `['a', 's']`. Since passing a string as the argument to `pos_tag()` is a common mistake and not likely to have a valid use-case, the NLTK might be improved by raising a `TypeError` or at least warning users when a string is passed.
