### ISSUE TITLE
Wrong default value in aline.py

### ISSUE THREAD

**Issue by danmysak** [nltk/nltk#2708]
I believe the value of `C_skip` in https://github.com/nltk/nltk/blob/develop/nltk/metrics/aline.py#L51 should be negative. In particular, the value in the original paper seems to be `-10`, not `10` (see https://webdocs.cs.ualberta.ca/~kondrak/papers/thesis.pdf, p. 54).

**Comment by DanielLoney** [comment]
Opened pull request #2712

**Comment by DanielLoney** [comment]
Not sure why but simply changing C_skip to -10 causes issues.
\>\>\> aline.align('tuwθ', 'dentis')
returns
[[('t', 't'), ('u', 'i'), ('w', '-'), ('θ', 's')]]  # Unmatched phonemes of "dentis" should still appear
instead of the expected
[[('t', 'd'), ('u', 'e'), ('w', '-'), ('-', 'n'), ('-', 't'), ('-', 'i'), ('θ', 's')]]

**Comment by DanielLoney** [comment]
> Not sure why but simply changing C_skip to -10 causes issues.
> \>\>\> aline.align('tuwθ', 'dentis')
> returns
> [[('t', 't'), ('u', 'i'), ('w', '-'), ('θ', 's')]] # Unmatched phonemes of "dentis" should still appear
> instead of the expected
> [[('t', 'd'), ('u', 'e'), ('w', '-'), ('-', 'n'), ('-', 't'), ('-', 'i'), ('θ', 's')]]

The unit test after #2713 still does not reflect the correct output. Opened #2714 to reflect this issue.
