### ISSUE TITLE
Error when using nltk.stem.arlstem2 module

### ISSUE THREAD

**Issue by LMech** [nltk/nltk#2718]
I was trying to use the stemming function in arlstem2 object and always found an error that there is no object called adject but, i tried to fix adject and replaced it with adjective in the source code it worked perfectly.

I just wanted to mention that it works for me :)

![SharedScreenshot](https://user-images.githubusercontent.com/64975785/119942357-02522380-bf92-11eb-98ee-0fbfe7d8d5a1.jpg)

**Comment by tomaarsen** [comment]
@LMech 
Hello! Thank you for raising this issue. 

I've created a Pull Request with the change you described in #2719. In order to prevent this from popping back up in the future, I added 2 very simple tests for `ARLSTem` and `ARLSTem2` over here: https://github.com/nltk/nltk/pull/2719/files#diff-614664a891b109ea50dfd368054111e15534db03a1192659a41d9f676786d1fc
However, I don't actually know Arabic. I'm assuming that you do - based on that you were using it - so perhaps you could check whether these tests make sense. It doesn't really matter much though - as the tests mostly focus on whether the stemmer actually works without throwing an Exception.

**Comment by LMech** [comment]
@tomaarsen 
Thanks for your response.

I think you did a great job as far as i can tell and yes your tests makes 100% sense for me.
