### ISSUE TITLE
"Smart" issue

### ISSUE THREAD

**Issue by TheBugYouCantFix** [nltk/nltk#2731]
Whenever I write smart/smarter/smartest, nltk always defines it as a noun

Examples:

```py
import nltk


def part_of_speech(word):
    token = nltk.word_tokenize(word)
    pos = nltk.pos_tag(token)
    return pos


print(part_of_speech('smart'))  # Output: [('smart', 'NN')]
print(part_of_speech('smarter'))  # Output: [('smarter', 'NN')]
print(part_of_speech('smartest'))  # Output: [('smartest', 'NN')]
```

**Comment by stevenbird** [comment]
What happens when you put the word in sentential context?

**Comment by tomaarsen** [comment]
@stevenbird 

```python
import nltk

def part_of_speech(word):
    token = nltk.word_tokenize(word)
    pos = nltk.pos_tag(token)
    return pos

print(part_of_speech('smart'))
print(part_of_speech('smarter'))
print(part_of_speech('smartest'))

print(part_of_speech('I am smart'))
print(part_of_speech('I am smarter'))
print(part_of_speech('I am smartest'))

print(part_of_speech('smart person'))
print(part_of_speech('smarter person'))
print(part_of_speech('smartest person'))

print(part_of_speech('work'))
print(part_of_speech('beautiful'))
print(part_of_speech('sweeter'))
print(part_of_speech('nicer'))
print(part_of_speech('darker'))

print(part_of_speech('beautifully'))
```

Outputs

```python
[('smart', 'NN')]
[('smarter', 'NN')]
[('smartest', 'NN')]

[('I', 'PRP'), ('am', 'VBP'), ('smart', 'JJ')]
[('I', 'PRP'), ('am', 'VBP'), ('smarter', 'RB')]
[('I', 'PRP'), ('am', 'VBP'), ('smartest', 'JJS')]

[('smart', 'JJ'), ('person', 'NN')]
[('smarter', 'RBR'), ('person', 'NN')]
[('smartest', 'JJS'), ('person', 'NN')]

[('work', 'NN')]
[('beautiful', 'NN')]
[('sweeter', 'NN')]
[('nicer', 'NN')]
[('darker', 'NN')]

[('beautifully', 'RB')]
```
*(The spacing was added after the fact)*

[A link explaining the used Penn Treebank POS tags.](https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html)

In conclusion: the words are better tagged when placed in the proper context. However, I believe `smarter` in `I am smarter` should be `JJR` (Adjective, comparative), or at least `RBR` (Adverb, comparative), instead of `RB` (comparative). I also believe the same holds for `smarter` in `smarter person`, where `JJR` seems better than `RBR`.

Still, this is way better than `NN`.

Other words such as `work` (which can be interpreted to be a noun and a verb) also seem to default to a noun when they are placed standalone. Moreover, other comparative adjectives are also classified as nouns by default (`sweeter`, `nicer`, `darker`).

However, do note that not all inputs are necessarily classified as nouns when it's just a single word, as can be seen with `beautifully`.
