### ISSUE TITLE
Is not the max of meteor score 100?  (nltk.translate.meteor_score)

### ISSUE THREAD

**Issue by zengxiang68** [nltk/nltk#2751]
I used [nltk.translate.meteor_score](https://github.com/nltk/nltk/blob/develop/nltk/translate/meteor_score.py) to calculate the meteor score of a example, strangely I got a score of 105.6. 
Is not the max of meteor score 100?

The example is following:

> **candidate:**   creates or updates a virtual machine scale set
**reference:**   create or update a vm scale set
**METEOR score:**   105.6

Is there anyone know that? Thank you very much!

**Comment by tomaarsen** [comment]
You are correct. The METEOR score should be 0.7806 (or 78.06%), and definitely not more than 100%. 
Through this issue, I've found a bug in how NLTK computes the METEOR score, and have created #2763 to fix this issue. 

I suspect this will be fixed in the next minor version.

Thank you for bringing this to our attention!
