### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by mannan291** [nltk/nltk#2805]
i used to get my output through nltk.set_proxy('http://user:password@ip:port') for like one year, but now this method is giving HTTP error, even by using the rule given by the nltk library which is ('http://ip:port',user,password) 
![image_2021_09_14T05_20_15_646Z](https://user-images.githubusercontent.com/83581864/133257750-6a3de092-92ef-49c1-93aa-335bbcaf5a3a.png)

**Comment by tomaarsen** [comment]
@mannan291 
What NLTK version are you using?
```python
>>> import nltk
>>> print(nltk.__version__)
```
or
```
python -c "import nltk; print(nltk.__version__)"
```

I ask this, because the line of code that is throwing a `KeyError` can be seen here:
https://github.com/nltk/nltk/blob/ab1027691fcd0e6e9d206156a4fd01eb0c5db626/nltk/util.py#L1098-L1101

And in the current version, this `KeyError` is caught with a `try-except`.

**Comment by stevenbird** [comment]
Thanks @tomaarsen
