### ISSUE TITLE
AttributeError: 'LazyMap' object has no attribute 'copy'

### ISSUE THREAD

**Issue by livingstream** [nltk/nltk#283]
File "/usr/local/lib/python2.7/dist-packages/nltk/classify/naivebayes.py", line 88, in classify
    return self.prob_classify(featureset).max()
  File "/usr/local/lib/python2.7/dist-packages/nltk/classify/naivebayes.py", line 94, in prob_classify
    featureset = featureset.copy()
AttributeError: 'LazyMap' object has no attribute 'copy'

After looking at the LazyMap API, I do not find the attribute copy. 

Python code to do NB:
data_set = apply_features(extract_features, records)
training_set = data_set[1:200]
testing_set = data_set[200:437]
classifiert = nltk.NaiveBayesClassifier.train(training_set)
nltk.NaiveBayesClassifier.classify(classifiert,testing_set)

**Comment by dasl-** [comment]
Hi livingstream, 

I have a few questions/comments  about this issue.
1) How are you passing two parameters to nltk.NaiveBayesClassifier.classify(classifiert, testing_set)? The classifier method is only supposed to take one parameter, the featureset dictionary.
2) How are you calling the classify method statically? It is not a static method.
3) You are getting this attribute error because the method expects featureset to be a dictionary, not a LazyMap.

**Comment by kmike** [comment]
I'm closing this ticket because the code in bug report is incorrect. Thanks @davidleibovic for the review!
