### ISSUE TITLE
Punkt Tokenizer not achieving expected results

### ISSUE THREAD

**Issue by DanielCarrami** [nltk/nltk#2871]
Hello. 

I've been trying to train Punkt tokenizer to split sentences in a particular way, but it doesn't seem to be working. I have many PDF files that contain a specific kind of inquiry. I want the Punkt tokenizer to divide said inquiries. For example, when using the German pickle file to do the split, this happens:

> Telefax
An: 
 Telefon: 
Datum Fax-Nr.: 
Unsere Anfrage-Nr.: 
 Blatt : 1 von
 Sehr geehrte Damen u. Herren ,
 Bitte erstellen Sie uns ein Angebot, mit gültiger
 Preis- und Terminstellung frei Haus inklusive Fracht und
 Verpackung für folgende Positionen.
--
 Menge Bezeichnung Ø Maß mm Länge Material Bemerkung
1 Rohr 406,4 x 5 2000 1.4539
1 Rohr 88,9 x 3,2 1000 1.4539
2 Rohr 33,4 x 2,6 1000 1.4539
4 V-Flansch DN25 PN40 1.4539
2 V-Flansch DN200 PN 10 1.4539
4 V-Flansch DN80 PN40 1.4539
2 V-Flansch DN50 PN40 1.4539
Ausführung gemäß: AD2000
 Lieferzeit :
 Kosten für Zeugnisse, sachliche und pers.
--
Abnahmekosten bitte angeben
 Für Ihre freundliche Mühe bedanken wir uns im voraus.
--
Mit freundlichem 

This is an inquiry: 

> 4 V-Flansch DN25 PN40 1.4539

This is the code I use to achieve that result:
```
def segmentate_sentences(text):
  sent_detector = nltk.data.load('tokenizers/punkt/german.pickle')
  print('\n-----\n'.join(sent_detector.tokenize(text.strip())))
```
But what I want is to split the specific inquiries, each one in as a sentence, like this:
 
> Telefax
An: 
 Telefon: 
Datum Fax-Nr.: 
Unsere Anfrage-Nr.: 
 Blatt : 1 von
 Sehr geehrte Damen u. Herren ,
 Bitte erstellen Sie uns ein Angebot, mit gültiger
 Preis- und Terminstellung frei Haus inklusive Fracht und
 Verpackung für folgende Positionen.
--
 Menge Bezeichnung Ø Maß mm Länge Material Bemerkung
--
1 Rohr 406,4 x 5 2000 1.4539
--
1 Rohr 88,9 x 3,2 1000 1.4539
--
2 Rohr 33,4 x 2,6 1000 1.4539
--
4 V-Flansch DN25 PN40 1.4539
--
2 V-Flansch DN200 PN 10 1.4539
--
4 V-Flansch DN80 PN40 1.4539
--
2 V-Flansch DN50 PN40 1.4539
--
Ausführung gemäß: AD2000
 Lieferzeit :
 Kosten für Zeugnisse, sachliche und pers.
--
Abnahmekosten bitte angeben
 Für Ihre freundliche Mühe bedanken wir uns im voraus.
--
Mit freundlichem 

I don't really mind how the rest of the text is segmented. To achieve this, I tried training the Punkt Tokenizer. I've read a couple of issues and SO posts about training and the data format for training (Which, for my understanding, is just plain text). For the training and execution, I used the following code snippet:

```
def train_tokenizer(input_text):
  train_text = state_union.raw("training_data.txt")

  custom_sent_tokenizer = PunktSentenceTokenizer(train_text) 

  tokenized = custom_sent_tokenizer.tokenize(input_text)

  print('\n-----\n'.join(tokenized))
```

For training_data.txt I just wrote the entire text and separated the sentences according to the result I wanted to achieve. Regardless, the result is precisely the same as while using the pre-trained german model. I've made many modifications to the training file, like adding line breaks between sentences, trying different ways to segment, but the result doesn't seem to change.

I read in one SO post that the training required a lot of data, not specifying exactly how much. I have a document with more than 10,000 inquiries in different formats. I used it for training, but the model kept performing precisely the same. I would really appreciate some guidance :) 

(I know that could use Regex in this particular case, but that only applies to this text. Usually, my inquiries come in many different formats and forms. That's why I want to train my own sentence tokenizer)

**Comment by tomaarsen** [comment]
Hello!

My understanding of the PunktSentenceTokenizer is that it is a statistical model, which still relies on specific characters to mark the end of the sentences:
https://github.com/nltk/nltk/blob/f12df18465ba642d93f8f2f5d9a85147a2e1a450/nltk/tokenize/punkt.py#L203-L204

With other words, Punkt may use statistical models to determine where to split,  but it only makes those decisions at potential ends of sentences, and the default system doesn't consider `\n` to be a potential end of a sentence.

Someone encountered a similar issue, and I found that adding `\n` as a potential end line character sadly doesn't work currently: https://github.com/nltk/nltk/issues/2460#issuecomment-857576564

This is how someone would go about modifying the expected sentence end characters:
```python
import nltk
from nltk.tokenize.punkt import PunktLanguageVars

input_text = """Telefax
An:
Telefon:
Datum Fax-Nr.:
Unsere Anfrage-Nr.:
Blatt : 1 von
Sehr geehrte Damen u. Herren ,
Bitte erstellen Sie uns ein Angebot, mit gültiger
Preis- und Terminstellung frei Haus inklusive Fracht und
Verpackung für folgende Positionen.
Menge Bezeichnung Ø Maß mm Länge Material Bemerkung
1 Rohr 406,4 x 5 2000 1.4539
1 Rohr 88,9 x 3,2 1000 1.4539
2 Rohr 33,4 x 2,6 1000 1.4539
4 V-Flansch DN25 PN40 1.4539
2 V-Flansch DN200 PN 10 1.4539
4 V-Flansch DN80 PN40 1.4539
2 V-Flansch DN50 PN40 1.4539
Ausführung gemäß: AD2000
Lieferzeit :
Kosten für Zeugnisse, sachliche und pers.
Abnahmekosten bitte angeben
Für Ihre freundliche Mühe bedanken wir uns im voraus.
Mit freundlichem"""

class EndLineLangVars(PunktLanguageVars):
    sent_end_chars = ("ß", ".", "?", "!")
    """Characters which are candidates for sentence boundaries.
    This is a truly nonsense example which also allows sentence splitting on ß.
    Note that the pretrained Punkt is also not trained with this in mind."""

def segmentate_sentences(text):
    sent_detector = nltk.data.load('tokenizers/punkt/german.pickle')
    sent_detector._lang_vars = EndLineLangVars()
    print('\n-----\n'.join(sent_detector.tokenize(text.strip())))

segmentate_sentences(input_text)
```

Which outputs:
```
Telefax
An:
Telefon:
Datum Fax-Nr.:
Unsere Anfrage-Nr.:
Blatt : 1 von
Sehr geehrte Damen u. Herren ,
Bitte erstellen Sie uns ein Angebot, mit gültiger
Preis- und Terminstellung frei Haus inklusive Fracht und
Verpackung für folgende Positionen.
-----
Menge Bezeichnung Ø Maß
-----
mm Länge Material Bemerkung
1 Rohr 406,4 x 5 2000 1.4539
1 Rohr 88,9 x 3,2 1000 1.4539
2 Rohr 33,4 x 2,6 1000 1.4539
4 V-Flansch DN25 PN40 1.4539
2 V-Flansch DN200 PN 10 1.4539
4 V-Flansch DN80 PN40 1.4539
2 V-Flansch DN50 PN40 1.4539
Ausführung gemäß
-----
: AD2000
Lieferzeit :
Kosten für Zeugnisse, sachliche und pers.
-----
Abnahmekosten bitte angeben
Für Ihre freundliche Mühe bedanken wir uns im voraus.
-----
Mit freundlichem
```
This works like  you would expect, but it sadly doesn't work with `"\n"`. One of the reason for this is as follows: 
* Punkt will find a potential sentence end in`"Word. Another word"`: `<re.Match object; span=(0, 5), match='Word.'>`
* Punkt will **not** find a potential sentence end in`"Word.Another word"`. This is because of the lack of some whitespace after the sentence end marker. 

If `"\n"` is used as a potential sentence end marker, the situation is identical:
* Punkt will find a potential sentence end in`"Word\n Another word"`: `<re.Match object; span=(0, 5), match='Word\n'>`
* Punkt will **not** find a potential sentence end in`"Word\nAnother word"`. This is because of the lack of some whitespace after the sentence end marker. 

And for `"\n"`, the former case practically does not occur. It would require data like:
```
Word
 Another word
```

So, in short:
1. Your trained PunktSentenceTokenizer does not split on newlines because it only considers `.`, `!` and `?` to be potential newlines, and
2. `"\n"` can not really be used as a sentence end character, because it is virtually never followed by whitespace before the next sentence starts.
3. Even if the former issue didn't exist, then the numerous uses of word-level tokenization would simply remove `"\n"` from the input.

With other words, splitting on newlines is not something the PunktSentenceTokenizer will do for you. Of course, you can add certain symbols before the newlines you plan to split on, then add that symbol to `sent_end_chars`, and you'll have a working system. But then you need to somehow pre-process those symbols into your system, and if you can do that, then you can probably find another simpler way to extract the sentences you're particularly interested in.

I hope this cleared it up a bit.

- Tom Aarsen

**Comment by DanielCarrami** [comment]
It did clear everything up. I really appreciate your thorough response
