### ISSUE TITLE
TreebankWordDetokenizer is not always an inverse of TreebankWordTokenizer

### ISSUE THREAD

**Issue by kazet** [nltk/nltk#2876]
For example, for the following script:

```python

import nltk
import nltk.tokenize

tokens = nltk.tokenize.TreebankWordTokenizer().tokenize("I wanna watch something")
print(tokens)
sentence = nltk.tokenize.treebank.TreebankWordDetokenizer().detokenize(tokens)
print(sentence)
```

The result is:
```
['I', 'wan', 'na', 'watch', 'something']
I wannawatch something
```

The detokenized sentence should be: `I wanna watch something`

**Comment by tomaarsen** [comment]
Hello!

For context, this comment might help:
https://github.com/nltk/nltk/blob/f12df18465ba642d93f8f2f5d9a85147a2e1a450/nltk/tokenize/destructive.py#L34-L42

In short, TreebankWordDetokenizer is not *guaranteed* to revert to the original string. This is because there are multiple inputs that lead to the same output - which make it impossible to know which of the multiple inputs is desired.

*That said*, there definitely seems to be a bug when looking at your example - it should have been able to know that "wanna" and "watch" should not become one word.
