### ISSUE TITLE
Undocumented API breakage in nltk.tree.ParentedTree

### ISSUE THREAD

**Issue by aecay** [nltk/nltk#289]
Commit  18267ffe of 2012-02-05 changed the API of `ParentedTree`, turning some things that were formerly properties into methods (including `parent`).  This badly breaks any code that uses `ParentedTree` -- the whole point of having a `ParentedTree` is to be able to access its `parent`.

The change is also flawed, turning e.g. `ptree.parent.treeposition` into `ptree.parent().treeposition()` -- the latter being more verbose and less idiomatic.  I think it should be reverted too (just the property -> method change, not the rest of pull request 208), but it at least has to be documented in the ChangeLog/release notes.

**Comment by stevenbird** [comment]
Sorry that our ChangeLog did not document this API change.  There were many API changes made when 2.0 was still in beta.  Now that 2.0 has been finalised, we're being more conservative with changing the API.  Let's see what Peter Ljunglof has to say, and if its not resolved after that, discuss on nltk-dev.

**Comment by heatherleaf** [comment]
I suggested these changes on nltk-dev Feb 3rd, and the only one who commented was Steven who said he liked the proposed change:

https://groups.google.com/d/msg/nltk-dev/TjTHPpI08M0/96jdd7WEsc4J

**Comment by heatherleaf** [comment]
Here are the arguments I had for the changes:

ParentedTree (PT) and MultiParentedTree (MPT) (in tree.py) have lot of properties:

  PT: parent, parent_index, left_sibling, right_sibling, treeposition, root
  MPT: parents, left_siblings, right_siblings, root

I don't like this, and would very much prefer them to be methods. Here's why:
- MPT.parent_indices() and MPT.treepositions() are already methods, since they take an argument
- the notion of property suggest that the information is stored, when it is infact calculated
- ProbabilisticTree has the methods .prob() and .logprob(), which really returns a stored value: if .prob() is a method, then I don't see why .left_sibling shouldn't be a method
- properties give an extra layer of complication, and in this case it doesn't give anything back

I know, in some sense it's a minor issue, but the current situation makes the code more difficult to maintain.

The only things that I feel are ok to have as properties are PT.parent and MPT.parents, since they really denote stored values. But I'm ok with having them as method too.

The only problem as I see it is that it will break existing code. On the other hand, PT and MPT are not mentioned in the book, and are not used anywhere else in the code (and neither in nltk_contrib). Which means that there won't be much existing code to break...

**Comment by heatherleaf** [comment]
As I wrote then: I'm ok with having .parent and .parents as properties. But I don't see why e.g. .treeposition() should be a property, when .treepositions() is a method.

**Comment by stevenbird** [comment]
Thanks for reminding us that this was already discussed on nltk-dev.  Given that the bulk of them need to be methods, I don't have a problem with them all being methods, even though it is more verbose.  (Perhaps this is another of those worse-is-better cases: http://www.jwz.org/doc/worse-is-better.html)

**Comment by aecay** [comment]
Beginning with the second point, and proceeding in order:
- Stored vs. calculated is an implementation detail, not something that should be exposed by the API.  It is perfectly possible to pre-calculate and store certain values (for speed reasons, if they need to be consulted often); it's also possible to move in the other direction.  The property vs. method distinction has more to do with the logical structure of the API.  So, things that are not "actions" on the object are perspicuously represented, in Python, as properties.  The language wouldn't provide the `@property` syntax at all if properties were just to be stored values -- one could simply use field access.
- This cuts both ways; I'd argue (but for reasons of API consistency) that (log)prob should be a property as well.
- The "extra layer of complication" is only a decorator on a handful of methods, which is fairly intuitive.  It also simplifies  code that uses the API.  A well-designed library might have very complex internals, but presents a simple interface to client code.

As to the first point, I don't have occasion to reason about objects that could be represented by MultiParentedTrees.  I tend to think that (unlike mono-parented trees) they are a leaky abstraction that would be better represented by a different, possibly more standard graph-theoretic object (a directed graph?). 

But, assuming someone who has familiarity with and use for these kinds of things, they must know that a treeposition function for an MPT requires an argument to be coherent.  I'd argue that consistency with the Python paradigm (property-like things have the syntax of field access, operations that inevitably have parameters have the syntax of method calls) is more important to making the API intelligible than internal consistency.

**Comment by heatherleaf** [comment]
I agree with your arguments in full. Almost.

> • Stored vs. calculated is an implementation detail, not something that should be exposed by the API. (...) The property vs. method distinction has more to do with the logical structure of the API. 

I agree. That was my real point from the beginning, I just couldn't formulate it that well.

> So, things that are not "actions" on the object are perspicuously represented, in Python, as properties. 

This is where I don't agree, not in full at least. I would say that things that are (mentally percieved as) calculated from the basic properties of the object, also suit better as methods.

E.g. the left and right siblings are calculated from the tree structure, and should therefore be methods, not properties. The same holds for treeposition and parent_index.

The parent is another deal. I'd be perfectly fine with having that as a property, since it is a _parented_ tree. But I'm not sure if it's worth changing the API once again. Steven is the one to decide this.

And prob/logprob should really be properties, since that's what they are. But then we would have to make a very big API change to the whole of NLTK, since the ProbabilisticMixIn class is everywhere. 

> I'd argue that consistency with the Python paradigm (...) is more important (...) than internal consistency.

I don't agree entirely here either. I think it's more important that the NLTK API is consistent in how we separate properties/methods. 

It's too bad that you weren't in the nltk-dev list back in February, when we had all our 2.0 discussions. Your comments would have been very valuable.

Perhaps we should move this discussion to nltk-dev, now that it's more about opinions than explicit bugs? Is there a good standardized way to do that, so that the rest of nltk-dev can follow?

PS. I also agree with you about MultiParentedTree - it should be implemented as a DAG instead. I don't even know if anyone uses it.

**Comment by stevenbird** [comment]
Thanks for the discussion of the issues. I think that the argument needs to be stronger before we change 2.0. However, we can entertain wholesale API changes as we move from Python 2 to Python 3 (perhaps in a new DAG class, uniting MultiParentedTree with FeatureStructure?).  We could discuss this further on nltk-dev if there's enough interest.
