### ISSUE TITLE
nltk.download() does not work

### ISSUE THREAD

**Issue by sriramja96** [nltk/nltk#2894]
When trying to use the nltk downloader in Colab i.e., nltk.download('punkt'),

I get the below error:

```
File "<string>", line unknown
ParseError: no element found: line 1, column 0
```

![image](https://user-images.githubusercontent.com/65125423/143721787-aa57c333-4fd1-4259-b8d1-4d03150ebb55.png)

**Comment by dannysepler** [comment]
hey! i'm not totally sure i'll be able to help you here, since I know nothing about Colab and running

```python
import nltk

nltk.download("punkt")
```

works for me locally. Further, running that snippet in this [Colab notebook I found online](https://colab.research.google.com/github/gal-a/blog/blob/master/docs/notebooks/nlp/nltk_preprocess.ipynb#scrollTo=-44aMwUcQZxm) also works. but can you give some more information about your Colab notebook? Can you link to it? Do you know the version of python and of nltk that your Colab notebook is using?

I'd recommend generally to post all the versions of stuff when you make github issues by the way. Makes our lives easier :)

**Comment by milandesai** [comment]
I had this problem yesterday too but it's working now. I believe it was related to the github outage since the nltk data is stored on github.

**Comment by sriramja96** [comment]
Yea, you're probably right. It works now !!

**Comment by sriramja96** [comment]
@dannysepler Sure Danny. Noted for the future. I'm very new to GitHub **issues** so made an amateur post without the logs.

**Comment by dannysepler** [comment]
Thank you @milandesai and not at all @sriramja96 glad it's working now!

**Comment by iliakur** [comment]
@dannysepler that error message seems confusing. do you know if it's easy to wrap in something clearer to users?
