### ISSUE TITLE
'wordnet' package and its data dependencies for version 3.6.6

### ISSUE THREAD

**Issue by mermakov** [nltk/nltk#2923]
Hello!

As of today (presumably due to version 3.6.6) our automated tests in a project using NLTK started failing due to missing NLTK data.

Environment: Ubuntu 18.04
Python: Python 3.7

I've used a short script to reproduce (clearing the entire NLTK data directory before each run):

```
import nltk

nltk.download('wordnet', force=True)

from nltk.corpus import wordnet as wn

wn.synsets('dog')
```

On version 3.6.5 this works properly.

On version 3.6.6 this fails with the following log:

```
Traceback (most recent call last):
  File "<...>/.venv/lib/python3.7/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "<...>/.venv/lib/python3.7/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource omw-1.4 not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('omw-1.4')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/omw-1.4.zip/omw-1.4/

  Searched in:
    <...>
```

I'm not entirely sure I understand where to check various dependencies for `wordnet`. Is it now necessary to manually download `omw-1.4` via `nltk.download` or is it an issue with the release?

**Comment by tomaarsen** [comment]
As per NLTK 3.6.6, we've started using `omw-1.4` instead of `omw`. You may have already noticed that installing `omw-1.4` via `nltk.download` will resolve the issue. However, I recognise that this is not particularly intuitive. 

The difference with NLTK 3.6.5 (which requires `omw`), is that `omw` was required lazily: it would only be needed when calling e.g. `_load_lang_data`, and then it would recommend you to install `omw`. Note that `omw` was not required for all tasks either.

With NLTK 3.6.6, `omw-1.4` is loaded immediately, which causes the warning you now see. 

With other words, it's not necessarily an implementation issue, but perhaps it's a design issue that stems from still asking users to download sections of `nltk_data` manually. I believe that it might be time to move to a system that automatically downloads this information when the system needs it, rather than telling the user to do it manually.

That said, I hope this explains the issue somewhat. As for your tests, I would advise also downloading `omw-1.4`.

**Comment by mermakov** [comment]
I see, thanks for your answer. I'll double check our code regarding lazy loading and whether `omw` was actually used, perhaps package initialization can be somewhat optimized.

I'll close the issue since the behavior is intended. Thanks again.

**Comment by fredericrous** [comment]
This is a breaking change, if nltk is using semver, 3.6.6 should have been tagged 3.7.0

**Comment by tomaarsen** [comment]
It should have been. This was an oversight. Apologies.

Happy new year.
