### ISSUE TITLE
From TreebankWordDetokenizer, the detokenize adds/subtracts spaces to/from special characters

### ISSUE THREAD

**Issue by espoof** [nltk/nltk#2935]
After using word_tokenize() on the following sample string:

"Hello ; Hello World     . Hello ; ;Hello;"

I use detokenize to put the string back together. I receive the following:

"Hello; Hello World . Hello;; Hello;"

The example above show spaces disappearing before semicolons. There are also scenarios where: 

";;;" turns to "; ; ;"

Is there a bug in the function or is this a way to clean up the string?

**Comment by rykroon-momentum** [comment]
I have also experienced a similar issue.
```
In [22]: tokens = word_tokenize("Ryan's")

In [23]: tokens
Out[23]: ['Ryan', "'s"]

In [24]: d.detokenize(tokens)
Out[24]: "Ryan 's"
```

**Comment by tomaarsen** [comment]
I'm afraid this is an issue caused by the TreebankTokenizer not being an [injective](https://en.wikipedia.org/wiki/Injective_function) function. To give an example, both `"Ryan 's"` and `"Ryan's"` map to `['Ryan', "'s"]` in the Tokenizer, and thus the Detokenizer can't be certain which of the two was the original string. 

So, although the Detokenizer simply uses the reverse regex operations from the Tokenizer, it can't always come to the correct original string again. We have added some regexes to try and help the Detokenizer be a bit smarter with punctuation and paranthesis handling, but it sadly isn't perfect.

There is some documentation on the Detokenizer [here](https://www.nltk.org/api/nltk.tokenize.treebank.html?highlight=detokenizer#nltk.tokenize.treebank.TreebankWordDetokenizer).

As for your example @rykroon-momentum, I believe the reason the that you're experiencing this somewhat weird behaviour is to try and support:
```python
>>> from nltk.tokenize.treebank import TreebankWordDetokenizer
>>> from nltk.tokenize import word_tokenize
>>> twd = TreebankWordDetokenizer()
>>> tokens = word_tokenize("Ryan 'The Guy' Kroon was his name")
>>> twd.detokenize(tokens)
"Ryan 'The Guy' Kroon was his name"
```
