### ISSUE TITLE
Missing newlines between entries in release notes

### ISSUE THREAD

**Issue by BLKSerene** [nltk/nltk#2953]
There're no newlines between each entry in [release notes](https://www.nltk.org/news.html), resulting in poor readability.
I'm not sure whether the release notes are generated automatically or added manually.

**Comment by tomaarsen** [comment]
The release notes page is not automatically generated, but at some point we seem to have switched to a more itemized list of changes. The release notes page can be found here on github: https://github.com/nltk/nltk/blob/develop/web/news.rst
(That said, perhaps https://raw.githubusercontent.com/nltk/nltk/develop/web/news.rst is more legible).

It's a bit of a confusing story, as we *also* have a Changelog file: https://github.com/nltk/nltk/blob/develop/ChangeLog. This file is slightly differently formatted, and a bit more detailed. 

Initially, web/news.rst seems to have been focused on *news*, like that development switched to a certain branch, that there was a certain number of downloads achieved, or that a book was released or a talk was scheduled. However, later it started just being a watered down changelog. 

I'm somewhat in favour of using this second file for the Release Notes page instead of web/news.rst. @stevenbird what are your thoughts on this? 

---

In the meantime though, I'll itemize the current news page to make it a bit easier to read. We're open to PRs if it's still hard to read. Thanks for bringing this to my attention.
