### ISSUE TITLE
CVE-2021-0204

### ISSUE THREAD

**Issue by konkodi210** [nltk/nltk#2964]
nltk version: 3.7

During the security reviews, we have found [CVE-2021-0204](https://nvd.nist.gov/vuln/detail/CVE-2021-0204).

**Comment by alvations** [comment]
Thank you @konkodi210 for notifying on the CVE. Most probably this is caused by your system allowing CLI access to NLTK resources through `python -m nltk.downloader`

According to https://kb.juniper.net/InfoCenter/index?page=content&id=JSA11114&actp=METADATA, it looks like it might be the Juniper dependancy you have on your system causing the problem that's allowing the `dexp` usage. 

Since it'll be on Juniper's end to patch their CLI and NLTK doesn't use `dexp` explicitly nor built on Juniper OS function, it's best to follow the workaround:

> WORKAROUND:
> Use access lists or firewall filters to limit CLI access to the device only from trusted, administrative networks or hosts.
> Limit access to the Junos OS shell to only trusted system administrators.
 
Meanwhile,  please let us know if any specific changes would need to be set on our end, if possible.
