### ISSUE TITLE
decisiontree classify demonstration is broken

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#297]
$ python ./classify/decisiontree.py
Training classifier...
Traceback (most recent call last):
  File "./decisiontree.py", line 285, in <module>
    demo()
  File "./decisiontree.py", line 280, in demo
    binary_names_demo_features)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nltk-2.0.3-py2.6.egg/nltk/classify/util.py", line 182, in names_demo
    classifier = trainer( [(features(n), g) for (n,g) in train] )
  File "./decisiontree.py", line 275, in f
    return DecisionTreeClassifier.train(x, binary=True, verbose=True)
  File "./decisiontree.py", line 155, in train
    feature_names, labeled_featuresets, feature_values, verbose)
  File "./decisiontree.py", line 255, in best_binary_stump
    fname, fval, labeled_featuresets)
  File "./decisiontree.py", line 244, in binary_stump
    default = DecisionTreeClassifier(neg_fdist.max())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nltk-2.0.3-py2.6.egg/nltk/probability.py", line 270, in max
    raise ValueError('A FreqDist must have at least one sample before max is defined.')
ValueError: A FreqDist must have at least one sample before max is defined.

**Comment by alexrudnick** [comment]
Just taking out "binary=True" over here:
https://github.com/nltk/nltk/blob/master/nltk/classify/decisiontree.py#L277

... makes it work. But I think the underlying bug is in binary_stump -- we mess it up trying to get the max of those FreqDists when they have no observations. But then what's the right thing to do if you get into that function and you have no applicable observations? ...

(working on it...)

**Comment by alexrudnick** [comment]
OK, should be fixed by 852378a!

**Comment by marcoippolito** [comment]
Hi Alex.
I'm having the same problem right now with Python 2.7 and the latest release of NLTK.

My code is:

from nltk.classify import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier.train(train_feats, binary=True, entropy_cutoff=0.8, depth_cutof\
f=5, support_cutoff=30)

This is the result:
Traceback (most recent call last):
  File "classifying.py", line 351, in <module>
    dt_classifier = DecisionTreeClassifier.train(train_feats, binary=True, entropy_cutoff=0.8, depth_cutoff=5, support_cutoff=30)
  File "/usr/local/lib/python2.7/dist-packages/nltk/classify/decisiontree.py", line 155, in train
    feature_names, labeled_featuresets, feature_values, verbose)
  File "/usr/local/lib/python2.7/dist-packages/nltk/classify/decisiontree.py", line 255, in best_binary_stump
    fname, fval, labeled_featuresets)
  File "/usr/local/lib/python2.7/dist-packages/nltk/classify/decisiontree.py", line 244, in binary_stump
    default = DecisionTreeClassifier(neg_fdist.max())
  File "/usr/local/lib/python2.7/dist-packages/nltk/probability.py", line 270, in max
    raise ValueError('A FreqDist must have at least one sample before max is defined.')
ValueError: A FreqDist must have at least one sample before max is defined.

What do I have to do in order to make it work? (I tried to taking out "binary=True" but when executing it stops)

Kind regards
Marco

**Comment by kmike** [comment]
Hi @marcoippolito,

Which NLTK version do you use? Alex's fix is a part of NLTK 3 alpha, it is not on pypi yet. You can get it from github, or from here: http://nltk.org/nltk3-alpha/

**Comment by marcoippolito** [comment]
Hi Mikhail,
I'm using nltk.**version** 
'2.0.4'

I saw in http://nltk.org/nltk3-alpha/ that "NLTK3.0 is likely to contain bugs"...:
so do you suggest to upgrade to 3.0 in order to have this DecisionTreeClassifier problem solved, or better wait till NLTK 3.0 version will be much more stable (I'm at the moment not that expert in order to be able to contribute to bugs fixing) ?

**Comment by kmike** [comment]
I don't know what to suggest :) There are bugs in nltk 2.0 and bugs in nltk 3.0, but they are different bugs. NLTK 2.0 is year or so behind NLTK 3.0, and there were a lot of 2.x bugs fixed in 3.x. On the other hand, 3.x may have new bugs because source code is changed a lot, and the code is not always compatible with NLTK book. There is http://nltk.org/book3/ which is being updated for NLTK3, but it is work in progress. I personally think that NLTK3 is a better bet because its bugs are likely simpler to fix, and there is a lot of improvements. But you must be ready to read some source code to use NLTK3 because not all examples from NLTK book will work as-is. 

If you just need a decision tree classifier then [scikit-learn](http://scikit-learn.org) is also an option; it has good implementations of decision trees, random forest and other alike classifiers. I doubt plain decision trees are used much these days.

**Comment by marcoippolito** [comment]
Thanks Mikhail for your suggestions.
I will try scikit-learn for the decision tree classifier.
Later, once I will have a thorough understanding of NLTK package, I will be able to shift to NLTK3.0 version

Kind regards
Marco
