### ISSUE TITLE
Punkt word tokenizer regex

### ISSUE THREAD

**Issue by vikigenius** [nltk/nltk#3023]
Appologies if this is the wrong place. But I am trying to understand the word tokenization regex used here

https://github.com/nltk/nltk/blob/1f28903066fe3ee3a4ab75085bfd5254184d135c/nltk/tokenize/punkt.py#L235-L247

Specifically the part
https://github.com/nltk/nltk/blob/1f28903066fe3ee3a4ab75085bfd5254184d135c/nltk/tokenize/punkt.py#L238-L239

My question is why is the lazy quantifier `\S+?` is needed here? Won't `\S+` give the same result here?

**Comment by tomaarsen** [comment]
Let's start by converting the regex into its full form:
```python
(
    (?:\-{2,}|\.{2,}|(?:\.\s){2,}\.)
    |
    (?=[^\(\"\`{\[:;&\#\*@\)}\]\-,])\S+?  # Accept word characters until end is found
    (?= # Sequences marking a word's end
        \s|                                 # White-space
        $|                                  # End-of-string
        (?:[)\";}\]\*:@\'\({\[\?!])|(?:\-{2,}|\.{2,}|(?:\.\s){2,}\.)|          # Punctuation
        ,(?=$|\s|(?:[)\";}\]\*:@\'\({\[\?!])|(?:\-{2,}|\.{2,}|(?:\.\s){2,}\.)) # Comma if at end of word
    )
    |
    \S
)
```
And then we'll consider the example input of `Hello!`. 

First of all, the first alternative of `(?:\-{2,}|\.{2,}|(?:\.\s){2,}\.)` clearly does not match, as we don't start with repeated dots or dashes. So, we start with a positive look-ahead of `(?=[^\(\"\¹{\[:;&\#\*@\)}\]\-,])`, which matches, as `H` is not in that set of options. (Note that I replaced a ` with ¹ for Markdown formatting reasons).

Then, `H` will be matched with `\S+?`, after which the regex engine will test the remainder with the section marked as `# Sequences marking a word's end`. This section only accepts whitespace, end-of-string, some punctuation and some stuff regarding commas. Because `e` is not any of these, the `\S+?` will match the `e`. This proceeds as expected, until after `o` has been matched. At this point, because `\S+?` is lazy, the section denoted as `# Sequences marking a word's end` will try to match the `!`. It can do so, because of the `!` in the `# Punctuation` set.

So, the positive look-ahead is matched, and thus the regex engine concludes matching. So, the first match is `Hello`. Afterwards, `!` becomes a second match.

If we had used `\S+`, then it would have greedily matched `Hello!` in full.

Feel free to experiment between `\S+?` and `\S+` here: https://regex101.com/r/bwJQi6/1

I hope that helps. I'll close this, but feel free to respond if you have more questions.

**Comment by vikigenius** [comment]
@tomaarsen thanks for the explanation. I just have one followup.

Why is the outermost capturing group required, removing them like this

```python
     _word_tokenize_fmt = r"""
         %(MultiChar)s 
         | 
         (?=%(WordStart)s)\S+?  # Accept word characters until end is found 
         (?= # Sequences marking a word's end 
             \s|                                 # White-space 
             $|                                  # End-of-string 
             %(NonWord)s|%(MultiChar)s|          # Punctuation 
             ,(?=$|\s|%(NonWord)s|%(MultiChar)s) # Comma if at end of word 
         ) 
         | 
         \S 
     """
```

Should give the same result right?

**Comment by tomaarsen** [comment]
@vikigenius I think so? Perhaps it influences which number you'd need to use with `match.group(...)`, because there's one more capturing group in the entire regex?
But I think the regex is only used with `.findall(...)`, which means that the individual capturing groups don't really matter anyways: it just returns (a list of) the whole matches.

That said, there's not really a reason to change it now. If it ain't broke (or slow, or bad style, or difficult to understand, etc. etc.), don't fix it.
