### ISSUE TITLE
AttributeError: 'SubPattern' object has no attribute 'pattern'

### ISSUE THREAD

**Issue by Neoxs** [nltk/nltk#3025]
i have installed ntlk using
```
pip install -U nltk
```

When running codes on Python 3.9, it runs successfully:

```
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
```

However, when I run above codes in jupyter notebook, it shows error:
```
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?8bfd1037-56d3-4e00-9f84-ec2b3125c53e)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/neoxsbibozero0/Desktop/kaggle/week3_classification/analyse_sentiment.ipynb Cell 27' in <cell line: 1>()
----> [1](vscode-notebook-cell:/Users/neoxsbibozero0/Desktop/kaggle/week3_classification/analyse_sentiment.ipynb#ch0000026?line=0) import nltk
      [2](vscode-notebook-cell:/Users/neoxsbibozero0/Desktop/kaggle/week3_classification/analyse_sentiment.ipynb#ch0000026?line=1) nltk.download('stopwords')
      [3](vscode-notebook-cell:/Users/neoxsbibozero0/Desktop/kaggle/week3_classification/analyse_sentiment.ipynb#ch0000026?line=2) from nltk.corpus import stopwords

File /opt/homebrew/lib/python3.9/site-packages/nltk/__init__.py:117, in <module>
    111 from nltk.jsontags import *
    113 ###########################################################
    114 # PACKAGES
    115 ###########################################################
--> 117 from nltk.align import *
    118 from nltk.chunk import *
    119 from nltk.classify import *

File /opt/homebrew/lib/python3.9/site-packages/nltk/align/__init__.py:15, in <module>
      9 """
     10 Experimental functionality for bitext alignment.
     11 These interfaces are prone to change.
     12 """
     14 from nltk.align.api  import AlignedSent, Alignment
---> 15 from nltk.align.ibm1 import IBMModel1
     16 from nltk.align.ibm2 import IBMModel2
     17 from nltk.align.ibm3 import IBMModel3
...
---> 50 parsed_pattern.pattern.groups = 1
     51 parsed_pattern.pattern.groupdict = {}
     52 return parsed_pattern

AttributeError: 'SubPattern' object has no attribute 'pattern'
```

I couldn't find a proper fix anywhere...

OS: MacOS Monterey
Chip: M1

**Comment by amdjedbens** [comment]
It seems like the used kernel in Jupyter doesn't contain same packages, in other words it means that terminal and jupyter notebook are in different environments.

- Try installing nltk using conda: `conda install nltk`, since conda creates language-agnostic environments natively unlike pip.
- also for more Tracebacks, apparently you're using VSCode interactive Python:

	The Jupyter extension currently notes the following regarding the 'Max Output Size' setting:

  		This setting is deprecated in favor of notebook.output.textLineLimit. This setting will be removed in an upcoming release.

	The setting they are referring to is `Notebook > Output: Text Line Limit` which requires you to reload VSCode before changes are applied.

   - Solution:
   		 	Open VS Code > File > Preferences > Settings. Then in the settings page look for "notebook". 
  Scroll down and there's the "Notebook > Output: Text Line Limit", which by default has value 50 but can be increased. 
  
 		// Note that the current setting does not use 0 to indicate that the output is limitless, while the previous 				settings did.

**Comment by tomaarsen** [comment]
> It seems like the used kernel in Jupyter doesn't contain same packages, in other words it means that terminal and jupyter notebook are in different environments.

This seems like a correct judgement. The traceback shows issues in `nltk/align/__init__.py`, in the `nltk.align` package. However, we renamed `align` to `translate` some 7 years ago now, in 7690cbf5f4b548b51d1985c6432dade3d09bb460. 

In short, @Neoxs, your Jupyter Notebook is using a different Python environment than you have in your terminal. The version in your terminal is up to date, while the one used by Jupyter Notebook is quite old still.

I reckon this should be resolved when you update your Jupyter Notebook settings to use the correct environment. I'll close this accordingly.
