### ISSUE TITLE
word confustion in nltk stemmer

### ISSUE THREAD

**Issue by jayambe36** [nltk/nltk#3029]
when i use word president that time, i get output as presid 
my question is why this ent is cut by system or library??

code :-

from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
sentence = "Hello I am Smit Patel President of India live in Delhi"
words = word_tokenize(sentence)
print(words)
ps = PorterStemmer()
for w in words:
  rootWord = ps.stem(w)
  print(rootWord)

output :- 

['Hello', 'I', 'am', 'Smit', 'Patel', 'President', 'of', 'India', 'live', 'in', 'Delhi']
hello
i
am
smit
patel
presid
of
india
live
in
delhi

**Comment by tomaarsen** [comment]
This is because Step 4 of the original Porter Algorithm, as described in "An algorithm for suffix stripping." by Porter, M. will strip away the `ent` suffix, e.g. in the word `dependent`. Note that all related words like president, preside, presiding, presided, etc. all stem to `presid`.

As implemented in NLTK:
https://github.com/nltk/nltk/blob/4a130f1cdf642327378a4387b319cd2df6f79287/nltk/stem/porter.py#L558

See also [Porter's own website](https://tartarus.org/martin/PorterStemmer/) about his algorithm, questions 2 and 3 from his FAQ:
> 2. Why is the stemmer not producing proper words?
> It is often taken to be a crude error that a stemming algorithm does not leave a real word after removing the stem. But the purpose of stemming is to bring variant forms of a word together, not to map a word onto its ‘paradigm’ form.
> And connected with this,
>
> 3. Why are there errors?
> The question normally comes in the form, why should word X be stemmed to x1, when one would have expected it to be stemmed to x2? It is important to remember that the stemming algorithm cannot achieve perfection. On balance it will (or may) improve IR performance, but in individual cases it may sometimes make what are, or what seem to be, errors. Of course, this is a different matter from suggesting an additional rule that might be included in the stemmer to improve its performance. 

I hope this is clear now.
