### ISSUE TITLE
Perplexity of a count based language model is always infinity

### ISSUE THREAD

**Issue by david-waterworth** [nltk/nltk#3065]
I trained a `KneserNeyInterpolated` language model with `order=2` as follows:

```
from nltk.lm.preprocessing import padded_everygram_pipeline
from nltk.lm import KneserNeyInterpolated, Laplace, StupidBackoff

train, vocab = padded_everygram_pipeline(2, corpus)

lm = KneserNeyInterpolated(order=2)
lm.fit(train, vocab)
```

Where corpus is a list of lists (i.e. tokenised)

I had to step through the code in order to work out why I couldn't calculate perplexity - it always returned `inf`. What I realised is the score of the start token (`<s>`) is always zero, i.e.

```
lm.estimator.unigram_score('<s>')
```

Because entropy is the mean of the ngram logscores, the result is infinity if any ngram has a score of zero.

I don't fully understand the math as I've not had time to drill into the model (a reference would be useful) but it's due to the use of `_continuation_counts` - i.e. the docstring says:

> Continuations track unique ngram "types", regardless of how many
> instances were observed for each "type".
> This is different than raw ngram counts which track number of instances.

The `_continuation_counts` for `<s>` is always zero resulting in an infinite log score.

What I ended up doing was to generate all the bigrams and unigrams with the `<s>` and `</s>` tokens and then remove them from the unigrams only (but not the bigrams as they're vital for the correct calculation of perplexity). Since `<s>` and `</s>` appear in every string it doesn't matter if they're excluded.

Is this the expected way of doing this - and is there a `proper` way of doing so - what I did was

```
lm.perplexity(
        list(everygrams(
                pad_both_ends(text.split(' '), n=2),
                max_len=2))[1:-1])
```

I couldn't find any documentation or discussion on this so want to confirm I've not missed something?

**Comment by david-waterworth** [comment]
I think the problem I'm having is when you train a count-based interpolated language model (of order 2 in this case) you use the list of all bigrams and unigrams. But when you evaluate the perplexity, you should only be using the list of bigrams from the test set. 

Can someone please confirm this?

**Comment by tomaarsen** [comment]
Hello! Sorry for the delay. I've been having a look at this (and a potentially related) issue recently, but I struggle to always reproduce the results. For example, I don't always get infinity on the `KneserNeyInterpolated` perplexity. Here is a testing script that I used.

```python
from nltk.lm.preprocessing import padded_everygram_pipeline
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.lm import KneserNeyInterpolated, Laplace, StupidBackoff

raw_text = """
Hello! This is a pretty long text, or so I would hope. I intend
for it to have multiple sentences. I should be able to do that, I reckon.
However, that does mean that I have to keep coming up with some text.
Luckily, that is not all too difficult. This text should be approaching
a good length by now.
"""

tokenized = [word_tokenize(sent) for sent in sent_tokenize(raw_text)]

train, vocab = padded_everygram_pipeline(2, tokenized)
lm = KneserNeyInterpolated(order=2)
lm.fit(train, vocab)

# Compute entropy and perplexity of these ngrams
bigrams = [("This", "is"), ("long", "text")]
print(bigrams)
print(lm.entropy(bigrams))
print(lm.perplexity(bigrams), "\n")

# Even with bigrams that don't occur, we just get higher entropies & perplexities,
# but no infinity
bigrams = [("That", "is"), ("large", "text")]
print(bigrams)
print(lm.entropy(bigrams))
print(lm.perplexity(bigrams), "\n")

# Only if *none* of the words in any of the bigrams exist, do we get infinity
bigrams = [("That", "could"), ("large", "sentences")]
print(bigrams)
print(lm.entropy(bigrams))
print(lm.perplexity(bigrams), "\n")

# For unigrams, as long as all of the words exist, we get normal outputs
unigrams = [("that",), ("long",), ("should",)]
print(unigrams)
print(lm.entropy(unigrams))
print(lm.perplexity(unigrams), "\n")

# However, if we use a unigram that does not exist, the entropy/perplexity does become infinity
unigrams = [("That",), ("long",), ("should",)]
print(unigrams)
print(lm.entropy(unigrams))
print(lm.perplexity(unigrams))
```
Which outputs:
```python
[('This', 'is'), ('long', 'text')]
0.6438952524596825
1.5625423071195421

[('That', 'is'), ('large', 'text')]
4.816043206417591
28.169132042006552

[('That', 'could'), ('large', 'sentences')]
inf
inf

[('that',), ('long',), ('should',)]
5.246870289871118
37.97216336228823

[('That',), ('long',), ('should',)]
inf
inf
```

Note that it's very easy to make a mistake with the input to e.g. `lm.fit`, `lm.entropy`, `lm.perplexity` or `lm.score`. In fact, when writing this script, I first initially accidentally made a language model with only characters, which *did* lead to scores of only 0 and perplexities/entropies of infinity. Furthermore, accidentally using `("that",)` rather than `[("that",)]` is a very easy mistake, and has big consequences:
```python
>>> lm.entropy(("that",))   
inf
>>> lm.entropy([("that",)])
4.523561956057013
```

I might be able to help you further if I'm able to consistently reproduce your issue.

- Tom Aarsen

**Comment by david-waterworth** [comment]
Hi @tomaarsen - the difference is I'm using short text descriptions (1-5 words), and it's essential to include the `<s>` and `</s>` tokens in the calculation of perplexity. Initially, I was using the same pipeline to generate the input to `lm.perplexity` as I was to train the actual model - this included a mix of unigrams and bigrams, including the `<s>` and `</s>` tokens. 

So for training I use:

`train, vocab = padded_everygram_pipeline(order=2, text=corpus)`

But now for test I use

`lm.perplexity(bigrams(pad_both_ends(text.split(' '), n=2)))`

i.e.
```

grams = list(bigrams(pad_both_ends("This is long".split(' '), n=2)))
print(grams)
print(lm.entropy(grams))
print(lm.perplexity(grams))
```

```
[('<s>', 'This'), ('This', 'is'), ('is', 'long'), ('long', '</s>')]
5.21987724385876
37.268303543936
```

If you include unigrams, though, `<s>` causes infinite perplexity, i.e.

```
print(lm.perplexity([("<s>",)]))
print(lm.perplexity([("</s>",)]))
```

I'm pretty sure you're not supposed to use unigrams - and since `<s>` doesn't complete any bigram it's not part of the model vocab hence the infinite perplexity. So I think what I'm doing is correct but it's easy to do it wrong and it wasn't initially clear to me from the documentation.

**Comment by tomaarsen** [comment]
I think the entropy and perplexity calculations for unigrams are a measure of likelihood of the word occurring after *any* context. For `</s>` this happens in two situations in my example: after `.`, which is followed by `</s>` with a frequency of 6, and after `!`, which is followed by `</s>` with a frequency of 1. Because of these two, `_continuation_counts` returns `(2, 69)`, which leads to a score of `2 / 69 = 0.02898...`, and an entropy/perplexity of 5.108... and 34.5, respectively.

However, the `<s>` never follows any other word, because it's always the first word. This causes a score of 0, which then gives a logscore of -inf for that unigram, causing the other grams to not matter, because we apply a mean average over all logscores. 

In short, I believe that only the *first* word, i.e. `<s>`, will cause infinity entropy/perplexity. Using `("</s>",)` or other unigrams like `("That",)` is possible, as long as the word exists in the model. 

---

Now, that information was not now to you, so let's discuss the interesting part: whether you *should* be using unigrams in the perplexity computation. There was recently some confusion about which implementation of entropy was used in NLTK, but this has been cleared up here:
* #2961

In particular, the NLTK implementation is inspired by a text file from [this comment](https://github.com/nltk/nltk/issues/1342#issuecomment-203060085), which uses the following implementation for perplexity:
```python
    def perplexity(self, sentence, method):
        """
        Compute
        """
        return 2.0 ** (-1.0 * mean([method(context, word) for context, word in \
                                    bigrams(self.tokenize_and_censor(sentence))]))
```
Note, `tokenize_and_censor` is a generator that first yields `<s>`, then all of the words that exist in the vocab one by one, and then `</s>`. Afterwards, `nltk.util.bigrams` is called, which you're familiar with.
In short, the original author of the perplexity method as implemented in NLTK suggests to use only bigrams of a sentence to measure the perplexity of the sentence in the language model.

This corresponds exactly with the solution that you came to independently:
```python
grams = list(bigrams(pad_both_ends(sentence.split(), n=2)))
```
Well done!

I hope that clears it up a bit.

- Tom Aarsen

**Comment by david-waterworth** [comment]
Yes that's fine thanks!
