### ISSUE TITLE
`generate` gives infinite recursion for recursive grammars

### ISSUE THREAD

**Issue by sylee957** [nltk/nltk#3072]
The following code for generating simple recursive grammar does not work

```python
from nltk.grammar import Nonterminal, Production, CFG
from nltk.parse.generate import generate


S = Nonterminal('S')
P = [Production(S, ['a', S]), Production(S, [])]
G = CFG(S, P)

gen = generate(G)
print(next(gen))
```
gives `RuntimeError: The grammar has rule(s) that yield infinite recursion!`

I think that the problem should not be an issue if the algorithm uses different searching technique
and iterators should be capable of generating infinite sequences.
Without the capability to generate recursive grammars, it loses many practical capability because it can only handle finite grammars.

**Comment by ekaf** [comment]
@sylee957, with an infinite grammar, you can use the _depth_ parameter to limit the recursion depth:

```
gen = generate(G, depth=10)
print(next(gen))
```
['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']

**Comment by sylee957** [comment]
I think that it also has the problem if it doesn't reach `'aa', 'aaa', 'aaaa', ...`

**Comment by ekaf** [comment]
@sylee957 actually, given a finite value for 'depth' lower than the recursion limit, the _generate_ function does reach all the allowable productions. Since it concatenates lists and not strings, it outputs forms  like ['a', 'a'] instead of 'aa'. And since it applies the grammar depth-first, the first output is the deepest tree, while the breadth-first strategy would start with ['a'].

**Comment by ekaf** [comment]
For example:

```
n = 5
gen = generate(G, depth=n)
for _i in range(n):
    print(next(gen))
```

['a', 'a', 'a', 'a']
['a', 'a', 'a']
['a', 'a']
['a']
[]

**Comment by ekaf** [comment]
So the real problem seems to be that, at line 29, _generate.py_ sets a default depth that is much higher  than the recursion limit:

```
    if depth is None:
        depth = sys.maxsize
```

However, using sys.getrecursionlimit() instead, which is 1000, is also still too high. 
With the above [grammar](https://github.com/nltk/nltk/issues/3072#issue-1450830583), the highest usable depth was 331 for me. Maybe the reason for this could be that the indirect recursions between __generate_all()_ and __generate_one()_ are adding up towards the recursion limit. If that is the reason, the maximum possible depth could be a little less than a third of the recursion limit.

Then, the solution could be, on one hand, to lower the default depth and, on the other hand, to output a more informative warning when the recursion limit is reached,
and mention the possibility of raising that value, using sys.setrecursionlimit().
