### ISSUE TITLE
Stop words - gender omission 

### ISSUE THREAD

**Issue by paulellis65** [nltk/nltk#3073]
Name: nltk
Version: 3.4.5
Summary: Natural Language Toolkit

Looking at the gender words contained in the above stop words 'English'

his - hers
himself - herself
him - her
he - she / she's

The list appears to omit the word he's

Is there any reason for this? Quite a fundamental omission. 

Thanks, 

Paul

**Comment by tomaarsen** [comment]
Hello!

This is because a common usage is to pass the input text through `word_tokenize`, which converts e.g. `he's` into `["he", "'s"]`, after which the `"he"` can be stripped. A common usage that I see is:
```python
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text = "He's eating an apple over there."
stop_words = set(stopwords.words())
tokenized = word_tokenize(text)
# ['He', "'s", 'eating', 'an', 'apple', 'over', 'there']
cleaned = [word for word in tokenized if word.lower() not in stop_words]
# ["'s", 'eating', 'apple']
```
As a result, `"he"` can be stripped regardless of the contraction in which it is used (`"he'd"`, `"he'll"`, etc). A better question might be why `she's` **is** in the stopwords list, as it seems a bit unnecessary. Perhaps some additional consistency (either both or neither) would be best here, but I don't know if I'm leaning towards both or neither.

**Comment by JEnduriumK** [comment]
@tomaarsen 

Wait, I thought that you _shouldn't_ be removing stop words from things prior to analyzing them with VADER. 

For example, I believe that the following words are in English `stopwords` file from `nltk.corpus`:

```
the
of
to
for
```

Which, unless I'm _wildly_ misunderstanding how VADER works, definitely **shouldn't** be removed before handing the sentence or text to VADER, because of the `special_cases` involving idioms that is built into it.

https://github.com/nltk/nltk/blob/b0e85694107992e00a2f9fb48e6410c50fe1f1f6/nltk/sentiment/vader.py#L184

You remove those words before handing it text, and you break its ability to detect those idioms. Right?

Other sites also confirm that VADER is intended to be used _without_ processing content ahead of time, such as [here](https://towardsdatascience.com/an-short-introduction-to-vader-3f3860208d53).

> The incredible thing about VADER is it doesn’t require a great deal of preprocessing to work. Unlike with some supervised methods of NLP, preprocessing necessities such as tokenisation and stemming/lemmatisation are not required. You can pretty much plug in any body of text and it will determine the sentiment.

If I understand correctly, the reason for this is because it's a *lexicon* based analysis tool.

Which means that if a word doesn't have a score, the word doesn't impact the score in either direction (unless a separate rule tells it to do so). So words like 'the' and 'to' don't need to be removed, because they don't have scores associated with them.

**Comment by tomaarsen** [comment]
If you intend to analyze them using VADER, then I would not recommend removing the stopwords. In most of the projects I've ran, I don't remove stopwords at all. It's just a tool in the toolkit that may or may not be applicable, depending on the task.

**Comment by JEnduriumK** [comment]
Oh, sorry, I have VADER on the brain lately, and somehow misread this as relating to it. 🤦‍♂️

**Comment by tomaarsen** [comment]
I don't think we need to make changes here. I'll close this accordingly.
