### ISSUE TITLE
Incorrect sentence tokenize for French.

### ISSUE THREAD

**Issue by LeMoussel** [nltk/nltk#3106]
I have observed the following incorrect sentence tokenize for French.
```python
import nltk.data
tokenizer = nltk.data.load('tokenizers/punkt/french.pickle')
tokens = tokenizer.tokenize("Film culte, classique parmi les classiques.Enfin un conte de Noël bien adapté aux tout-petits sans les prendre pour des attardés.")
for sentence in tokens:
    print(sentence)
```
with output:
`Film culte, classique parmi les classiques.Enfin un conte de Noël bien adapté aux tout-petits sans les prendre pour des attardés.`

With [Spacy](https://spacy.io/models/fr), I do this:

```python
import spacy
nlp = spacy.load("fr_core_news_sm")
doc = nlp("Film culte, classique parmi les classiques.Enfin un conte de Noël bien adapté aux tout-petits sans les prendre pour des attardés.")
for sentence in doc.sents:
    print(sentence.text)
```

I have both sentences right. Which is correct.
`Film culte, classique parmi les classiques`.
`Enfin un conte de Noël bien adapté aux tout-petits sans les prendre pour des attardés.`

**Comment by LeMoussel** [comment]
For the moment, I applied this workaround with the use of this regular expression: 

> (?<=[.!?])(?=[^\s])


 - `(?<=[.!?])` positive lookbehind that looks for . ! ?
 - `(?=[^\s])` positive lookahead that matches anything that isn't a space

So this will match positions just after the comma or the space like `phrase.Ceci` or `texte?Cela` but not `mot. Le` and replace with a single space (` `)

**Python code:**

    texte="Film culte, classique parmi les classiques.Enfin un conte de Noël bien adapté aux tout-petits sans les prendre pour des attardés. Un espace après le point?Sans espace après le point d'interrogation."
    texte = re.sub(r'(?<=[.!?])(?=[^\s])', r' ', texte)
    print(texte)

**Output:**

> Film culte, classique parmi les classiques. Enfin un conte de Noël
> bien adapté aux tout-petits sans les prendre pour des attardés. Un
> espace après le point? Sans espace après le point d'interrogation.

**Comment by tomaarsen** [comment]
Hello @LeMoussel,

This is a language-agnostic problem, or quirk might be a better description. I believe that the implementation opts not to consider dots that are not followed by a space as potential sentence breaking points. This way, the model never splits sentences inbetween abbreviations. Otherwise, it may split `U.S.A.` into multiple sentences.

Your workaround should help avoid the problem. In general, any sentence tokenizer works best when sentence seperators are followed by a space, regardless of whether the sentence ends with `.`, `?`, `...`, `!!!`, etc.

I don't foresee that we will be changing this in the future, as we would risk reducing performance elsewhere.

- Tom Aarsen
