### ISSUE TITLE
IBM model 5 issue

### ISSUE THREAD

**Issue by shavetakhepra** [nltk/nltk#3110]
Hi

it keeps me giving this error

__init__() takes 2 positional arguments but 3 were given

**Comment by tomaarsen** [comment]
Hello,

These are cases of user error, for which you should be debugging, searching online and/or posting on stack overflow. This page is meant for issues (hence the name) of the repository. 
As for the error, it's pretty clear: you are initializing a class with too many variables, e.g. `IBMModel5(A, B, C)` instead of `IBMModel5(A, B)`. 

- Tom Aarsen
