### ISSUE TITLE
nltk.Tree ordering

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#319]
It is possible to construct trees `t1` and `t2` so that `t1 > t2` and `t2 > t1`:

```
>>> t1 = Tree("(! (NP foo))")
>>> t2 = Tree("(! (NP foo))", children=[])
>>> t1 > t2
True

>>> t2 > t1
True
```

This is a real issue because it seems that such trees are indeed constructed by ccg module (see #315). 

Comparison methods are defined as follows in nltk.Tree:

```
    def __lt__(self, other):
        if not isinstance(other, Tree): return False
        return self.node < other.node or list.__lt__(self, other)
```

Just deleting all `__le__`, `__eq__`, etc. methods from nltk.Tree fixes the example. 

It seems that `self.node < other.node` causes the issue: when children is empty, self.node is a root node label, and when children is non-empty self.node is a whole string passed to constructor.

Why is `self.node < other.node` part needed?

**Comment by heatherleaf** [comment]
Oh, that's a bug in `__lt__`! Strange that noone has noticed it before. It's _not_ ok to use the following idiom:

```
def __lt__(self, other):
    return self.X < other.X or self.Y < other.Y
```

because this returns True if `self.X>other.X` and `self.Y<other.Y`. This is the right way to do it:

```
def __lt__(self, other):
    return (self.X, self.Y) < (other.X, other.Y)
```

For Trees this becomes:

```
def __lt__(self, other):
    return (self.node, self) < (other.node, other)
```

but this leads to an infinite loop. We need to force Python to use `list.__lt__` instead of `Tree.__lt__`. Like this:

```
def __lt__(self, other):
    return (self.node, list(self)) < (other.node, list(other))
```

I'll fix it and submit a patch

**Comment by heatherleaf** [comment]
Oh, and comparing `self.node` with `other.node` is crucial -- otherwise we cannot distinguish these trees:

```
>>> t1 = Tree("(a x y)")
>>> t2 = Tree("(b x y)")
```

because `t1.node == 'a'` and `t2.node == 'b'`

Note that `Tree(s)` and `Tree(n,ts)` are not at all similar. The 2-argument form is the real constructor, while the 1-argument form is just a shorthand for `Tree.parse(s)`. Personally, I think that's unfortunate: I'd much rather have `Tree(s)` mean `Tree(s,[])`.

**Comment by heatherleaf** [comment]
So there. When that's incorporated, perhaps kmike can add it to the 2to3 branch, and use the @total_ordering decorator?

**Comment by stevenbird** [comment]
Nice work! I would be happy to consider changing Tree(s) to mean Tree(s,[]). The Python 3 port is a good opportunity to clean up such interface issues. I've created a place to put such proposals here:

https://github.com/nltk/nltk/wiki/API-changes-for-Python-3

**Comment by stevenbird** [comment]
@heatherleaf how about submitting a pull request for this, and I'll update master, and @kmike can pull it into 2and3.

NB the @total_ordering decorator is new in 2.7, and we still support 2.6.

**Comment by stevenbird** [comment]
(Oh, I see you already submitted the pull request, thanks.)

**Comment by kmike** [comment]
FYI: I've backported total_ordering in a 2and3 branch (https://github.com/nltk/nltk/blob/2and3/nltk/compat.py) because without it `__cmp__` methods would be tedious to port.

**Comment by heatherleaf** [comment]
yes I've seen that -- but can't compat.py be incorporated in master directly? shouldn't it be easier to merge msater and 2and3 then?

**Comment by kmike** [comment]
I think the plan is to merge 2and3 to master _before_ Python 3 support will be fully implemented (hopefully in 2012) so adding compat.py to master branch now won't provide many benefits.
