### ISSUE TITLE
A potential edge case for WordNetLemmatizer.lemmatize() 

### ISSUE THREAD

**Issue by bowenyi-pierre** [nltk/nltk#3227]
Hello,

I realized that WordNetLemmatizer.lemmatize() would lemmatize word "us" to "u", which is not ideal most of the time. Maybe this issue could be fixed?

Best,
BW

**Comment by ekaf** [comment]
WordNetLemmatizer.lemmatize() always returns the shortest possible lemma. Admittedly, this is often not ideal, but it is _the_ defining feature of that lemmatizer. So rather than changing it, I would prefer using an alternative lemmatizer, or developing a new one.
However, please also consider this [criticism of the WordNetLemmatizer name](https://github.com/nltk/nltk/issues/1978#issuecomment-1888797951).
