### ISSUE TITLE
__cmp__ returns -1

### ISSUE THREAD

**Issue by heatherleaf** [nltk/nltk#324]
In some classes, the `__cmp__` method returns -1 if `type(self) != type(other)`. This has the effect that `x<y` and `y<x` both become true.

The following classes are affected, as far as I can see:

```
featstruct.Feature
parse.chart.TreeEdge
parse.chart.LeafEdge
parse.featurechart.FeatureTreeEdge
parse.pchart.ProbabilisticTreeEdge
parse.projectivedependencyparser.DependencySpan
```

There are two solutions, which one is best?
- Fix `__cmp__(self,other)`. Convert each function like
  
  def **cmp**(self, other):
      if type(self) != type(other): return -1
      return Tree.**cmp**(self, other) or cmp(self.prob(), other.prob())

into something like this:

```
def __cmp__(self, other):
    return cmp(type(self), type(self)) or Tree.__cmp__(self, other) or cmp(self.prob(), other.prob())
```
- Replace all occurrences of `__cmp__` with rich comparisen operators, `__eq__`, `__le__`, etc.

Which one is best? The latter is tedious -- another reason for backporting compat to master.

**Comment by kmike** [comment]
Thanks for the research!

Another option: fix it in a 2and3 branch :) This may be easier than fixing it in master because test running is improved in 2and3 (and there is compat.py). 

+1 for rewriting `__cmp__` with `__eq__`, `__lt__`, etc. We will have to do this anyway for Py3 compatibility. If the fixes are for master branch, it is fine to backport compat.py.

It may be better to raise an exception if the comparison functions don't know how to compare objects. This is one of the things that was systematically fixed in Python 3.x:

Python 2.x:

```
>>> 1 > "5"
False
```

Python 3.x:

```
>>> 1 > "5"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: int() > str()
```

Why would anybody compare featstruct.Feature with parse.projectivedependencyparser.DependencySpan?

**Comment by heatherleaf** [comment]
I didn't know about that change in Py3. I agree we fix it in 2and3 branch. 

I can volunteer, but it will take a few days.

**Comment by kmike** [comment]
This would be great. 

My next TODO item is finishing the unicode support, it won't interfere with comparison fixes.
