### ISSUE TITLE
NLTK word tokeniser splits archaic "[verb]'d" into "[verb]" and "'d"

### ISSUE THREAD

**Issue by Crissium** [nltk/nltk#3320]
Version: nltk==3.8

Example:

```python
>>> nltk.word_tokenize("It is all fill'd vppe with Guttes and Midriffe.")
['It', 'is', 'all', 'fill', "'d", 'vppe', 'with', 'Guttes', 'and', 'Midriffe', '.']
```

The expected result is `['It', 'is', 'all', "fill'd", 'vppe', 'with', 'Guttes', 'and', 'Midriffe', '.']`

**Comment by MohanedMashaly** [comment]
To achieve this in nltk,

you have to use RegexpTokenizer, since word_tokenize does not support this out of box.

Here is a working example, 

```
import nltk
tokenizer = RegexpTokenizer(r'\(['()\w]+|\.)')
tokenizer.tokenize("It is all fill'd vppe with Guttes and Midriffe.")
// output ['It', 'is', 'all', "fill'd", 'vppe', 'with', 'Guttes', 'and', 'Midriffe', '.']

```
I can not argue, wether this is a bug or the intended behavior for nltk, but I believe RegexpTokenizer were made for reasons like this.

Make sure to download('punkt_tab') before trying this code

**Comment by Crissium** [comment]
Thank you for your help, Mohaned!

I think it might be a bug of NLTK because handling such archaisms shouldn't result in any inaccuracies for modern languages. So I perhaps I'll leave this issue open though my original problem has been solved.

**Comment by ekaf** [comment]
@Crissium, the different tokenizers should not all behave in the same way, so that you can pick the one that best suits your task.
