### ISSUE TITLE
Disagreement between comments and code in punkt.py

### ISSUE THREAD

**Issue by alexeyr** [nltk/nltk#362]
https://github.com/nltk/nltk/blob/master/nltk/tokenize/punkt.py#L873

Should the comment say "err on the side of calling our context 'unknown'" instead?

**Comment by stevenbird** [comment]
@jnothman would you please advise?

**Comment by jnothman** [comment]
I think it's a strange use of "err on the side of", but it means: "at the beggining of a line, where we might otherwise think the given token is sentence-internal, we're assuming we have dirty-but-possibly-ostensive line breaks, in which case the token might be sentence-initial; so let's sit on the fence and call it 'unknown'".

Mind you, this is my understanding: I didn't do the original port (and at least this line was in the nltk_contrib version), I don't have the Perl script, and I don't think the CL article talks about line-breaks.

I'll try modify the comment accordingly.

**Comment by jnothman** [comment]
See https://github.com/nltk/nltk/pull/363
