### ISSUE TITLE
Maybe use non-uniform distribution for Baum-Welch by default?

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#373]
See https://github.com/nltk/nltk/issues/100. 

I encountered a suggestion for slightly non-uniform initial probability distributions (uniform + a bit of noize) in some paper (maybe about unsupervised POS tagging), but can't find the reference now. Most papers that employ Baum-Welch use either uniform distributions or distributions learned from  corpora using carefully crafted heuristics.

**Comment by tyleha** [comment]
So as I understand it, and this is based on my advisor's [thesis](http://brl.ee.washington.edu/BRL_Pubs/Pdfs/Th037.pdf) (p.99 especially), a totally uniform distribution where each probable transition begins equivalent to every other results in a local minimum from which the BW algo will not escape. There is no probability gradient on which to update the matrices. Thus, some random jitter in the initialization is necessary. 

Ideally, yes - you would initialize the transition matrix with initial guesses based on learned distributions. However, most algorithms that require unlabeled training algorithms like BW do not have such heuristics in mind, but instead are willing to train a corpus of HMMs using randomly initiated probabilities and then select the HMM that shows best discrimination against some known dataset (this is how I use and evaluate HMMs). 

The most general solution to this problem is to assign the A and B (transition and output) matrices with a random set of probabilities where any value between 0 and 1 is equally probable (a uniform random distribution). Of course you could select a gaussian or a weighted or band-limited, but uniform is the most general. 

Seeing as I can't find much literature discussing the pros/cons of different types of random distributions, I'm happy to submit a pull request with a uniform random distribution function initializing the `HiddenMarkovModelTagger`'s `_transitions` and `_outputs`.
