### ISSUE TITLE
Weird result using NgramModel.prob() function.

### ISSUE THREAD

**Issue by aliannejadi** [nltk/nltk#380]
In the code below:

```
from nltk.corpus import reuters
from nltk.probability import LidstoneProbDist
from nltk.model import NgramModel

def main():
    tokens = list(reuters.words())
    estimator = lambda fdist, bins: LidstoneProbDist(fdist, 0.2)
    model = NgramModel(3, tokens, True, False, estimator)

    print model.prob('said', [''])

if __name__ == '__main__':
    main()
```

The resulted outout is: 3.03175480769 which is impossible since it is a probability and should be below 1. I have encountered many same issues when checking the probabilities of stopwords more often.

Thanks.
MOLi

**Comment by bcroy** [comment]
Hello -

I would not be surprised if this is due to the issue I raised here: #367. That issue is with the backoff calculation, and perhaps you can confirm that when you call `model.prob('said', [''])` the model is backing off to a n=2 or even n=1 model. By the way, what happens when you call `model.prob('said', ['',''])`? Given that if you are building a trigram model, I think the context should be a bigram, not a unigram as you have it in the example...

**Comment by aliannejadi** [comment]
Hello,

Thanks for mentioning issue #367. That's right, it's the same but the other comments you made on it don't seem to be correct. In the same code, check this:

print model.prob('in', ['areas', 'will'])

The output is: 3.18247596154

**Comment by stevenbird** [comment]
@Copper-Head would you please confirm if this issue is current?

**Comment by iliakur** [comment]
@stevenbird This can now be closed, we have a regression test for it.
