### ISSUE TITLE
invalid values passed to numpy log in hmm.py train_unsupervised, possibly due to -np.inf values

### ISSUE THREAD

**Issue by tyleha** [nltk/nltk#385]
#### Issue

numpy.logaddexp2 or numpy.log2 raises non-fatal errors when training a hidden markov model with train_unsupervised, but only on the first iteration when A and B matrices are first being updated.
#### Reproduce

This problem can be reproduced simply by running the nltk.tag.hmm.demo_pos_bw() demo. The warnings raised are shown below:

```
C:\Python27\lib\site-packages\nltk-3.0a1-py2.7.egg\nltk\tag\hmm.py:986:     RuntimeWarning: invalid value encountered in logaddexp2
B_numer[i] = np.logaddexp2(B_numer[i], seq_B_numer[i]-lpk)
C:\Python27\lib\site-packages\nltk-3.0a1-py2.7.egg\nltk\tag\hmm.py:1103: RuntimeWarning: invalid value encountered in subtract
return np.log2(np.sum(2**(arr - max_))) + max_
```
#### Explanation/Solution

I believe the problem stems from the recent change to initialize all matrices to values of `-np.inf` instead of the previous -1e300. The reason is now numpy is being asked to compute a logarithm of 0 since `2**-np.inf == 0`, which raises the warning. When replacing `-np.inf` with -1e300 in `_ninf_array`, the warnings are gone since 2**-1e300 is nonzero. 

Furthermore, there are HMM-specific rationales to "whiten" all transition and output matrices in an HMM by replacing all zero probabilities with small but non-zero probs (I have often seen these as 4*[machine epsilon](http://en.wikipedia.org/wiki/Machine_epsilon) though -1e300 does fine). This prevents any later path calculations through the HMM from blowing up by multiplying by -inf. (For more reference on this, basics are discussed briefly in slide 67 [here](http://disi.unitn.it/~passerini/teaching/complex_systems/slides/HMM.pdf).

@kmike, I think you implemented the `-np.inf` changes and I figure you understand all the impacts of this better than I do - are there any downsides to going back to a non-zero A and B matrices?

**Comment by kmike** [comment]
Hi @tylerhartley, 

Thanks for the heads up.

When I implemented this, reasons were the following:
- it may be desired to have "hard" zeros in transitions (this is mentioned in slide 31 from PDF you referred) - such zeros correspond to -np.inf in log scale;
- based on a comment in the original source code it looked like -1e300 was chosen over float('-inf') because of Python bug (-inf was not supported in Windows in Python < 2.6);

Slide 67 talks about a different issue (input smothing) - nothing prevents transitions & emissions to be smoothed before passing them to HMM (or after the training); I think this is domain-specific task and we shouldn't enforce smoothing. 

So I don't think zero probabilities (approximated by -np.inf) are issue per se. In case of log space such calculations are valid (they mean multiplying by 0 in real space).

I don't understand why, but it seems that train_unsupervised (and DictionaryConditionalProbDist / MutableProbDist) discards smoothing applied to model. I tried to insert "return model" right after 

```
        if update_outputs:
            model._outputs = DictionaryConditionalProbDist(
                dict((s, MutableProbDist(model._outputs[s], self._symbols))
                     for s in self._states))

        return model
```

and print emission probabilities before & after running train_unsupervised; this is the result:

```
In [8]: hmm._outputs_vector('DO')
Out[8]: 
array([-8.64385619, -8.4918531 , -8.4918531 , -8.4918531 , -8.53138146,
       -8.64385619, -8.53138146, -8.4918531 , -8.64385619, -8.4918531 ,
       -8.4918531 , -8.60733031, -8.53138146, -8.53138146, -8.81378119,
       -8.4918531 , -8.53138146, -8.60733031, -8.6794801 , -9.36632221,
       -8.4918531 , -8.4918531 , -8.4918531 , -8.4918531 , -8.60733031,
       -8.4918531 , -8.56985561, -8.56985561, -8.53138146, -8.56985561,
       -8.53138146, -8.4918531 , -8.4918531 , -8.81378119, -8.64385619,
       -8.4918531 , -8.4918531 , -8.56985561, -8.53138146, -8.4918531 ,
       -8.53138146, -8.53138146, -8.53138146, -9.04984855, -8.99435344,
       -8.4918531 , -8.4918531 , -8.53138146, -8.53138146, -8.53138146,
       -8.4918531 , -8.4918531 , -8.6794801 , -8.53138146, -8.53138146,
       -8.4918531 , -8.4918531 ])

In [9]: unlabeled = nltk.tag.hmm._untag(sentences[15:])

In [10]: hmm = trainer.train_unsupervised(unlabeled, model=hmm,
   ....:                                      max_iterations=5)

In [11]: hmm._outputs_vector('DO')
Out[11]: 
array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf])

```

So in my humble understanding this never works, and switching to vectorized numpy (+ "hard" -np.inf) made this issue more visible. 

See also: #379, #69. It looks that my understanding of #69 was incomplete by the way (DictionaryConditionalProbDist should really take existing smoothing in account and I think it is a bug if it doesn't).

There is also a possibility that some non-zero probabilities could unintentionally become zero during training because of numeric instability, but at least in case of demo_pos_bw it looks like this is not what caused warnings.

**Comment by tyleha** [comment]
Thanks @kmike, I think you're correct about 0 probabilities being valid. Whitening should just be performed after the model has been computed.

I should have tracked this error farther down before bringing it here; this appears to be an inconsistency in [numpy log(0) warnings](https://github.com/numpy/numpy/issues/3214), and I'll try and solve the issue over there. In the meantime, these errors could be supressed using [`numpy.sterr`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.seterr.html) if a user wants.
