### ISSUE TITLE
Another issue with NgramModel.prob()

### ISSUE THREAD

**Issue by awahl1** [nltk/nltk#388]
Maybe this is related to Issue #380  and issue #367 .

When I call this function twice on the same word and context, the first time I get a probability value, but the second time I get an error.

corpus = ['one','fish','two','fish']
model = NgramModel(2,corpus)
model.prob('fish','one')

which returns the value 1.0. But then when I immediately call model.prob again on the same bigram, I get an attribute error "'SimpleGoodTuringProbDist' object has no attribute '_intercept'"

**Comment by dan-blanchard** [comment]
This looks to me like more of an error in SimpleGoodTuringProbDist than NgramModel itself (granted there are issues abound with NgramModel right now). It may also have something to do with the fact that NgramModel.prob expects different arguments than you're providing. It should be `model.prob('fish', ['one'])` because the context has to be a list (even with bigram models).

**Comment by stevenbird** [comment]
@Copper-Head would you please confirm if this issue is current?

**Comment by iliakur** [comment]
@stevenbird seeing as the interfaces in the model package are drastically different now, this is no longer relevant. I'd close it.

**Comment by iliakur** [comment]
@stevenbird @alvations we should close this :)

**Comment by alvations** [comment]
Should be outdated given the new Ngram model module now #2077 =)
