### ISSUE TITLE
 I don't understand tokenize.texttiling.py line 322

### ISSUE THREAD

**Issue by laike9m** [nltk/nltk#408]
texttiling.py line322:
`for score in scores[:index:]:`

Recently I studied the texttiling algorithm and found texttiling.py a good implementation of it.
But I just couldn't understand line322,shouldn't that be:
`for score in scores[index:]:`  ?
Since what we want is the right peak,shouldn't we start searching from `index` instead of `0`?

**Comment by laike9m** [comment]
Someone just tell me I was wrong ...Seems that no one ever use texttiling.py?

**Comment by kmike** [comment]
Hi @laike9m, 

First, thanks for the bug report! 

texttiling.py is definitely used by people (see e.g. http://www2.slais.ubc.ca/agarnett/Schneider2011ConsentCanvas.pdf ), but there is a difference between using it and knowing all algorithm implementation details. It looks like the algorithm works, but, as you pointed, it could have errors that result in lower quality.

TextTiling implementation was contributed by G.Boutsioukis in 2010; he is not an active NLTK contributor. In order to review this ticket somebody will have to read the paper and sort out the details again (basically this is what you've done). Alternatively, we could apply the fix you proposed and check if segmentation quality improves - but we can't because there is no evaluation setup for texttiling so we don't know if segmentation quality will improve, and properly checking it will require creating some evaluation data and code.

NLTK is a volunteer project, it looks like none of active NLTK members is using texttiling for work right now, and the barrier for reviewing this ticket looks relatively high, so nobody reviewed it yet. If you want to make it easier for us, there are several ways to help:
- make it easier to check if your problem description is correct (e.g. provide more detailed description, some relevant links and/or links to alternative implementations);
- create some evaaluation data/code that demonstrate that your proposed fix improves segmentation quality.

If you don't have a time for this that's fine - your contribution is already useful, and I think this ticket will eventually get attention, but there is no timeframe for this.

**Comment by laike9m** [comment]
Thank you for your reply @kmike
I think I should get in touch with G.Boutsioukis,can you tell me his email address?

**Comment by kmike** [comment]
The original ticket is https://code.google.com/p/nltk/issues/detail?id=505; you can find George contacts here: https://code.google.com/u/gboutsioukis/

**Comment by stevenbird** [comment]
Note that there is an earlier loop over scores[index::-1], the mirror-image of scores[:index:], so if one of these is wrong, then they are both wrong. Since the loops compute lpeak and rpeak, which are summed, it hardly matters which directions the loops go, so long as they are the reverse of each other.

**Comment by laike9m** [comment]
@stevenbird `[index::-1]` is right,but `[:index:]` isn't
![ttt](https://f.cloud.github.com/assets/2592205/616627/08a5a68c-ce76-11e2-94b3-dc5179926c39.jpg)

Let's say `index` is 3,i.e. the number `1`.If i'm not mistaken(of course I could be),the lpeak is `7` and rpeak is `6`.
As the pic shows,we can find the lpeak `7` but we can't find rpeak `6`,since we started from the wrong place.

**Comment by laike9m** [comment]
@kmike 
Thank you!

**Comment by laike9m** [comment]
@kmike I've talked to George,he's now reviewing the code.

**Comment by kmike** [comment]
@laike9m what is the state of this ticket? Did you get an answer from George?

**Comment by laike9m** [comment]
@kmike I was hoping that he could give me an answer, but nothing happened after George said he'll review it.I still think the original code is wrong, and I used the peraonal-modified version in my project.

**Comment by stevenbird** [comment]
I agree that the existing code is suspect, and we should probably replace [:index:] with [index::], to search the second half of the string. I'll check the original paper first. http://www.aclweb.org/anthology/J97-1003.pdf

**Comment by stevenbird** [comment]
I believe @laike9m is right. Thanks for the bug report. Resolved in https://github.com/nltk/nltk/commit/0d43779e9f55d53cb8378f9fedfccc92f53925f1
