### ISSUE TITLE
Getting unexpected results

### ISSUE THREAD

**Issue by zotz** [nltk/nltk#413]
Working on a little something:

https://github.com/zotz/partystory_pythonutils

based around nltk and am getting unexpected results. This may just be me misunderstanding things in general, it may be me misunderstanding the limits of the current state of the tech, it may be coding errors on my part.

I would appreciate it if an interested party would run psauto.py against a novel from Project Gutenberg for instance and then run psatest.py against the created data files and look at the quality of the generated sentences and see where the issue may lie. If this does not belong here, I would appreciate a pointer to where it properly belongs.

I would expect the generated sentences to be properly formed gibberish. What I am getting is improperly formed gibberish. From what I see, the problem comes in in the creation of the files by psauto.py.

all the best,

drew

**Comment by kmike** [comment]
Hi Drew,

Such questions are better suited to https://groups.google.com/forum/?fromgroups#!forum/nltk-users mailing list; I think that's why you haven't got an answer here. 

A side note: it is much easier to persuade somebody to debug/review your code if there is clear description of the specific problem - it is much harder to get a code review from a person on Internet if the issue is "my program doesn't work as expected, could you please check why".
