### ISSUE TITLE
ValueError: A 0.7-series setuptools cannot be installed with distribute.

### ISSUE THREAD

**Issue by johbub** [nltk/nltk#424]
I followed the installation instructions at http://nltk.org/install.html. When running install -U nltk i get the above error.
Python: 2.7.3; Ubuntu 12.04.

**Comment by pfeyz** [comment]
It looks like the installation instructions refer to setuptools 0.6c11 (0.7 is pretty new). Did you install setuptools 0.7.5 ? I was able to reproduce the behavior you described w/ 0.7.5 because [Distutils prevents you from installing setuptools-0.7](https://pypi.python.org/pypi/setuptools/0.7.5#upgrading-from-distribute), but installation worked with 0.6.
