### ISSUE TITLE
Consistency with properties

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#475]
We should audit the NLTK API to make sure we are being consistent with the use of properties. E.g. why do we have Tree.node and Tree.leaves()?

**Comment by heatherleaf** [comment]
Because .node is a stored value and .leaves() are calculated.

**Comment by stevenbird** [comment]
Right, though this distinction is not transparent to students whose only exposure to programming is a course on Python for NLP.

**Comment by heatherleaf** [comment]
Another distinction that is perhaps easier is that properties are mutable but methods are not. 

But then we get into trouble with ProbabilisticTree.prob(), which is mutable and has a setter method .setprob(x). The reason for this is probably to be consistent with ProbDists which have methods .prob(x), but that is definitely not transparent.

The most consistent would be to get rid of all properties and start using get- and set-methods (.node() resp .setnode())

**Comment by paulproteus** [comment]
@stevenbird , curious if you agree with @heatherleaf 's proposal.

**Comment by stevenbird** [comment]
There's too many options here, and the goal is to keep NLTK pythonic, simple, and consistent. (Simplicity trumps consistency: http://www.jwz.org/doc/worse-is-better.html). Where setting a property requires some logic then I think it makes sense to use get- and set-methods (http://tomayko.com/writings/getters-setters-fuxors).

I don't understand the suggestion to get rid of all properties and start using get- and set-methods instead, since the latter still leads to user code that accesses member variables using the property syntax.

**Comment by kmike** [comment]
Yes, that there are too many options here. Also, any solution that converts methods to properties will break a lot of code, so it is better to handle it before NLTK3. 

This is what we can do for Tree class:
- make height(), leaves(), productions() and pos() properties. We can't make subtrees() property as-is because it has a parameter. Other methods also have parameters, or they make no sense as properties. So still, some attributes will be properties and some will be methods. I'd make some of these functions properties if started from a clean sheet, but this doesn't fix the problem entirely, and changing them now could break a lot of code, including examples from a printed version of NLTK book (e.g. ch8, Weighted Grammar).
- rename some methods to become verbs: get_height(), get_leaves(), get_productions(), get_pos(), get_subtrees(), etc. By this logic students could learn that every method that computes something must be prefixed with 'get_' or named as verb. I think this assumption is wrong, and there are methods named after nouns without 'get_' prefix everywhere in NLTK, in standard library and in other Python packages. This is a respectable approach IMHO, but it could be hard to enforce in practice.
- Make node attribute private (or just undocumented, or just do nothing about node attribute) and create a get_node()/set_node() methods (without creating a property). Tree will become consistent (there won't be emphasis on 'node' property), but other classes won't, and we're introducing an unnecessary layer of abstraction.

I agree that node/leaves distinction is not intuitive - I recall having this problem myself while using Tree class for the first time. 

But all ways (including "don't change anything") look controversial and have their own drawbacks. In such situation I'd vote -0 for changing anything.

I think that to move this ticket forward it is better to have some concrete proposals on table, and that general properties overhaul based on some prescribed rules is too hard and will break too much things.

**Comment by fcbond** [comment]
My students also find this a problem (and I confess I often also have trouble remembering.

I must admit I am drawn to heatherleaf's make everything look like a method solution.

Another thing that would really help is to show the description in the documentation.

For example:

dir(wordnet.synsets('dog')[0])
['**class**', '**delattr**', '**dict**', '**doc**', '**eq**', '**format**', '**getattribute**', '**hash**', '**init**', '**module**', '**ne**', '**new**', '**reduce**', '**reduce_ex**', '**repr**', '**setattr**', '**sizeof**', '**str**', '**subclasshook**', '**weakref**', '_iter_hypernym_lists', '_lemma_pointers', '_pointers', '_related', '_wordnet_corpus_reader', 'also_sees', 'attributes', 'causes', 'closure', 'common_hypernyms', 'definition', 'entailments', 'examples', 'frame_ids', 'hypernym_distances', 'hypernym_paths', 'hypernyms', 'hyponyms', 'instance_hypernyms', 'instance_hyponyms', 'jcn_similarity', 'lch_similarity', 'lemma_infos', 'lemma_names', 'lemmas', 'lexname', 'lin_similarity', 'lowest_common_hypernyms', 'max_depth', 'member_holonyms', 'member_meronyms', 'min_depth', 'name', 'offset', 'part_holonyms', 'part_meronyms', 'path_similarity', 'pos', 'res_similarity', 'root_hypernyms', 'shortest_path_distance', 'similar_tos', 'substance_holonyms', 'substance_meronyms', 'tree', 'verb_groups', 'wup_similarity']

I this could show e.g. hypernym_paths() for methods, it would be quite helpful.

**Comment by stevenbird** [comment]
I would like to propose the following for tree.node. It is close to @kmike's third option, but using node() and set_node() methods, following the practice in probability.py with discount()/set_discount(), prob()/set_prob(), and logprob()/set_logprob().

https://github.com/nltk/nltk/pull/502

**Comment by stevenbird** [comment]
Can anyone point out the other cases of properties that should be converted to methods?

**Comment by heatherleaf** [comment]
Here are all the defined properties I found by some simple grepping and searching:

```
align.AlignedSent: words, mots, alignment
data.FileSystemPathPointer: path
data.ZipFilePathPointer: zipfile, entry
data.SeekableUnicodeStreamReader: closed, name, mode
downloader.Downloader: url, download_dir
featstruct.Feature: name, default, display
tree.ImmutableTree: node
classify.maxent.GISEncoding: C

inference.api.TheoremToolThread: result
inference.mace.MaceCommand: valuation

draw.table.MultiListbox: column_names, column_labels, listboxes
draw.table.Table: column_names

sem.drt.AbstractDrs: type
sem.evaluate.Valuation: domain, symbols

sem.logic.AnyType: first, second
sem.logic.ApplicationExpression: type, pred, args
sem.logic.IndividualVariableExpression: type
sem.logic.LambdaExpression: type
sem.logic.QuantifiedExpression: type
sem.logic.NegatedExpression: type
sem.logic.BinaryExpression: type

tag.crf.MalletCRF: filename, feature_detector
tag.senna.SennaTagger: executable
tag.sequential.SequentialBackoffTagger: backoff
tag.stanford.StanfordTagger: _cmd
tag.stanford.POSTagger: _cmd
tag.stanford.NERTagger: _cmd

tokenize.punkt.PunktLanguageVars: _re_sent_end_chars
tokenize.punkt.PunktToken: type_no_period, type_no_sentperiod, first_upper, first_lower, first_case, is_ellipsis, is_number, is_initial, is_alpha, is_non_punct

corpus.reader.api.CorpusReader:: root
corpus.reader.nombank.NombankInstance: roleset, tree
corpus.reader.propbank.PropbankInstance: baseform, sensenumber, predid, tree
corpus.reader.util.StreamBackedCorpusView: fileid
```

Personally I think that many of these could equally well be methods. Especially those that are private anyway (e.g., `_cmd`, `_re_sent_end_chars`).

**Comment by dan-blanchard** [comment]
Maybe it's too late to chime in here, but I personally find properties much more Pythonic and would prefer moving toward them instead of away from them. My vote is for @kmike's first option.

**Comment by stevenbird** [comment]
@heatherleaf thanks for identifying the properties.
@dan-blanchard this doesn't address the concern, namely how users are meant to tell when something is a property (are you saying that any parameter-less method should be a property?)

Right now, a user has to understand the difference between a stored attribute and something that is computed. This depends on the particular implementation, and its usually not transparent without reading the code. Making more extensive use of properties will only make the problem more acute for our users, I think.

**Comment by dan-blanchard** [comment]
I don't believe that knowing the difference between a stored attribute and something that's computed is a burden on the user. Regardless of whether they're implemented via the property built-in or just plain old member variables, there are always methods and properties for any class in any object-oriented language. This is something that a user---someone who is presumably a programmer, or learning to become one---should be able to keep straight. The idea of cluttering up a very nice Python API with Java-style getter/setter methods is something I find completely unappealing. Even the second article you linked to seemed to agree with Phillip J. Eby's argument that getters/setters should not be used in Python unless setting things requires some logic, and even then wrapping them as a property is the cleaner approach.

Being able to easily tell what has to be computed on the fly vs. what is stored is very helpful to users of the API, because then they can determine whether the value is something that should be stored in a variable if they're using it multiple time, or whether they can just access the property directly. That said, if the choice is between making all no-argument methods that return something into properties, or using lots of explicit getter/setters, I am 100% in favor of making everything a property.

**Comment by fcbond** [comment]
G'day,

On Fri, Oct 11, 2013 at 9:39 PM, Dan Blanchard notifications@github.comwrote:

> I don't believe that knowing the difference between a stored attribute and
> something that's computed is a burden on the user. Regardless of whether
> they're implemented via the property built-in or just plain old member
> variables, there are always methods and properties for any class in any
> object-oriented language. This is something that a user---someone who is
> presumably a programmer, or learning to become one---should be able to keep
> straight. The idea of cluttering up a very nice Python API with Java-style
> getter/setter methods is something I find completely unappealing. Even the
> second article you linked to seemed to agree with Phillip J. Eby's argument
> that getters/setters should not be used in Python unless setting things
> requires some logic, and even then wrapping them as a property is the
> cleaner approach.
> 
> I agree that this is something a serious programmer should not have trouble
> with.  However, I teach computational linguistics to linguists: students
> whose only programming experience is with this (and I think this is
> reasonably common).  Having to know the difference between a stored
> attribute and something that's computed is a real burden for these
> students.    I think it it very valuable to make at least some of the power
> of programming accessible to someone who is neither a programmer, or
> learning to become one.
> 
> Being able to easily tell what has to be computed on the fly vs. what is
> stored is very helpful to users of the API, because then they can determine
> whether the value is something that should be stored in a variable if
> they're using it multiple time, or whether they can just access the
> property directly. That said, if the choice is between making all
> no-argument methods that return something into properties, or using lots of
> explicit getter/setters, I am 100% in favor of making everything a property.
> 
> It is possible to do many useful an interesting things without being so
> computationally intensive we need to care about whether to store things or
> recompute them.

I think the problem with many of the wordnet methods is that sometimes they
take arguments:
so wn.all_synsets() can take a pos: wn.all_synsets('n') and thus it cannot
be a property.  So making everything a property is (unless I am missing
something) not really feasible.

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by stevenbird** [comment]
@dan-blanchard I completely agree about avoiding Java-style getters and setters. I think the point about knowing when to save a result in a local variable is a bit of a red herring when the language may do its own optimisations behind the scenes (or the method may be explicitly memoised). In the case of Tree, the setter is built into the initialiser and it will be unusual to call Tree.set_label() explicitly. The getter is called Tree.label() so there's no issue here.

**Comment by stevenbird** [comment]
I've updated https://github.com/nltk/nltk/pull/502 to provide Tree.set_label() and Tree.label(), and to raise an error when Tree.node is used. It would be great if someone could test this please.

**Comment by stevenbird** [comment]
Next step is to audit @heatherleaf's list and decide what else should be a method instead of a property. Anything internal or in modules that are typically only used by non-beginners can probably stay as is.

**Comment by stevenbird** [comment]
@fcbond mentions that @heatherleaf's list omits the wordnet attributes. There's a forthcoming contribution of an interface to the Global WordNet Grid in which some of these attributes (like "definition") would need to become methods that take a language parameter.

**Comment by heatherleaf** [comment]
I only did some simple grepping for the strings `@property` and `property(`, so I'm sure I missed some.

**Comment by stevenbird** [comment]
I proposed to replace the WordNet Synset and Lemma properties with methods having the same name, and with no setter methods.

**Comment by fcbond** [comment]
and can we also do definition and example?

On Fri, Oct 18, 2013 at 7:48 AM, Steven Bird notifications@github.comwrote:

> I proposed to replace the WordNet Synset and Lemma properties with methods
> having the same name, and with no setter methods.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/475#issuecomment-26559608
> .

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by stevenbird** [comment]
Yes, I'll include those.

**Comment by stevenbird** [comment]
The wordnet properties have been changed to methods in https://github.com/nltk/nltk/commit/ba8ab7e23ea2b8d61029484098fd62d5986acd9c

**Comment by watercrossing** [comment]
Good afternoon
i realise that this issue is 5 months old - but I have just pulled the latest develop and @stevenbird 's pull request broke a lot of my code. 
I am not sure why these methods are necessary: none of these attributes require any computation, and they just clutter the code a lot. This is not pythonic - it looks like java. It also makes `dict()` even larger, as now not just `name`, but `_name` and `name()` are present.  

In order to keep some backward compatibility, I suggest adding `@property` decorators for these properties - but then this will increase the clutter even further. I entirely agree with @dan-blanchard - everything should be properties. Python does not have the distinction between `private` and `public` methods/attributes to make the api 'nicer', but it keeps the code short and easy to read. https://mail.python.org/pipermail/tutor/2012-December/092993.html describes this point well. 

I do agree that there can be confusion about why something is a method or an attribute, but the standard libraries make this distinction quite clear (see for example http://docs.python.org/2/library/stdtypes.html#file-objects): properties are things that a class has - for example an identifier, a status, while methods represent actions on the class. Of course there is some overlap, which has to be resolved on a case by case basis.

I do agree with @fcbond as to the complexity of the Synset class. But adding more methods does not really help here - the class needs refactoring and a rethink.

**Comment by stevenbird** [comment]
@watercrossing unfortunately its rather late to be giving us this input! I share the aversion to Java style setters and getters. We have almost no setters, and so the getters are never `get_property()` but just `property()`. The point that "everything should be properties" wasn't really sustainable, and you yourself talk about the need to decide on a case-by-case basis. In many cases, the distinction between "things that a class has" and "actions on a class" seems to depend on knowledge of the implementation, if a user is to know that it is `Tree.node` vs `Tree.leaves()`. We don't want to expect users to have to guess.

This is just one of a large number of API changes for NLTK 3, which have been under review for months, and occasionally discussed on nltk-dev. Please see our full list here.
https://github.com/nltk/nltk/wiki/Porting-your-code-to-NLTK-3.0

**Comment by watercrossing** [comment]
Thank you for the reply @stevenbird. I do realise that I am a bit late to this discussion - would it be too much to ask to at least keep backwards compatibility with `@property` decorators? That way users will get the benefit of having the unified getter methods and their old code will not need to be changed.

I will try to join these discussions earlier in future!
