### ISSUE TITLE
module or protocol for POS tagset specification and conversion

### ISSUE THREAD

**Issue by nschneid** [nltk/nltk#483]
Given the importance of part-of-speech tags in corpora and NLP applications, it seems that NLTK would benefit from a standard way to **encode, document, and convert among different tagsets**. For example, a module might be added for each tagset that lists all the tags, with a description and examples of each, and provides groupings/morphosyntactic features or mappings to more general POS categories.

Special cases of such functionality have been requested multiple times, e.g.:
- the "universal" tagset of Petrov, Das, & McDonald, #316 
- the BNC tagset as used in FrameNet vs. the Penn Treebank tagset

I often find myself writing one-off functions like `isNominal(pos)` or `isFunctionWord(pos)`, and in a few cases have attempted to systematize particular tagsets (see https://gist.github.com/nschneid/4231292 and https://gist.github.com/nschneid/6476715). @brendano similarly has a conversion script: http://brenocon.com/bnc_ptb.py But I know of no general solution to this problem. There are many subtleties that can arise in implementing such routines, so having a standard implementation of some of the common cases should promote comparability and replicability of systems that group or map POS tags.

To make this easily extensible as new corpora (or standalone tagsets) are added, perhaps there should be a way for a corpus reader to register a tagset with a master list of all NLTK tagsets, and specify conversions where applicable. Corpora and taggers could then make explicit which tagset they use.

Things to consider:
- What information should be available to converters in order to be as accurate as possible? Just the source tag/tagset and target tagset? The source word? Full sentences?
- The interaction between tagsets and tokenization schemes. For example, not all tagsets require clitics like _'s_ to be separated; and some but not all expect hyphens to be separated. Mismatches might call for modifying the tokenization as part of the tag conversion process, though the user should probably have the option to override this.

**Comment by nschneid** [comment]
another resource along these lines: http://ufal.mff.cuni.cz/wiki/user:zeman:interset

**Comment by kmike** [comment]
I don't have experience with English tagsets, but I have some experience with Russian tagsets (https://github.com/kmike/russian-tagsets). Readme is in Russian, sorry :) There are conversion functions for 5 tagsets implemented in that library. The idea is the following:
- each tagset module defines conversion routines to/from other tagsets - they are just functions that take a single tag from one tagset and return a single tag from an another tagset;
- these conversion functions are added to registry;
- there is a "main" function that for a given pair of tagsets returns a function that converts between these tagsets (maybe using an intermediate step(s) - it can find a conversion path because all conversion functions are registered);
- there is also a "rules engine" that allows to define conversions using simpler format (example: https://github.com/kmike/russian-tagsets/blob/master/russian_tagsets/ruscorpora.py) - there is no need to use it for tagset conversion routines, but for complex cases it is much easier to work with. Each tag consists of comma-separated "grammemes", and rules define how to replace grammemes of one tagset with grammemes from other tagset, both individually or in groups; there is an option to remove unprocessed grammemes.

What I learned:
- tagset conversion is a complex task; 
- at least for Russian it is very hard to create a nice table like https://gist.github.com/nschneid/6476715 because there are > 4000 possible tags in some of tagsets, and for these tagsets not all tags maps 1-to-1;
- tagset conversion is usually lossy, at least for 2 reasons: (a) one tagset can be more "detailed" and (b) tagsets can have overlapping tags for some words, i.e. tag conversion depends on word itself - (b) is most annoying and hard to deal with;
- in practice, there is no "universal" tagset; even most detailed tagsets can't encode all information from other tagsest;
- tagset conversion quality is important;
- it is bad to rely on tag conversion "chains" because tagset conversion quality is important, but for a large number of tagsets a number of direct conversion functions grows too fast;
- tagset conversion should be avoided when possible

just my 2c

**Comment by brendano** [comment]
Interesting set of issues.  As for the function interface for source=>target tag conversion, you could imagine three levels of more and more input information.
1. The source tag
2. The source tag, and the word form (specifically, just the raw surface string, I think)
3. The input sentence (as a sequence of tokens and tags), and the index of which token is to be converted

In all cases, the output is just the target tag.

Some conversions will be ok with (1), some will do better with (2), and in the extreme, contextual disambiguation could be done with (3).  I suspect that (2) would be a reasonable compromise.  For truly ambiguous conversions, like from the coarse Petrov tagset into a finer-grained one, that's going to require (3) and ideally a statistical model for better accuracy.

I was expecting that the main use case for this sort of thing is to massage data in one tagset into another that you already have a different processing system that's designed to use it, so lossiness in the conversion is inevitable.

To be more specific on the interfaces -- I'm not familiar with how NLTK prefers to structure sentence and tagged token data, but here's a straw proposal that uses just simple lists of strings and such.  The `source_tagset` and `target_tagset` parameters would refer to some sort of global registry of known tagsets (mentioned in a comment above).

(1)

```
def convert_tag(source_tag, source_tagset, target_tagset='WSJPTB'):
    """source_tag: is a string"""
```

(2)

```
def convert_tag_with_word(source_tag, source_word, source_tagset, target_tagset='WSJPTB'):
    """source_tag: string, source_word: string"""
```

(3)

```
def convert_tag_in_context(index, sentence_words, sentence_tags, source_tagset, target_tagset='WSJPTB'):
    """
    index: integer, in [0..N)
    sentence_words: list of strings, length N (the words of the sentence)
    sentence_tags: list of strings, length N (the source POS tags of the sentence)
    """
```

(4) Might as well have a whole-sentence conversion routine too...

```
def convert_sentence_tags(sentence_words, sentence_tags, source_tagset, target_tagset='WSJPTB'):
    """
    Converts all the tags in a sentence, with whatever the most appropriate implementation is supported for this tagset pair.
    Returns list of strings length N: the tags in the target tagset.
    """
```

**Comment by stevenbird** [comment]
+1 to @nschneid's suggestions. This functionality would be extremely useful to have! It would be good to decide on the interface before 3.0 is finalised.

Note that the tagged corpus readers support tag mapping already, and we could think about generalising this interface (replacing the simplify_tags flag with a tagset specification). Also, we provide access to tagset documentation in help.py.

https://github.com/nltk/nltk/blob/master/nltk/corpus/reader/tagged.py
https://github.com/nltk/nltk/blob/master/nltk/tag/simplify.py
https://github.com/nltk/nltk/blob/master/nltk/help.py

**Comment by stevenbird** [comment]
How about I change the simplify_tags flag to a tagset parameter:

> brown.tagged_sents(categories=['news', 'mystery'], simplify_tags=True)

becomes:

> brown.tagged_sents(categories=['news', 'mystery'], tagset='simple')

and it wouldn't be hard to go the further step to the Das/Petrov/McDonald universal tagset

> brown.tagged_sents(categories=['news', 'mystery'], tagset='universal')

**Comment by nschneid** [comment]
Sounds good. I assume the default is then `tagset='brown'`?

**Comment by heatherleaf** [comment]
+1 for adding a `tagset` parameter

**Comment by stevenbird** [comment]
The previous default was simplify_tags=False. Now it needs to be whatever is native to a given corpus. In the case of the Brown Corpus, it is easy, and we would have tagset='brown'. In the case of the tagged_words() method (in corpus/reader/tagged.py), we don't know which corpus is being used at the point the default is being set. So we probably should not specify a default in such methods. We need revisit the LazyCorpusLoader interface, and replace its tag_mapping_function parameter.

**Comment by stevenbird** [comment]
I would like to replace NLTK's existing support for a simplified tagset with this universal tagset. I've added the universal tagset data from https://code.google.com/p/universal-pos-tags to NLTK's data collection (#79 http://nltk.org/nltk_data/). @nschneid I would like to adapt your code (https://code.google.com/p/universal-pos-tags/source/browse/trunk/universal_tags.py) -- any objections?

**Comment by nschneid** [comment]
@stevenbird Sounds good to me!

**Comment by stevenbird** [comment]
Please review this pull request. I think this issue is the last interface change before we release 3.0 beta.

**Comment by SumeetSandhu** [comment]
Hi, I have a specific need - to convert Brown tags to Penn Treebank tags. Is there 'official' code that does that? 

The painful solution = read https://catalog.ldc.upenn.edu/docs/LDC95T7/cl93.html and map manually. Unfortunately this link doesn't articulate an exhaustive mapping and I don't want to guess at linguistics.

I do need the full Penn tags - not the NLTK simplified set - as the tag subcategories are useful in my chunking grammar (currently written using Penn tags). The Brown corpus has specialized categories that are better for training taggers (e.g. 'learned' is a good category for tagging scientific/legal documents). However Brown corpus misses some words, so I think I'll need to use the Penn as a backoff tagger.

**Comment by nschneid** [comment]
> Hi, I have a specific need - to convert Brown tags to Penn Treebank tags. Is there 'official' code that does that?

This is apparently not supported in NLTK yet, but see Dan Zeman's [Interset](https://wiki.ufal.ms.mff.cuni.cz/user:zeman:interset) tool or my script at https://gist.github.com/nschneid/6476715 – specifically, `brownSequence2ptb()`.

**Comment by stevenbird** [comment]
This would be welcome functionality if anyone wanted to add it.

**Comment by SumeetSandhu** [comment]
thank you Nathan - I will start with your list in POSMappings.txt and perhaps edit a bit - hoping I can avoid compound Brown tags for formal/scientific texts.
