### ISSUE TITLE
Sequence methods should return iterators by default

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#509]
Methods that return sequences should produce iterators by default following standard practice in Python 3; there should be no special _iter methods.

**Comment by stevenbird** [comment]
This change has been made for parse.generate() in https://github.com/nltk/nltk/commit/d7784cc454b6adb1e358c14491feb0690be88294

**Comment by kmike** [comment]
I found it useful that many NLTK methods return lists and not iterators because it makes interactive work easier (slicing, printing, concatenating). 

Iterators are good when memory consumption matters or when they prevent unnecessary work. I think it is better not to switch to iterators when memory consumption is not an issue and there is not a lot of unnecessary work.

**Comment by stevenbird** [comment]
I agree. Its a balance. We should only do it for objects that are large or expensive to compute.

**Comment by stevenbird** [comment]
Closing for now, since it hardly effects the interface. It just means that in some situations a user must wrap a call with `list()`.
