### ISSUE TITLE
classifier API

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#58]
Classifiers are trained using a factory function, e.g.:

  nltk.NaiveBayesClassifier.train(train_set)

N-Gram taggers used to be trained like this too, but we changed them to do
training in constructor, e.g.:

  nltk.BigramTagger(train_sents)

NEChunkParserTagger, NGramModel, FreqDist, and ConditionalFreqDist are also
initialized with data to the constructor.  So how about:

  nltk.NaiveBayesClassifier(train_set) ?

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=316</p><hr/><h2>earlier comments</h2>
<p><strong>peter.ljunglof@heatherleaf.se said, at 2009-04-02T18:05:16.000Z:</strong></p>
<p>The BrillTaggerTrainer (and Fast-) also have train methods, perhaps they could be cleaned too?

>>> trainer = nltk.BrillTaggerTrainer(basetagger, templates)
>>> tagger = trainer.train(training_data)

How about this instead:

>>> tagger = nltk.BrillTaggerTrainer(basetagger, templates, training_data)

</p><p><strong>StevenBird1 said, at 2009-05-04T01:11:41.000Z:</strong></p>
<p>It would be good to resolve this in 0.9.9
</p>

**Comment by larsmans** [comment]
Or: adopt the scikit-learn convention that construction and training are two separate operations. In sklearn, when constructing a classifier or other estimator, one just sets the metaparameters, while at training time, one fits the data-dependent parameters (including number of features and number of classes) to the training data. This is in fact how the scikit-learn wrapper in NLTK works: a `SklearnClassifier` is constructed from a scikit-learn one, then fit to data with its (non-static) `train` member function.

When I first started using scikit-learn, I was surprised by this convention, but it turns out it works really well and is useful in situations like cross validation.

**Comment by kmike** [comment]
+1 for adopting scikit-learn API if such breaking changes are feasible.
