### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#597]
It looks like our continuous integration testing service at ShiningPanda has gone away. NLTK has been queued at position 214 for three weeks now. We need to find another service. A small fee is fine.
https://jenkins.shiningpanda.com/nltk/job/NLTK-TOX/

**Comment by stevenxxiu** [comment]
There's a jenkins hosting program on cloudbees: http://www.cloudbees.com/foss/foss-dev.cb
Their free plan seems to be enough for nltk.

**Comment by stevenbird** [comment]
I've applied for a free plan.

**Comment by stevenbird** [comment]
We've been given a free plan, so let's try it out.

**Comment by stevenbird** [comment]
We need to check if they will install the C libraries required to compile numpy.

**Comment by stevenxxiu** [comment]
Their python plugin (https://developer.cloudbees.com/bin/view/DEV/Python) seems to resolve the numpy install issue, but does not appear to have tkinter compiled in which causes some test-running errors.

I don't think tkinter is necessary to run tests, so maybe the tkinter import code in `nltk.compat` can be skipped while running tests. Is this the case?

The tests are running here now: https://nltk.ci.cloudbees.com/

**Comment by stevenxxiu** [comment]
Scipy is now installed on cloudbees jenkins.

Numpy source code indicates that it requires library extension names ending with *.so, so it wasn't able to find the libraries.

I added a script there to manually copy the libraries to the home directory with the correct file names. There should be no more dependency errors in the jenkins console log.

**Comment by stevenbird** [comment]
@xim has also set up CI at https://travis-ci.org/xim/nltk

**Comment by kmike** [comment]
Travis is great, and it'll be a big win if it will be working for us - one advantage is that it is integrated with github and runs on pull requests, so we can check them before merging without running tests manually.

**Comment by xim** [comment]
The Shining Panda folks reactivated our account, they said we have had out jobs there stopped manually for long enough that they were automatically deleted. Maybe someone pressed “Customize build” and forgot to unlock it afterwards, or otherwise accidentally deactivated the job. If we want to stay on Jenkins, I suggest we stay there. They allow you unix user access to install and build whatever you want.

Travis allows us to install Debian packages, and also to download prebuilt stuff on demand. So if we make a tarball with anything that may be missing, we can get the Stanford tagger etc. running there as well. Coverage reports can be produced using coveralls, if we care.

Some pros of Travis?
- Github integration comes easy, it runs on pull requests and all pushes.
- No state is kept, so a travis setup config has all steps needed for a full test setup, which documents requirements including external java crack etc.
- Setup (except the complexities of NLTK itself) should be quite easy to read.

Vs the cons?
- Does not have the same amount of plugins etc. available. If we want e.g. coverage reports, we need a separate account on a separate free system.
- Downloads/builds all depenencies on every run, which can be slow.

**Comment by stevenbird** [comment]
The processing of pull requests is very attractive.

Is there a cost factor? A few months back we exceeded some limit and I paid ShiningPanda $50 so we could do at least one build per day. What's the deal at Travis-ci?

What swrvice do Travis projects typically use for coverage?

**Comment by stevenbird** [comment]
How about Coveralls? Looks easy to configure. https://coveralls.io/r/nltk/nltk

**Comment by cash** [comment]
Travis-CI is free for open source projects. They have corporate sponsors for this service and in the past have done fund raising from individuals (http://love.travis-ci.com/). It is great advertising for their service.

They have a hard limit of 50 minutes for a run. There are ways to speed up really long builds by caching artifacts in something like S3 and downloading them rather then rebuilding them each time.

I have less experience with coveralls but it's also a nice tool.

**Comment by stevenbird** [comment]
Thanks @cash. Well, I'm on for trying Travis and Coveralls. There's no harm in leaving the Jenkins instance at Shining Panda for now.

**Comment by stevenbird** [comment]
Closing, since our CI service at ShiningPanda is meeting our needs atm.
