### ISSUE TITLE
Alpha testing

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#600]
Run tests locally, and deal with any remaining failing tests (including 3rd party software).

**Comment by stevenbird** [comment]
We can now see failing tests at https://nltk.ci.cloudbees.com/job/nltk/lastSuccessfulBuild/testReport/

**Comment by jnothman** [comment]
Does NLTK currently have a solution for docstring-testing outputs that include `u'...'` in Py2 and `'...'` in Py3?

**Comment by kmike** [comment]
@jnothman yes, these strings should be considered the same by our nose plugin - see https://github.com/nltk/nltk/blob/develop/nltk/test/doctest_nose_plugin.py#L15. Output checker removes `u` string prefixes from the output using a regex. It may occasionally match something extra, but the issue is too common, so this behaviour is enabled by default.
