### ISSUE TITLE
Boolean values

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#621]
Use `True` and `False` instead of `1` and `0` for readability.

**Comment by Liechti** [comment]
I took the results from
 `grep -rn "return [01]" .`
and went through the list, dividing it into "Change" and "No Change" (see the full list [here](https://gist.github.com/Liechti/11312842)). Please a take look to see if there is more that needs to be done.

Also the documentation for the `step` method in the `SteppingRecursiveDescentParser` class should be changed from `return: 0` to `return: None` in order to match the code.
