### ISSUE TITLE
internals.Counter vs collections.Counter

### ISSUE THREAD

**Issue by heatherleaf** [nltk/nltk#632]
The class `internals.Counter` clashes with `collections.Counter`, we should rename it.

It is used in `inference/tableau.py` and several files in the `sem` package, nowhere else.

**Comment by ams-bjones** [comment]
Since "internals.Counter" is for unique naming, Could "internals.UniqueNumber", be used instead?

**Comment by stevenbird** [comment]
How about UID? Or UniqueIdentifier?

**Comment by jnothman** [comment]
Delete it.

Replace:

``` python
_counter = internals.Counter()
id = _counter.get()
```

with:

``` python
id_generator = itertools.count()
id = next(id_generator)
```

**Comment by stevenbird** [comment]
Good idea, thanks.

**Comment by ewan-klein** [comment]
As I recall, this was something that Dan Garrette set up, in order to generate new variable names. One persistent problem with it was that when generating doctest results, we couldn’t reliably ensure that successive runs of the same test would generate the same variable names each time. I never succeeded in figuring out a solution. Is @jnothman's proposal going to make it easier to fix this?

**Comment by jnothman** [comment]
This should give equivalent functionality (as long as no one has been
resetting the counter)... so I don't think it's any easier, but doesn't use
a custom helper
