### ISSUE TITLE
Support Brat format

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#668]
Write a module to convert between NLTK's chunk structures to files in Brat format, cf http://brat.nlplab.org/standoff.html, http://stackoverflow.com/questions/23146072/converting-nltk-phrase-structure-trees-to-brat-ann-standoff, https://github.com/nlplab/brat

**Comment by larsmans** [comment]
I'm not volunteering, but I am pinging myself because I want to add Brat format support to [xtas](https://github.com/NLeSC/xtas) and we might be able to share code.

**Comment by jnothman** [comment]
I wrote a response on the stackoverflow, handling that case only. The issue
with Brat is that you have to choose how to represent a particular bit of
data: were our tree strictly binary, we could represent it with relations;
otherwise it's resented as nested text-bound annotations, and they
currently don't show an example where they have anything like a
constituency parse. So saying "I'm going to write an importer/exporter for
brat" means you have to make some decisions about exactly what that
can/will represent. NLTK can include an importer for text-bound structures,
if it can ensure that they are aligned to tokens (and the brat raw text
need not be pre-tokenised) and tree-structured; it can include an importer
for entity-entity relations; or it can include an importer for dependency
tree. My point is merely that this needs some more specification.

**Comment by larsmans** [comment]
Given the annotation configuration, it should be possible to tell whether the intended annotation is tree or chain-structured.

**Comment by jnothman** [comment]
If I understand your suggestion, a converter (or at least an importer) would take Brat annotation configuration as input? I guess that has the potential to work. I'm still not sure of it in the context of NLTK.

**Comment by larsmans** [comment]
Yes. And if I understand @stevenbird correctly, the main thing on the NLTK wish list is a conversion in the opposite direction, which should be even easier.

**Comment by johncadigan** [comment]
I would be very interested in this. I'm looking for NLP projects to complete this summer. Would you like me to write it as a wrapper class to Tree or a module to manipulate files into .ann + .txt? What about the other data models supported by brat such as dependency graphs?

**Comment by bryandeng** [comment]
Hi, @stevenbird.

How's the progress of this enhancement? I need exactly this feature in a recent project. If you would like, I can start to write some code for this.

**Comment by stevenbird** [comment]
@bryandeng, @johncadigan: sorry for the delay – is this still relevant for you? How widely used is Brat?
