### ISSUE TITLE
Improve IPython Notebook usability by providing custom object display

### ISSUE THREAD

**Issue by jnothman** [nltk/nltk#684]
IPython Notebook is a very popular way of working with mixed media (code, printed output, images, arbitrary HTML) in an interactive research/development environment. By implementing a magic method on a class, it can be displayed as an image or interactive object rather than a textual `repr`esentation.

We should identify classes in NLTK (e.g. `Tree`) that could be easily visualised in this framework, and thus enhance the experience working with NLTK, choosing to implement one of the following methods:
- `_repr_html_`
- `_repr_latex_`
- `_repr_svg_`
- `_repr_jpeg_`
- `_repr_png_`

Note: a list of classes that currently implement `__str__` and hence would be straightforward candidates can be acquired with `git grep -pE 'def __str__' | grep 'class ' | sed 's/(.*//'`

**Comment by stevenxxiu** [comment]
I've tried to use `_repr_pdf_` for trees, which output postscript from tkinter (https://github.com/jskda/nltk/tree/pull_request.684) but firefox doesn't appear to support this. I think it might be better to use svg or png in the cases of postscript files.

**Comment by kowey** [comment]
Hello @jskda! I was wondering if you'd be kind enough to look into [my _repr_png patch](https://github.com/kowey/nltk/commit/4ac4beacff7f9363c84e5d72719e2b5cda8267f2).  Unfortunately, shell=true seems to break on MacOS X. I'm not entirely sure why. 

Was `shell=true` introduced because of Windows's behaviour? (opening a console window?).  This SO post seems to say you can [set a Windows `STARTUPINFO.wShowWindow` attribute](http://stackoverflow.com/questions/6390394/executing-subprocess-from-python-without-opening-windows-command-prompt) instead.

Thanks!
