### ISSUE TITLE
More permissive regular expression for finding Stanford Models

### ISSUE THREAD

**Issue by wenkokke** [nltk/nltk#731]
Using Homebrew, the models jar is (currently) installed as `stanford-parser-3.4-models.jar`, which NLTK is unable to detect. It reports:

```
===========================================================================
  NLTK was unable to find stanford-
  parser-(\d+)\.(\d+)\.(\d+)-models\.jar! Set the CLASSPATH
  environment variable.

  For more information, on stanford-parser-(\d+)\.(\d+)\.(\d+)-models\.jar, see:
    <http://nlp.stanford.edu/software/lex-parser.shtml>
===========================================================================
```

Would it be a good idea to use a more permissive regular expression to find the models jar? For instance...

```
stanford-parser-(\d)(\.(\d))+-models\.jar
```

...so that it is detectable even if it doesn't have a version with precisely _three_ numbers.

**Comment by stevenbird** [comment]
Thanks @pepijnkokke

**Comment by shijunil** [comment]
Hi 
I m facing a similar problem in a python code which uses stanford parser.

shiju@shiju-Satellite-C665D:~/Downloads/SVO_Extractor-master/stanford-parser-2012-07-09$ python svo.py 
Traceback (most recent call last):
  File "svo.py", line 204, in <module>
    svo = SVO()
  File "svo.py", line 37, in **init**
    self.parser = stanford.StanfordParser(model_path="/home/shiju/Downloads/SVO_Extractor-master/stanford-parser-2012-07-09/edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz")
  File "/usr/local/lib/python2.7/dist-packages/nltk/parse/stanford.py", line 99, in **init**
    key=lambda model_name: re.match(self._MODEL_JAR_PATTERN, model_name)
  File "/usr/local/lib/python2.7/dist-packages/nltk/internals.py", line 675, in find_jar_iter
    raise LookupError('\n\n%s\n%s\n%s' % (div, msg, div))
LookupError: 

# 

  NLTK was unable to find stanford-parser-(\d+)(.(\d+))+-models.jar!
  Set the CLASSPATH environment variable.

  For more information, on stanford-parser-(\d+)(.(\d+))+-models.jar, see:
    http://nlp.stanford.edu/software/lex-parser.shtml

Can you please help. Thanks

**Comment by ritwikmishra** [comment]
if anybody is still getting this error
```
NLTK was unable to find stanford-parser-(\d+)(\.(\d+))+-models\.jar!
```
Short version: Use this
```
parser = StanfordParser(path_to_models_jar="/path/to/englishPCFG.ser.gz")
```
Long version:
It means stanford.py is not able to locate your models jar file of the parser. Generally, the models jar is located at ```/your-path/stanford-parser-full-2018-10-17/stanford-parser-3.x.x-models.jar```

The purpose to locate models.jar is to find the englishPCFG.ser.gz file inside the jar. If you open the jar file through an archive manager, you can see the file there (```edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz```)

Now your job is to help stanford.py to locate this englishPCFG.ser.gz. Try extracting englishPCFG.ser.gz from the models.jar file. Copy the path of englishPCFG.ser.gz (wherever you extracted it). And pass it to the StanfordParser() as
```
parser = StanfordParser(model_path="/path/to/englishPCFG.ser.gz")
```
If it doesn't work and the error persists. Look around the line at which this error is generating. It seems that with time nltk will keep updating the file stanford.py. Therefore, what I tell henceforth will not be applicable always so use your discretion as well. In my case the error was originating at line 62
```
key=lambda model_path: os.path.dirname(model_path)
```
The entire block was 
```
        model_jar=max(
            find_jar_iter(
                self._MODEL_JAR_PATTERN, path_to_models_jar,
                env_vars=('STANFORD_MODELS', 'STANFORD_CORENLP'),
                searchpath=(), url=_stanford_url,
                verbose=verbose, is_regex=True
            ),
            key=lambda model_path: os.path.dirname(model_path)
        )
```
where 
```
_MODEL_JAR_PATTERN = r'stanford-parser-(\d+)(\.(\d+))+-models\.jar'
path_to_models_jar=None
```
these variables were written above the block. I had to find them by manually searching. I realized that the block is trying at various places to find the models.jar file but it is not able to. So I tried different methods and all of them worked!
1) set environment variable ```STANFORD_MODELS``` to the folder which contains the models.jar file.
or
2) instead of ```model_path```, pass ```path_to_models_jar``` with the absolute location of englishPCFG.ser.gz
```
parser = StanfordParser(path_to_models_jar="/path/to/englishPCFG.ser.gz")
```

How to set an environment variable?
```
sudo nano ~/.bashrc
```
Add this line at the end
```
export STANFORD_MODELS=/path/to/wherever/you/want
```
