### ISSUE TITLE
NERTagger stops tagging at first: ? ! .

### ISSUE THREAD

**Issue by vaisov** [nltk/nltk#761]
How to reproduce:

```
from nltk.tag.stanford import NERTagger
import sys, os

classifier = '/opt/stanford-ner/classifiers/hgc_175m_600.crf.ser.gz'
ner = '/opt/stanford-ner/stanford-ner.jar'
nt = NERTagger(classifier, ner, 'utf-8')

nt.tag('einen schönen. guten abend. freue mich sehr, dass sie dabei sind herzlich'.split())
```

output:

```
[(u'einen', u'O'), (u'sch\xf6nen', u'O'), (u'.', u'O')]
```

However POSTagger works without problem with same texts.

**Comment by alvations** [comment]
Related to NER tagger, http://stackoverflow.com/questions/26352041/nltk-entity-extraction-difference-from-nltk-2-0-4-to-nltk-3-0

**Comment by vaisov** [comment]
I tried Stanford's NER tagger using NLTK 2.0.4, outcome is the same, no tagging after .!?

**Comment by stevenbird** [comment]
@desilinguist would you please advise?

**Comment by desilinguist** [comment]
I don't know much about the NERTagger portion since I only wrote the POSTagger wrapper. However, I can take a more detailed look and report back.

**Comment by stevenbird** [comment]
Oh, no problem. Before you do that, can @vaisov confirm that the Stanford NER tagger behaves in the desired manner when invoked directly, i.e. on the command line?

**Comment by vaisov** [comment]
Sure. Here are results of using command line without python.

```
root@localhost:/opt/stanford-ner# cat 1
einen schönen guten abend. freue mich sehr, dass sie dabei sind. herzlich willkommen zu unserer sendung. schönen guten abend in die runde. freue mich sehr, dass ihr alle da seid.

root@localhost:/opt/stanford-ner# ./ner.sh 1
CRFClassifier invoked on Thu Oct 16 15:18:29 UTC 2014 with arguments:
   -loadClassifier ./classifiers/hgc_175m_600.crf.ser.gz -textFile 1 -outputFormat slashTags
loadClassifier=./classifiers/hgc_175m_600.crf.ser.gz
textFile=1
outputFormat=slashTags
Loading classifier from ./classifiers/hgc_175m_600.crf.ser.gz ... done [57.1 sec].
einen/O schönen/O guten/O abend/O ./O
freue/O mich/O sehr/O ,/O dass/O sie/O dabei/O sind/O ./O
herzlich/O willkommen/O zu/O unserer/O sendung/O ./O
schönen/O guten/O abend/O in/O die/O runde/O ./O
freue/O mich/O sehr/O ,/O dass/O ihr/O alle/O da/O seid/O ./O
CRFClassifier tagged 37 words in 5 documents at 149.19 words per second.
```

**Comment by desilinguist** [comment]
Okay, I looked at this and I think I know what's going on. The main difference is that we are passing `-tokenize false` as part of the  `POSTagger` command but no such option is being passed to the `NERTagger`. Let's look at an example. Let's say this our text to tag is:

```
I am going to fly to Paris tomorrow. Is Pierre going to come with me?
```

If I use the `_cmd` property that's constructed for an `NERTagger` instance to tag this on the command line, I get:

``` bash
$> java -cp ~/work/NLPTools/stanford-ner/stanford-ner.jar edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier /Users/nmadnani/work/NLPTools/stanford-ner/classifiers/english.all.3class.distsim.crf.ser.gz -textFile test.txt -outputFormat slashTags
loadClassifier=/Users/nmadnani/work/NLPTools/stanford-ner/classifiers/english.all.3class.distsim.crf.ser.gz
textFile=test.txt
outputFormat=slashTags
Loading classifier from /Users/nmadnani/work/NLPTools/stanford-ner/classifiers/english.all.3class.distsim.crf.ser.gz ... done [1.5 sec].
I/O am/O going/O to/O fly/O to/O Paris/LOCATION tomorrow/O ./O 
Is/O Pierre/O going/O to/O come/O with/O me/O ?/O 
```

Note that the output is sentence tokenized. The output for the `tag()` method is the first element of the output of `tag_sents()` which means that in this case we will just return the first sentence.

However, if I use the `_cmd` property that's constructed for a `POSTagger` instance to tag this on the command line, I get (note the `-tokenize false` part):

``` bash
$> java -cp ~/work/NLPTools/stanford-pos/stanford-postagger.jar edu.stanford.nlp.tagger.maxent.MaxentTagger -model /Users/nmadnani/work/NLPTools/stanford-pos/models/english-left3words-distsim.tagger -textFile test.txt -tokenize false
Loading default properties from tagger /Users/nmadnani/work/NLPTools/stanford-pos/models/english-left3words-distsim.tagger
Reading POS tagger model from /Users/nmadnani/work/NLPTools/stanford-pos/models/english-left3words-distsim.tagger ... done [0.6 sec].
I_PRP am_VBP going_VBG to_TO fly_VB to_TO Paris_NNP tomorrow._NNP Is_VBZ Pierre_NNP going_VBG to_TO come_VB with_IN me?_NN
Tagged 15 words at 714.29 words per second.
```

Note that the output is _not_ sentence tokenized. Therefore, returning the first element returns the whole tagged text as a single sentence. 

So, to fix this, I think we need to make sure that the output of the NERTagger is also not sentence tokenized. According to the [Stanford NER FAQ](http://nlp.stanford.edu/software/crf-faq.shtml#tokenized), to do this, we need to add the following option to the `_cmd` property: `-tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer -tokenizerOptions "tokenizeNLs=false"`

And, indeed, if I make this change, this issue is resolved. However, I thought it'd be prudent to further test this and so I modified my text to separate the punctuation as a word tokenizer might do:

```
I am going to fly to Paris tomorrow . Is Pierre going to come with me ?
```

With this text, turning off tokenization for `NERTagger` doesn't fix the issue. So, this change isn't the complete solution. Another option is to do the opposite: turn on tokenization for the POSTagger and modify `tag()` to explicitly join the tagged sentences.

Thoughts?

**Comment by lenazun** [comment]
In order to return all sentences I changed tag() to return self.tag_sents([tokens])[0:] instead of just [0]

**Comment by dimazest** [comment]
@lenazun, would it make sense to return `self.tag_sents([tokens])`?

**Comment by lenazun** [comment]
@dimazest  Yes, that works too!  just wanted to be explicit about the change.

**Comment by stevenbird** [comment]
This is an issue with the Stanford Named Entity Tagger, and @longdt219 has reported it here:
https://mailman.stanford.edu/pipermail/java-nlp-user/2015-January/006722.html

**Comment by alvations** [comment]
@longdt219 issue was because the stanford tools commands in NLTK's API are static:
- POS: https://github.com/alvations/nltk/blob/develop/nltk/tag/stanford.py#L126
- NER: https://github.com/alvations/nltk/blob/develop/nltk/tag/stanford.py#L159

`-tokenizerOptions "tokenizeNLs=true"` arguments are needed to keep newlines.

**Comment by longdt219** [comment]
Hi @alvations, 
The problem is not about keeping newlines with `-tokenizerOptions "tokenizeNLs=true"`
The problem is how to stop stanford tokenizer because the input is already tokenized. 
This was done in stanford POS by passing the argument `-tokenize false`
However this is not implemented in NER and using `-tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer's didn't solve the problem as I reported in 
https://mailman.stanford.edu/pipermail/java-nlp-user/2015-January/006722.html

**Comment by stevenbird** [comment]
@longdt219  please follow up with the java-nlp-user forum.
