### ISSUE TITLE
'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'

### ISSUE THREAD

**Issue by Liontooth** [nltk/nltk#803]
Hi Steven --

I'm getting this error on threading with python 2.7.8.11 on Debian -- 

```
    threads = []
    for year in [2007, 2008, 2009, 2010, 2011, 2012, 2013]:
        t = threading.Thread(target=count_year, args=(year, phrases_dict))
        t.daemon = True
        t.start()
        threads.append(t)

    for t in threads:
        t.join()
```

The first thread works fine, and the subsequent fail:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "phrase-count.py", line 137, in count_year
    feature_vector = _count_phrases(captionfile, phrases_dict)
  File "phrase-count.py", line 102, in _count_phrases
    words = _read_caption_and_clean(captionfile)
  File "phrase-count.py", line 76, in _read_caption_and_clean
    return cleansing.clean(words)
  File "/home/liontooth/Programming/count-phrases/cleansing.py", line 10, in clean
    words = [__morphy(w) for w in words]
  File "/home/liontooth/Programming/count-phrases/cleansing.py", line 47, in __morphy
    result_set.insert(0, wn.morphy(word, wn.NOUN))
  File "/usr/lib/python2.7/dist-packages/nltk/corpus/util.py", line 99, in __getattr__
    self.__load()
  File "/usr/lib/python2.7/dist-packages/nltk/corpus/util.py", line 73, in __load
    args, kwargs  = self.__args, self.__kwargs
AttributeError: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'
```

Any reason the threading is not working?

Cheers,
Dave

**Comment by stevenbird** [comment]
NLTK has not been written to be thread-safe. I don't know why a problem would show up here, particularly. Are you able to reproduce the error within a single thread?

**Comment by Liontooth** [comment]
No, a single thread works fine, which also means I can work around it. However, this code worked fine in July 2013, so it's fairly likely there's a regression introduced by an upgrade somewhere. It may be difficult to determine which upgrade of which component; the script is phrase-count.py in https://github.com/hang-qi/CDI/tree/master/tools/count-phrases

Cheers,
David

**Comment by stevenbird** [comment]
The changes between NLTK 2 (from 2013) and NLTK 3 are extensive! Can you please supply a complete code sample that allows the problem to be replicated? That would be a good start at least.

**Comment by jnothman** [comment]
Is the lazy loading engineered to be thread-safe? otherwise, it seems
something very likely to blow up in multithreading.

In any case, multithreading is a form of parallelism that is not often very
effective in Python, because any object reference manipulation requires
holding a global mutually exclusive lock (the GIL). Multithreading is only
likely to provide substantial benefits when the most expensive operations
release the GIL, which only occurs for some builtin operations and C
extensions (e.g. numpy vectorised operations).

If you need parallelism, multiprocessing is more reliable (although it
carries some overhead in Windows). Memory blowout can be an issue, but
memory can be shared through memmapped data if handled appropriately (the
joblib library may help make this easy).

**Comment by Liontooth** [comment]
Multiprocessing in fact is perfectly adequate for my task, so multi-threading is likely not worth pursuing. The code I link to above is complete if anyone should want to pursue it, but it sounds like this is not a good use of NLTK time.

Thank you for the feedback!

Cheers,
David
