### ISSUE TITLE
Efficiency of new dependency representation

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#878]
PR #822 included https://github.com/nltk/nltk/commit/e0f0630155eec7e0df5b907ee523ad7ed8a04f5b in which `self.nodes` was changed from `defaultdict(lambda: {'deps': []})` to `defaultdict(lambda: {'deps': defaultdict(list)})`. At the inner level, we've replaced a list with a defaultdict over lists. I'm concerned about the performance consequences of this more expensive representation. @dimazest would you be able to test this and report back here please?

**Comment by dimazest** [comment]
Hi, I'm using DependencyGraph to extract dependencies from ukwac and didn't notice any speed penalty, but I don't have any concrete numbers, so I might be wrong.

It might be the case that `defaultdict`s are more efficient, because iterations like https://github.com/nltk/nltk/pull/879/files#diff-5771d1c43509b27a40aee3c0debde28eL715 are not needed anymore.

Actually, I think that the code that uses DependencyGraph currently relies too much on its internal implementation. Methods like `get_by_address()` is a good step in the right direction where client code (for example, `nonprojectivedependencyparser`) abstracts away from DependencyGraph's internal structure and uses a high-level API. But, it could be done differently by implementing `__getitem__()`

The API should provide common use cases, something like "give me nodes of the graph ordered by the appearance in the sentence". Right now ordering is done outside of DependencyGraph which leads to code repetition, and potential problems with new code.

So far I've concentrated more on code being intuitive, but I'll also pay attention to efficiency.

**Comment by stevenbird** [comment]
I've done some of my own testing of loading a dependency graph, and parsing a sentence using a dependency grammar, in 3.0.1 and in pre-3.0.2, and there's no significant performance impact from the new representation. Loading a graph was slightly faster, though I'm not sure why.
