### ISSUE TITLE
Question about wordnet.path_similarity() results

### ISSUE THREAD

**Issue by iliakur** [nltk/nltk#897]
While getting similarity measures between synsets with different parts of speech, I noticed that more pairs than I had expected were showing as `Null`. I decided to investigate and discovered that I could get rid of these `Null`s (and arrive at float scores) if I just changed the order of the arguments to `wordnet.path_similarity()`. Below is a minimal working example:

``` python
>>> from nltk.corpus import wordnet as wn
>>> hell = wn.synset('hell.n.01')
>>> abduct = wn.synset('kidnap.v.01')
>>> print wn.path_similarity(hell, abduct)
None
>>> a =  wn.path_similarity(abduct, hell)
0.1
```

I'm aware that getting similarity scores between nouns and verbs is squirrelly, but that issue aside, isn't it odd that this works only one way? Moreover, this behavior does not affect _all_ noun-verb pairs, some are reversible.
Any thoughts?

**Comment by trinitys** [comment]
path_similarity() across parts of speech is not commutative (by design). The key to that is the difference in the notion of root for different synsets. If you look into the code for path_similarity(), you'll notice the default variable simulate_root=True, that creates a dummy root in the tree of the taxonomy that allows traversing from one part of speech to another in the first place. Also notice the call to self._needs_root() which returns whether a synset needs to be assigned a root. This method acts differently for wn.synset('hell.n.01') and wn.synset('kidnap.v.01') and causes the difference in behavior you're noticing.

**Comment by iliakur** [comment]
Thanks, @trinitys! `self._needs_root()` was the detail I was missing. Was under the impression that `simulate_root=True` would have led to commutativity, but was wrong. I'm closing this issue, the question has been answered.
