### ISSUE TITLE
Interface to Kaldi HMM toolkit?

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#906]
Explore the possibility of interfacing NLTK to [Kaldi](http://kaldi.sourceforge.net/about.html), via [pykaldi](https://github.com/UFAL-DSG/pykaldi) (from @oplatek).

**Comment by oplatek** [comment]
Hi,
I do not think it is feasible right know because
1) The pyfst wrapper for my inkremental decoder interface can be built only for Ubuntu 14.04 (tested) and Ubuntu 12.04 (not tested right now)
I would need to figure out how to transfer compilation parameters from Kaldi configure to cython setup.py (and this is not my priority)
2) Kaldi and mainly openfst compiles about 15 minutes with paralelized build on average notebook
3) I have only a few acoustic and language models for English and Czech right

On the other hand, I and @choko will be interested to write a client for our cloud asr service (www.cloudasr.com), which is going to be much improved

See the terms of usage http://demo.cloudasr.com/, if it is OK for nltk
