### ISSUE TITLE
NLTK.Text UnicodeDecodeError

### ISSUE THREAD

**Issue by sathik11** [nltk/nltk#915]
Example 
text_sample: "i have this card for about 1 1/2 year now and it have perform flawlessly"
text1 = nltk.Text(nltk.word_tokenize(text_sample))

When i run above code snippet in 64 bit machine(python 2.7, sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)) i get 
""ascii' codec can't decode byte 0xa0 in position " error" at 
...\ntlk\text.py line 304 self.name = " ".join(text_type(tok) for tok in tokens[:8]) + "..."

whereas in my 32 bit system(python 2.7,sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)) it works fine . 

in 64 bit machine =  'i have this card for about 1\xc2\xa01/2 year now '
and in 32 bit    =  'i have have this card for about 1\xa01/2 year now '

--possibly in compat.py text_type is not set properly

( when i decode the text to "utf-8" there isnt any issue)

**Comment by kmike** [comment]
Hi @sathik11,

In Python 2.x `'i have this card for about 1\xc2\xa01/2 year now '` is a byte string (unless unicode_literals future import is active); NLTK expects unicode as an input. So you're passing incorrect input to NLTK, that's why it fails.

Try `u'i have this card for about 1\xa01/2 year now '` or `u"i have this card for about 1 1/2 year now and it have perform flawlessly"` - decode your text from utf-8 before passing it to NLTK.
