### ISSUE TITLE
nltk_tgrep

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#931]
@wroberts would you be open to the idea of incorporating [nltk_tgrep](https://github.com/wroberts/nltk_tgrep) into NLTK? (I learnt about nltk_tgrep from [this post on nltk-users](https://groups.google.com/forum/#!topic/nltk-users/iyCelNfsZ0U)).

**Comment by wroberts** [comment]
Hi Dr. Bird,

Thanks for your message!  I'd be happy to see `nltk_tgrep` go into NLTK.  It seems to me that `nltk_tgrep` fits well into the NLTK project, and should be added to NLTK if possible.  I would be willing to continue maintaining the code, if you'd like.

The module is currently useable and has fairly good unit test coverage; I'm in contact with Prof. Emily Bender, which might result in a few more tgrep2 search features getting implemented.  She also mentions the documentation being a bit sparse, so perhaps that's something that will also need to be improved in the future.

A few thoughts about integration with NLTK:
- Where would the module go?  `nltk.parse.tgrep.py`, or maybe `nltk.tgrep.py`?  There's an opportunity here to rename things or otherwise make the interface different to fit better with NLTK.
- What should we do about `nltk_tgrep`'s requirements (pyparsing, future)?

Best,
Will

**Comment by stevenbird** [comment]
Thanks @wroberts! I think it can live in `nltk/tgrep.py`. It would be great if you would continue to maintain it there. It needs to be ported to Python 3 – is that something you would have time to do? The pyparsing dependency should only be an issue at runtime. I.e.:

```
try:
    import pyparsing
except ImportError:
    pass
```

**Comment by wroberts** [comment]
`nltk_tgrep` currently does py26, py27, py32, py33, and py34 (I'm using `future` to provide compatibility between py2 and py3).  I suppose `future` can be imported the same way as `pyparsing`, by simply throwing out ImportError.

I'll remove the license statement from the source (I'm currently distributing `nltk_tgrep` under MIT, but Apache-2.0 would work fine, too), `filter-branch` and send you a pull request as soon as I get a chance.

**Comment by stevenbird** [comment]
@wroberts what do you think about modifying the interface to `tgrep_positions` and `tgrep_nodes` to support a list of trees as the first parameter? Then the overheads for processing the query expression would be amortised over all the trees being queried.

**Comment by wroberts** [comment]
Hi @stevenbird that's a nice thought.

It's certainly true that compiling the tgrep node predicate takes much more time than running the tgrep predicate over the nodes in a tree.  When I use tgrep searching, I tend to pre-compile the tgrep search strings (much the same way that you might precompile a regex that you use a lot) so that they're only built once, instead of every time a search is run.

The solution you suggest is also valid, and makes it easier to build one node predicate and use it against many trees.  Maybe something like the code in #964 would work?

**Comment by stevenbird** [comment]
Thanks for your work @wroberts!
